### ISSUE TITLE
滚动是文档中的元素的offsetTop应该不变

### ISSUE THREAD

**Issue by zelllez** [openkraken/kraken#1000]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

Flutter 2.2.3 • channel stable • flutter/flutter.git
Framework • revision f4abaa0735 (6 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

kraken: 0.8.4
kraken_devtools: 0.3.1
kraken_websocket: 0.2.0+1
rax 1.2.2

### 重现步骤 ｜ Steps To Reproduce

https://codesandbox.io/embed/rax-quick-start-forked-51to3?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fpages%2FHome%2Findex.tsx&theme=dark

**重现代码 | Code example:** 

见上

**预期结果 ｜ Expected results:** 

滚动时offsetTop应该是固定的而不是可变的

**实际结果 ｜ Actual results:** 
变化

**Comment by temper357** [comment]
能否升级到 0.10-rc.1 版本确认下?  0.9.0 版本进行了大量重构，修复了大量渲染一致性问题

**Comment by zelllez** [comment]
> 能否升级到 0.10-rc.1 版本确认下? 0.9.0 版本进行了大量重构，修复了大量渲染一致性问题

升级0.10后，websocket包用不了版本不一致，
我尝试build来跑（rax-app+target=kraken）（这个不太靠谱，每次都build？），但是却出现__weex_require__这个关键字的报错，走不下去，而且0.8.4以上的开发者工具缺失，这个升级没好处暂时对于框架不是很成熟的时候来说，有没有什么升级的路径建议？

**Comment by zelllez** [comment]
@temper357 我更新了一下这个issue，剩余一个问题

**Comment by temper357** [comment]
iframe 可以通过插件支持，试一下装这个插件 https://openkraken.com/plugins/official/kraken_webview

**Comment by zelllez** [comment]
> iframe 可以通过插件支持，试一下装这个插件 [openkraken.com/plugins/official/kraken_webview](https://openkraken.com/plugins/official/kraken_webview)

好的我试试，谢谢，这个issue主要关注的是offsetTop哈，大佬有空帮手看看，谢谢
