### ISSUE TITLE
什么时候能适配flutter2.8

### ISSUE THREAD

**Issue by krisfly** [openkraken/kraken#1002]
### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by answershuto** [comment]
近期打算切 2.5，我们升级 flutter 一般等新版本出来后稳定一段时间。

**Comment by yifei8** [comment]
> 近期打算切 2.5，我们升级 flutter 一般等新版本出来后稳定一段时间。

目前支持的是哪个版本，我flutter降到2.2.0/2.3.0的版本，在windows上还是会报以下错误。

Unhandled exception:
Invalid argument(s): A directory corresponding to fileSystemPath "C:\Users\xxxx\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\devtools-2.9.2\build" could not be found
#0      createStaticHandler
package:shelf_static/src/static_handler.dart:50
#1      defaultHandler (package:devtools_server/src/external_handlers.dart:38:23)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:215:15)
<asynchronous suspension>
#3      serveDevToolsWithArgs (package:devtools_server/src/server.dart:73:10)

<asynchronous suspension>
E/flutter (16565): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libkraken.so': dlopen failed: library "libkraken.so" not found

**Comment by fadeAce** [comment]
请到 https://docs.flutter.dev/development/tools/sdk/releases?tab=windows stable channel
下载 v2.2.1版本，并设置好PATH 不要使用cherrypick或者 git reset方式降级flutter版本

**Comment by wssgcg1213** [comment]
@yifei8 Windows 暂时还没支持上, 需要先把 libkraken.dll 构建出来

**Comment by wssgcg1213** [comment]
目前最新版本 0.10.0 支持到 2.5.x, 一般情况下我们会比 flutter 官方延迟一个版本适配(因为实际使用的人比较少, 且会有一些明显 bug)   

实在需要 2.8 的可以用源码的方式切过去跑一下, 但是我们也不清楚会发生什么, 你可能需要有解决这些问题的准备, 经验来说通常不会太复杂
