### ISSUE TITLE
Heap free 的时候可能引发不当释放 SIGABRT

### ISSUE THREAD

**Issue by fadeAce** [openkraken/kraken#1007]
集成kraken到demo app中，引入事先打包好的app.js并作跳转，点开kraken页面，然后关闭，再点开关闭多次 基本稳定复现，控制台错误如下，本次是关闭并打开第三次崩溃

```
flutter: Getting bundle for contextId: 0, src: assets://assets/script/app.js
this.route.path
flutter: Getting bundle for contextId: 1, src: assets://assets/script/app.js
this.route.path
Runner(6570,0x16dceb000) malloc: Heap corruption detected, free list is damaged at 0x283deb520
*** Incorrect guard value: 120865603695903
Runner(6570,0x16dceb000) malloc: *** set a breakpoint in malloc_error_break to debug
* thread #12, name = 'io.flutter.1.ui', stop reason = signal SIGABRT
    frame #0: 0x00000001b794a964 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b794a964 <+8>:  b.lo   0x1b794a984               ; <+40>
    0x1b794a968 <+12>: pacibsp 
    0x1b794a96c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b794a970 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.
```

###  版本 信息

flutter version: 
version detail: v2.2.1 stable
Framework • revision 02c026b03c (7 months ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

Kraken版本是 0.10.0-rc.1

测试设备为 安卓设备/iphone 12promax

### 为了方便debug 提交测试工程如下
可直接debug：
报错来源于APP：https://github.com/EntySquare/miniapp-demo
APP中的kraken页面来源于vue demo项目：https://github.com/EntySquare/miniapp-nikestore-demo

**Comment by andycall** [comment]
Fixed on https://github.com/openkraken/kraken/pull/1020

**Comment by fadeAce** [comment]
Well, looks fine. Waitting for the merge

**Comment by andycall** [comment]
wait a moment，integration test not passed，
