### ISSUE TITLE
首屏速度慢

### ISSUE THREAD

**Issue by pba-cra** [openkraken/kraken#1009]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.8.4/0.10.0-rc-0
### 重现步骤 ｜ Steps To Reproduce

大量节点创建和样式设置

**重现代码 | Code example:** 
<img width="1836" alt="企业微信截图_3fff0e07-ba41-4b76-aaa2-92a006e073c9" src="https://user-images.githubusercontent.com/14161857/147205209-097919c5-7bb3-45ee-b2fd-8c959cc1ab5e.png">

**预期结果 ｜ Expected results:** 
js层进行节点的提交速度补慢于h5

**实际结果 ｜ Actual results:** 
有慢于h5

**Comment by andycall** [comment]
这个已经发现了，正在优化中。目前做了一部分 https://github.com/openkraken/kraken/pull/973

**Comment by answershuto** [comment]
这个验证了OK吗是不是可以i关了

**Comment by andycall** [comment]
还有 

https://github.com/openkraken/kraken/pull/1062

https://github.com/openkraken/kraken/pull/1063

**Comment by wssgcg1213** [comment]
@pba-cra 另外, 现在 kraken 已经支持部分的层叠样式, 选择器只支持 class 选择器  

你可以通过动态插入 style 标签或者 link 标签的形式引入外部样式, 这样可以减少 style 指令的数量
