### ISSUE TITLE
文本更新 Color 不应当触发 Layout

### ISSUE THREAD

**Issue by andycall** [openkraken/kraken#1010]
## 使用场景 ｜ Use case

现在通过 CSS 更新 color 会触发文本节点 layout，如果是动画场景，频繁 layout 会导致动画性能较差。

https://github.com/openkraken/kraken/blame/0e2d45adb2c48d28cdd0d8a26d722f64c9a0651d/kraken/lib/src/css/text.dart#L38

## 提案 ｜ Proposal

color 的更新只需要 markNeedsPaint，还需要 check 一下文本的其他属性是否也存在这些问题。

**Comment by yuanyan** [comment]
https://github.com/openkraken/kraken/blame/0e2d45adb2c48d28cdd0d8a26d722f64c9a0651d/kraken/lib/src/css/text.dart#L38 代码里现在就是 markNeedsPaint

**Comment by andycall** [comment]
诶，我记得当时是 layout 来找
