### ISSUE TITLE
flutter 集成 问题 mac-mini-m1

### ISSUE THREAD

**Issue by duleigiser** [openkraken/kraken#1011]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.9.0

### 重现步骤 ｜ Steps To Reproduce
按照文档https://openkraken.com/guide/native/interpolation-flutter
在flutter run 时候出现问题

flutter run
Launching lib/main.dart on iPhone 12 in debug mode...
Running pod install...                                             675ms
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: File exists @ syserr_fail2_in - /Users/lei/Desktop/sd/myapp/ios/.symlinks/plugins/connectivity.

     #  from /Users/lei/Desktop/sd/myapp/ios/Podfile:33
     #  -------------------------------------------
     #    use_modular_headers!
     >   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
     #    
     #  -------------------------------------------

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:335:in `rescue in block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:329:in `block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:327:in `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:327:in `from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:293:in `from_file'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:205:in `podfile'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:46:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
    rm: /Users/lei/Desktop/sd/myapp/ios/.symlinks/plugins/device_info: Permission denied
    rm: /Users/lei/Desktop/sd/myapp/ios/.symlinks/plugins/connectivity: Permission denied
    rm: /Users/lei/Desktop/sd/myapp/ios/.symlinks/plugins/kraken: Permission denied
    rm: /Users/lei/Desktop/sd/myapp/ios/.symlinks/plugins/shared_preferences: Permission denied
    rm: /Users/lei/Desktop/sd/myapp/ios/.symlinks/plugins: Permission denied
    rm: /Users/lei/Desktop/sd/myapp/ios/.symlinks: Permission denied

Error running pod install
Error launching application on iPhone 12.

### flutter 环境
$ flutter doctor -v
[✓] Flutter (Channel unknown, 2.2.3, on macOS 12.1 21C52 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/lei/flutter
    • Framework revision f4abaa0735 (6 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • 5EA92E06-CFD6-4959-BD68-F7EDDF173284 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 2 categories.

### 电脑环境

Darwin leideMac-mini.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64

**Comment by andycall** [comment]
![image](https://user-images.githubusercontent.com/4409743/147234518-304df9b1-83c6-436a-b2f0-b18e2b34236b.png)
你应该修复一下你本地的磁盘权限问题
