### ISSUE TITLE
Flex布局，复杂的ui场景下排版速度无法收敛。

### ISSUE THREAD

**Issue by pba-cra** [openkraken/kraken#1015]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.8.4，0.10.0-rc-1

### 重现步骤 ｜ Steps To Reproduce

![无标题流程图](https://user-images.githubusercontent.com/14161857/147308359-a6ba1f9b-f3cb-49af-be3a-43147b35eb63.png)

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 
排版响应速度不慢于h5

**实际结果 ｜ Actual results:** 
0.10.0-rc1,debug 70ms
0.8.4.debug 170ms

**Comment by yuanyan** [comment]
https://github.com/openkraken/kraken/pull/1023 merge 后可以再测试下
