### ISSUE TITLE
where is the quickjs.framework in 0.9.0 version ?   I can't find it 。

### ISSUE THREAD

**Issue by Blackwing-V** [openkraken/kraken#1017]

**Comment by andycall** [comment]
![image](https://user-images.githubusercontent.com/4409743/147331503-595b76a5-5e0c-423d-be65-bc5f33cfaeed.png)

**Comment by Blackwing-V** [comment]
大佬，我下载的kraken-0.9.0版本，里面的quickjs.xcframework打不开 
<img width="743" alt="截屏2021-12-24 下午4 33 46" src="https://user-images.githubusercontent.com/14243936/147335367-47f63339-7db8-4f41-a036-b244b8b49b25.png">

**Comment by andycall** [comment]
你没有编译吧

**Comment by Blackwing-V** [comment]
这个咋编译啊？ 有个交流群吗？
