### ISSUE TITLE
sliver性能有提升但是有一些加载的问题需要答疑，高度是必选的话对于变高的容器应该怎么集成

### ISSUE THREAD

**Issue by zelllez** [openkraken/kraken#1019]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

Flutter 2.2.3 • channel stable • flutter/flutter.git
Framework • revision f4abaa0735 (6 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

kraken: 0.8.4-0.10.0-rc.1都能重现
kraken_devtools: 0.3.1
kraken_websocket: 0.2.0+1
rax 1.2.2

### 重现步骤 ｜ Steps To Reproduce

https://codesandbox.io/embed/rax-quick-start-forked-j589d?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fpages%2FHome%2Findex.tsx&theme=dark

**重现代码 | Code example:** 
见上

**预期结果 ｜ Expected results:** 
1. 为何rax在kraken中useEffect获取不到dom的高度，而在浏览器可以
2. 为何有时候滚动会触发了一个下拉刷新的交互，中间的sliver容器也是，上滚后手势下滚之类的操作会导致看上去某种手势冲突在堆积，等一会又能滚了。

**实际结果 ｜ Actual results:** 
见上

**Comment by wssgcg1213** [comment]
我本地跑了一下你的脚本，原因是 sliver 的容器在渲染它的内容时，可能是异步的 (为了性能考虑)，所以在立刻获取它的子节点 boundingClientRect 时，未渲染的内容返回宽高位置都是 0。

具体在这一段 

```js
useEffect(() => {
    setTimeout(() => {
      // 这里不知道为何kraken会取不到渲染dom的高度，web可以
      setTick((i) => i + 1);
    }, 0);
  }, []);
```

`setTimeout(fn, 0)` 可以近似地看做立即执行，此时 DOM 结构中 sliver div 拥有它的 children，但是 renderObject tree 中它的子节点需要在下一帧渲染，所以获取到了高度为 0，进而执行到了 `setHeight('0px')`。  

我的建议是尽快固定容器的高度(比如100vh)，这样也能减少二次布局的消耗；如果不行的话，将上面的 setTimeout 用 requestAnimationFrame 替代可以让这个 demo 正常工作。

---

第二个问题, 我这边本地未复现, 或者你可以录个屏来看一下 (cc @answershuto)，我的环境是 macos + kraken 0.10 rc。滚动回弹是 ScrollPhysics 的设定, 在 iOS/macOS 是会回弹的, Android 下则无回弹效果，可以通过覆盖 `ScrollPhysics.scrollPhysicsFactory` 自定义这个行为。

**Comment by answershuto** [comment]
第二个问题是滚动过程中触顶（或底）会触发 bounce 效果，如果从顶（或底）开始滚动则会尝试触发滚动传递，会尝试将该滚动能力继续传递给下一个 scroll 容器，直到传递到最外层为止。

**Comment by zelllez** [comment]
> 我本地跑了一下你的脚本，原因是 sliver 的容器在渲染它的内容时，可能是异步的 (为了性能考虑)，所以在立刻获取它的子节点 boundingClientRect 时，未渲染的内容返回宽高位置都是 0。
> 
> 具体在这一段
> 
> ```js
> useEffect(() => {
>     setTimeout(() => {
>       // 这里不知道为何kraken会取不到渲染dom的高度，web可以
>       setTick((i) => i + 1);
>     }, 0);
>   }, []);
> ```
> 
> `setTimeout(fn, 0)` 可以近似地看做立即执行，此时 DOM 结构中 sliver div 拥有它的 children，但是 renderObject tree 中它的子节点需要在下一帧渲染，所以获取到了高度为 0，进而执行到了 `setHeight('0px')`。
> 
> 我的建议是固定滚动容器的高度(比如100vh)，这样也能减少二次布局的消耗；如果不行的话，将上面的 setTimeout 用 requestAnimationFrame 替代可以让这个 demo 正常工作，因为 requestAnimationFrame 的回调在下一帧布局执行之后触发。
> 
> 第二个问题, 我这边本地未复现, 或者你可以录个屏来看一下 (cc @answershuto)，我的环境是 macos + kraken 0.10 rc。滚动回弹是 ScrollPhysics 的设定, 在 iOS/macOS 是会回弹的, Android 下则无回弹效果，可以通过覆盖 `ScrollPhysics.scrollPhysicsFactory` 自定义这个行为。

下一帧可以获取~谢谢，这个能否文档出下，看来是个非标准的异步操作

**Comment by zelllez** [comment]
> 第二个问题是滚动过程中触顶（或底）会触发 bounce 效果，如果从顶（或底）开始滚动则会尝试触发滚动传递，会尝试将该滚动能力继续传递给下一个 scroll 容器，直到传递到最外层为止。

所以开发者能注意些什么？我们出现这个情形是在例子中某些交互时碰到

我们业务上诉求是这样子，如图：绿色是文档，黄色是屏幕，白色是组件树结构，
场景是组件都有可能变化高度，组件可以嵌套，内容也有变化高度需要，而内部list有很多item(几百)重复的组件需要用到sliver，而item不同组件可能不同，所以我们才走获取第一个组件的高度的一个sideeffect，
我们当前用法是如demo，那么用是不是合理的做法？有没有什么建议？ @wssgcg1213 @answershuto 

![image](https://user-images.githubusercontent.com/36196697/147441564-4b8f823b-c33d-426c-beee-cddc83d4f8fe.png)

**Comment by zelllez** [comment]
@answershuto 
那个滑动问题，表面看似乎是每个sliver列表里面都有个滑动方向的开关，现在每个方向滑动先都要往那个方向滑动一下才能切换滑动方向。
先滑a方向才能往a滑动，然后要a变成b方向要先滑b方向然后才能滑动b方向。

**Comment by wssgcg1213** [comment]
@zelllez 看了下你画的情况, 通常情况下 sliver 容器被设计用来处理平铺的 feeds 流场景, 你的情况看起来会出现不确定的嵌套层级, 而且我不太确定你需要回收的 sliver-item 会不会尺寸过大, 导致回收/创建过程中出现影响帧率的计算。  

或者能否设计一个规范, 让内层的容器高度透出给父层; 当然在初始化时的重复 layout 也许也OK，它的消耗仅是多出了 1frame (通常是16ms) 的时间, 看你是否可以接受吧。

**Comment by zelllez** [comment]
> @zelllez 看了下你画的情况, 通常情况下 sliver 容器被设计用来处理平铺的 feeds 流场景, 你的情况看起来会出现不确定的嵌套层级, 而且我不太确定你需要回收的 sliver-item 会不会尺寸过大, 导致回收/创建过程中出现影响帧率的计算。
> 
> 或者能否设计一个规范, 让内层的容器高度透出给父层; 当然在初始化时的重复 layout 也许也OK，它的消耗仅是多出了 1frame (通常是16ms) 的时间, 看你是否可以接受吧。

当前看1frame后可以获取，但是想问的是如果页面里面有20+个 sliver 容器， 每个sliver容器里面有300-500个feed的话，你认为 sliver容器是否需要自己实现个不在屏回收还是说本身kraken已经做了？因为同样的实现在chrome内是很丝滑但是在kraken里面比较卡

**Comment by wssgcg1213** [comment]
sliver 回收的是不在屏的子元素, 它自己是不会被回收的

**Comment by zelllez** [comment]
可关掉后面关于性能我再另外提个案例
