### ISSUE TITLE
Sliver中的子元素，如果未出现在屏幕中或者滑出后，该元素的排版信息缺失

### ISSUE THREAD

**Issue by pba-cra** [openkraken/kraken#1030]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.8.4/0.10.0-rc1

### 重现步骤 ｜ Steps To Reproduce

Sliver中的子元素，如果未出现在屏幕中或者滑出后，该元素的排版信息缺失

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 
元素无论是否在屏幕上 或者滑出屏幕 都能获取到排版信息

**实际结果 ｜ Actual results:** 
都是0， 因为是没有attached

**Comment by wssgcg1213** [comment]
是的, 这个是特性, 原理决定未生成的元素是不持有排版信息的

**Comment by wssgcg1213** [comment]
不仅是未 attach，甚至都没有创建 RenderObject，这里的出发点也是性能考量的

**Comment by pba-cra** [comment]
> 

这些是知道的。
主要跟h5的还是有区别所以提了一个问题

**Comment by wssgcg1213** [comment]
OK, 这个点暂时无解，我先 close 了。如果业务上必须要获取到不可见元素的 BoundingClientRect 或者滚动位置等, 只能是选择 overflow 的方式了~
