### ISSUE TITLE
sliver的滚动需要第二下才能滚的问题

### ISSUE THREAD

**Issue by zelllez** [openkraken/kraken#1037]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (6 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
kraken 0.10
android真机（华为mate40和三星note20u都重现到）

### 重现步骤 ｜ Steps To Reproduce

https://codesandbox.io/embed/rax-quick-start-forked-ygk4n?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fpages%2FHome%2Findex.tsx&theme=dark

**重现代码 | Code example:** 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/36196697/147651309-c845059f-65fb-4d58-bdcb-81012da0e4ce.gif)

**预期结果 ｜ Expected results:** 
第一下就可以滚动而不是同方向要第二下才可以，ps: 这个现象原以为是数据量会让sliver自动降级为普通列表，我尝试取3000数据量这个问题也消失了，比较怪异。

**实际结果 ｜ Actual results:** 
第二下滚动才可以

**Comment by wssgcg1213** [comment]
确实挺怪异的, 我们研究一下看看

**Comment by zelllez** [comment]
@wssgcg1213 你好这个问题有没有眉目?

**Comment by wssgcg1213** [comment]
可以看一下上面这个 PR, 是精度导致的。    
  
@zelllez 另外你的例子里面 sliver 容器的高度应该是可视区域的高度, 不是内部所有 item 的高度和

**Comment by zelllez** [comment]
> 可以看一下上面这个 PR, 是精度导致的。
> 
> @zelllez 另外你的例子里面 sliver 容器的高度应该是可视区域的高度, 不是内部所有 item 的高度和, 这样触发的实际上是 body 的滚动

😯这样子。。。。所以应该是screen.height?

**Comment by wssgcg1213** [comment]
对的, 容器的高度是可视区域 (viewport) 的高度, sliver 可以嵌套 sliver

**Comment by zelllez** [comment]
> 对的, 容器的高度是可视区域 (viewport) 的高度, sliver 可以嵌套 sliver
@wssgcg1213 
所以比如下面这个情况，1是可以写成高度是100vh，但是2,3的话应该写多少？
```html
<sliver name =1>
  <div></div>
   <sliver name=2/>
    <div></div>
   <sliver name=3/>
</sliver>
```
