### ISSUE TITLE
Screen.width和Screen.height的表现与预期不符

### ISSUE THREAD

**Issue by pba-cra** [openkraken/kraken#1039]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.8.4/main

### 重现步骤 ｜ Steps To Reproduce

Screen.width,Screen.height的返回值是Flutter中Window.physicalSize
而实际给kraken-widget的尺寸可能只是屏幕的一半。

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 
Screen.width,Screen.height的返回值是kraken-widget的尺寸大小

**实际结果 ｜ Actual results:** 
Flutter中Window.physicalSize

**Comment by airingursb** [comment]
这个应该是没问题的，`window.screen` 返回的宽高是设备的宽高，和容器无关

https://developer.mozilla.org/en-US/docs/Web/API/Screen/width#:~:text=The%20Screen.width%20read%2Donly%20property%20returns%20the%20width%20of%20the%20screen%20in%20pixels.

**Comment by airingursb** [comment]
这个没有问题，webview 在不做任何处理的时候，`window.screen` 默认返回的就是设备的逻辑宽高，无论这个 webview 视图控制器本身是多大

**Comment by wssgcg1213** [comment]
screen 描述的是屏幕的信息, 节点的尺寸可以用 document.documentElement 的计算尺寸
