### ISSUE TITLE
北海相对于weex来说，标签/样式/dom等前端环境优势有哪些。

### ISSUE THREAD

**Issue by yifei8** [openkraken/kraken#1049]
## 使用场景 ｜ Use case

北海相对于weex来说，标签/样式/dom等前端环境优势有哪些。
weex迁移成北海的成本能降低吗

**Comment by wssgcg1213** [comment]
北海的标签/样式/DOM 是参考浏览器标准设计的，Weex 更多是类似 Web 标签，细节差异比较多 (比如文本需要用 text 标签, 许多样式不支持)

**Comment by andycall** [comment]
kraken 有这和浏览器一样的线程模型，原生支持 HTML，CSS， DOM API，是面向 W3C 标准而开发的渲染引擎，所以 h5 页面可以很容易迁移过来。

weex 的实现是 weex 标准，前端布局都需要做一些调整。
