### ISSUE TITLE
事件冒泡在 dart 层实现，按需 dispatch 到 前端

### ISSUE THREAD

**Issue by answershuto** [openkraken/kraken#1050]
由于现在事件冒泡是在 bridge 实现的，导致 dart 测没有冒泡机制。

* 在脱离引擎工作时不能按照 web 标准工作（google 的 md 需求等）
* 想在 dart 通过冒泡做 document 上的监听处理一些事情时必须用比较 hack 的方式。

讨论是否可以移动到 dart 层实现。

**Comment by andycall** [comment]
dart 层实现冒泡会增加事件触发的通信压力

**Comment by answershuto** [comment]
对，所以按需，实际业务上不会在每个节点上都配置事件的。

**Comment by andycall** [comment]
考虑将冒泡的功能实现在脱离引擎的功能内。

**Comment by answershuto** [comment]
实际上按需不会牺牲性能的，除非业务真的给链路上的节点绑定上很多监听方法。
或许也可以在 dart 测实现一个内部的监听，按需冒泡。

**Comment by wssgcg1213** [comment]
我跟 @andycall 想法一样, 对主链路通信的损耗太大, 不建议这么做, 考虑做成可选项, 用不同的 API 触发?
