### ISSUE TITLE
When will next version be released? 

### ISSUE THREAD

**Issue by arasrezaei** [openkraken/kraken#1054]
thanks for your great project,
I always check your repo every day still waiting for next version.
when will next version be released?
does it support window?
can't wait for it 🙂.

**Comment by andycall** [comment]
Please wait patiently, there are still some work(multiple platform support, performance improve) to do. 

You can try 0.10.0-rc.1 version for testing.

**Comment by wssgcg1213** [comment]
Thanks for your concern, we will release ASAP :)
