### ISSUE TITLE
自定义元素列表报错 No Directionality widget found

### ISSUE THREAD

**Issue by hzbhzb** [openkraken/kraken#1072]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.10.0-rc.1

### 重现步骤 ｜ Steps To Reproduce
在flutter层定义一个列表，注册成自定义元素给js使用

**实际结果 ｜ Actual results:** 

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Text("cdfdsf", inherit: true, color: Color(0xff646464)):
No Directionality widget found.

RichText widgets require a Directionality widget ancestor.

The specific widget that could not find a Directionality ancestor was: RichText
  softWrap: wrapping at box width
  maxLines: unlimited
  text: "cdfdsf"
  dirty
The ownership chain for the affected widget is: "RichText ← Text ← _KrakenAdapterWidget ← RenderObjectToWidgetAdapter<RenderBox>-[GlobalObjectKey RenderIntrinsic#7e76f]"

Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget at the top of your application widget tree. It determines the ambient reading direction and is used, for example, to determine how to lay out text, how to interpret "start" and "end" values, and to resolve EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.

The relevant error-causing widget was: 
  Text file:///Users/huangzhebin/Documents/vipkraken/flutter_sample/lib/elements/define_left_widget.dart:52:12
When the exception was thrown, this was the stack: 
#0      debugCheckHasDirectionality.<anonymous closure> (package:flutter/src/widgets/debug.dart:272:7)
#1      debugCheckHasDirectionality (package:flutter/src/widgets/debug.dart:292:4)
#2      RichText.createRenderObject (package:flutter/src/widgets/basic.dart:5775:37)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5430:28)
#4      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6228:11)

**Comment by answershuto** [comment]
```
RichText widgets require a Directionality widget ancestor.
```

这个是 RichText Flutter 本身的限制，需要有一个方向性的祖先才可以 work ，需要在外层包一个。

**Comment by hzbhzb** [comment]
外层是有的了，在flutter直接调是没问题的，在kraken的外面是个MaterialApp->Scaffold

**Comment by answershuto** [comment]
我看一下

**Comment by hzbhzb** [comment]
层级是这样的，MaterialApp->scaffold->kraken,  之后kraken里面的js使用自定义的listview元素

**Comment by hzbhzb** [comment]
大佬有解决的方案吗

**Comment by answershuto** [comment]
我还没来得及看，手头有优先级更高的事情在跟，我晚点看一下

**Comment by answershuto** [comment]
@hzbhzb 这个怎么关了？是没问题了吗

**Comment by hzbhzb** [comment]
嗯，你们这个版本0.10.0-rc.2已经解决了
