### ISSUE TITLE
优化 opacity: 0 的性能

### ISSUE THREAD

**Issue by andycall** [openkraken/kraken#1097]
## 使用场景 ｜ Use case

设置 opacity: 0 会导致内容不可见。现在 Kraken 依然会创建 pushOpacityLayer，会浪费绘制性能。

## 提案 ｜ Proposal

可以考虑在当前帧直接不绘制 opacity: 0 内部的内容。

**Comment by yuanyan** [comment]
属于 fast path 优化，需要想下会不会有副作用

**Comment by wssgcg1213** [comment]
same as `visibility: hidden`

**Comment by wssgcg1213** [comment]
如果 opacity 为 0 导致的内容不可见, appear 事件是否应该触发
