### ISSUE TITLE
reload报错

### ISSUE THREAD

**Issue by jnxey** [openkraken/kraken#1100]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.10.0

### 重现步骤 ｜ Steps To Reproduce
使用samples-main内的hello-react示例，用kraken打开，进入后正常显示，执行kraken.reload()后报错
（在0.9.0版本时是正常的）

系统：windows 10
工具：Android studio

**重现代码 | Code example:** 
kraken.reload()

**预期结果 ｜ Expected results:** 
正常刷新

**实际结果 ｜ Actual results:** 
Build fingerprint: 'Redmi/picasso/picasso:10/QKQ1.191222.002/V12.0.7.0.QGICNXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-01-14 10:21:19+0800
pid: 9673, tid: 9716, name: 1.ui  >>> com.example.kraken_nl <<<
uid: 10402
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    x0  0000000000000000  x1  00000074ce33bd60  x2  000000754ce99ec0  x3  000000754ce99860
    x4  0000000000000000  x5  00000074d400a9a1  x6  00000074d9d16c39  x7  00000074d9d16bf9
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000005  x11 000000754ce99ec0
    x12 000000754ce99860  x13 0000000000000000  x14 0000000000000000  x15 00000074e9a3cdc0
    x16 0000000000000000  x17 00000074f1dd3038  x18 00000074e8ba0000  x19 00000074cf281748
    x20 000000754ce9c6a0  x21 000000754ce9c6f0  x22 00000074da688041  x23 000000754ce9c890
    x24 00000074da688041  x25 00000074e9964000  x26 00000074f1dd2a00  x27 00000074d9954fc0
    x28 0000000600000000  x29 00000074e9a3cdd0
    sp  00000074e9a3cdc0  lr  00000074da606b08  pc  0000000000000000
backtrace:
      #00 pc 0000000000000000  <unknown>
      #01 pc 0000000000086b04  <anonymous:74da580000>
Lost connection to device.

**Comment by wssgcg1213** [comment]
感谢反馈, 这个问题我们已经确认, 正在修复中
