### ISSUE TITLE
cli 启动官网项目白屏

### ISSUE THREAD

**Issue by 18zili** [openkraken/kraken#1108]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

v0.10.1

### 重现步骤 ｜ Steps To Reproduce

kraken https://raw.githubusercontent.com/openkraken/kraken/master/kraken/example/assets/bundle.js
![image](https://user-images.githubusercontent.com/31918458/149717097-3ac918a9-ca79-406c-b737-a0d93a62ea9c.png)

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 
成功渲染

**实际结果 ｜ Actual results:** 
白屏

**Comment by cnryb** [comment]
可能是遇到防火墙了。
测试一下在命令行中能不能访问到  https://raw.githubusercontent.com/openkraken/kraken/master/kraken/example/assets/bundle.js

**Comment by answershuto** [comment]
@andycall  cli 是基于哪个版本的，试了一下似乎有问题。

**Comment by 18zili** [comment]
> 可能是遇到防火墙了。 测试一下在命令行中能不能访问到 https://raw.githubusercontent.com/openkraken/kraken/master/kraken/example/assets/bundle.js

可以

**Comment by 18zili** [comment]
> @andycall cli 是基于哪个版本的，试了一下似乎有问题。

v0.10.1

**Comment by answershuto** [comment]
@18zili 上周发的有问题，正在重新发布

**Comment by 18zili** [comment]
> @18zili 上周发的有问题，正在重新发布

ok 感谢

**Comment by jnxey** [comment]
> @18zili 上周发的有问题，正在重新发布

0.10.0+2的版本，reload之后是白屏，用的是samples-main/hello-react的示例代码

**Comment by answershuto** [comment]
> 

reload 的问题见 pr —— https://github.com/openkraken/kraken/pull/1109

**Comment by jnxey** [comment]
> > 
> 
> reload 的问题见 pr —— #1109

ok

**Comment by 18zili** [comment]
@answershuto cli v0.10.2 未启动模拟器 直接结束进程了

**Comment by answershuto** [comment]
稍等下，看起来还有问题

**Comment by andycall** [comment]
可以尝试重新安装一下试试看

**Comment by snice** [comment]
kraken run https://raw.githubusercontent.com/openkraken/kraken/master/kraken/example/assets/bundle.js
用这个命令可以了

**Comment by 18zili** [comment]
@snice 你的cli是什么版本
@andycall 并不行

**Comment by 18zili** [comment]
不确定是不是cli引起的 我试了0.9 版本 也是白屏

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (3 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "macos_x64"

**Comment by 18zili** [comment]
@snice 可以了
