### ISSUE TITLE
devtools没有对应版本支持最新版的kraken

### ISSUE THREAD

**Issue by gplcn** [openkraken/kraken#1123]
我使用的kraken0.10.0版本，添加最新devtools依赖时提示：Because kraken_devtools >=0.2.0 <0.4.0-dev.0 depends on kraken ^0.8.0 and saas depends on kraken >=0.10.0, kraken_devtools >=0.2.0 <0.4.0-dev.0 is forbidden.

**Comment by wssgcg1213** [comment]
@gplcn  0.10.0 之后 devtools 被移动到了核心包内, 不需要再引入 pub 包了, 引用路径变成了 `package:kraken/devtools.dart`

**Comment by wssgcg1213** [comment]
文档我们补充一下
