### ISSUE TITLE
按照官方文档无法正常运行示例

### ISSUE THREAD

**Issue by Jingzhou** [openkraken/kraken#1130]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

kraken 0.10.0 
flutter 2.5.3
xcode 12.2

### 重现步骤 ｜ Steps To Reproduce

按照官方文档https://openkraken.com/guide/native/interpolation-flutter 运行示例

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 
正常运行

**实际结果 ｜ Actual results:** 
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    warning: [CP] Unable to find matching .xcframework slice in '/Users/apple/FlutterProjects/myapp/ios/Pods/../.symlinks/plugins/kraken/ios/kraken_bridge.xcframework kraken_bridge framework
    ios-x86_64-simulator ios-arm64_armv7_armv7s' for the current build architectures (arm64 x86_64).
    warning: [CP] Unable to find matching .xcframework slice in '/Users/apple/FlutterProjects/myapp/ios/Pods/../.symlinks/plugins/kraken/ios/quickjs.xcframework quickjs framework
    ios-x86_64-simulator ios-arm64_armv7_armv7s' for the current build architectures (arm64 x86_64).
    lib/main.dart:13:9: Error: No named parameter with the name 'bundleURL'.
            bundleURL:
            ^^^^^^^^^
    ../../flutter/.pub-cache/hosted/pub.flutter-io.cn/kraken-0.10.0/lib/src/widget/kraken.dart:198:3: Context: Found this candidate, but the arguments don't match.
      Kraken({
      ^^^^^^
    Failed to package /Users/apple/FlutterProjects/myapp.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'Reachability'
    from project 'Pods')
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner
    editor. (in target 'Runner' from project 'Runner')

**Comment by answershuto** [comment]
最新版本的 API 已经有发生变化了，官网这没有同步，我修改一下。

bundle: KrakenBundle.fromUrl('xxxxxxxx')
