### ISSUE TITLE
编译失败：集成kraken后，在xcode中运行ios成功，但在终端中执行flutter run 失败

### ISSUE THREAD

**Issue by gplcn** [openkraken/kraken#1145]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.10.0 

### 重现步骤 ｜ Steps To Reproduce
flutter版本2.5.2 stable，创建一个新flutter项目，在终端中执行flutter run能正常运行到ios模拟器中；
按文档集成kraken 后在终端中执行`flutter run`无法正常运行到ios模拟器中，但xcode可以正常运行 ios目录工程，并且执行`flutter run`也够正常运行到Andoid 上；

**重现代码 | Code example:**
**pubspec.yaml:**
```
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kraken: '0.10.0' 

  cupertino_icons: ^1.0.2
  kraken_websocket: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  
  uses-material-design: true

  assets:
     - images/cat.jpeg
     - kraken/guide.js
    
```

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:** 
**终端Log:**
```
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Running Xcode build...                                          
Xcode build done.                                            6.9s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
   ~~~
    ** BUILD FAILED **


Xcode's output:
↳
    warning: [CP] Unable to find matching .xcframework slice in '/Users/HEcom/saas/ios/Pods/../.symlinks/plugins/kraken/ios/kraken_bridge.xcframework kraken_bridge framework ios-x86_64-simulator ios-arm64_armv7_armv7s' for the current build architectures (arm64 x86_64).
    warning: [CP] Unable to find matching .xcframework slice in '/Users/HEcom/saas/ios/Pods/../.symlinks/plugins/kraken/ios/quickjs.xcframework quickjs framework ios-x86_64-simulator ios-arm64_armv7_armv7s' for the current build architectures (arm64 x86_64).
    ld: warning: directory not found for option '-F/Users/HEcom/saas/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/kraken_bridge'
    ld: warning: directory not found for option '-F/Users/HEcom/saas/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/quickjs'
    ld: framework not found kraken_bridge
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/HEcom/saas/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'Reachability' from project 'Pods')
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro.
 
```

**Comment by dancancer** [comment]
同样的问题

**Comment by wssgcg1213** [comment]
flutter 2.5.3 + xcode 13.2.1 我这边试了下是正常的, 升级一下版本试试呢? @dancancer @gplcn

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/152734099-85ae4e30-7846-4d87-9566-4d7876e350b6.png)

**Comment by gplcn** [comment]
> ![image](https://user-images.githubusercontent.com/3922719/152734099-85ae4e30-7846-4d87-9566-4d7876e350b6.png)

Xcode版本是 13.2.1 (13C100) , MacOs版本12.2 (21D49), flutter版本最初用的是2.5.3 出现上述问题后降到2.5.2的，但还是不行。 @wssgcg1213

**Comment by wssgcg1213** [comment]
是 M1 的机器吗?

**Comment by wssgcg1213** [comment]
试下这个步骤是否工作:https://stackoverflow.com/questions/67719774/cannot-run-flutter-app-in-ios-simulator-warning-cp-unable-to-find-matching

**Comment by gplcn** [comment]
@wssgcg1213 这个方法前两天试过了不起作用，刚才还是又试了一遍也不行。你看下目录结构看看有没有问题。
![截屏2022-02-07 下午2 57 57](https://user-images.githubusercontent.com/17821282/152740278-3337011a-179a-47ca-9bd3-6ad1872dc565.png)

**Comment by gplcn** [comment]
> 是 M1 的机器吗?

不是M1,  古董级MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by wssgcg1213** [comment]
@gplcn 我这边看着没有问题, 这个报错应该是 cocoapod 报出来的, 意思是说 xcframework 找不到对应的 arch, 对模拟器来说 ios-x86_64-simulator 理论上是 match 的, 我这边用 kraken 项目下的 example 工程暂时没复现, 我再研究一下看看, 或者你也可以对比一下你的工程与 example 工程之间的配置有没有差异(architecure 相关的配置)

**Comment by gplcn** [comment]
> @gplcn 我这边看着没有问题, 意思是说 xcframework 找不到对应的 arch, 对模拟器来说 ios-x86_64-simulator 理论上是 match 的, 我这边用 kraken 项目下的 example 工程暂时没复现, 我再研究一下看看, 或者你也可以对比一下你的工程与 example 工程之间的配置有没有差异(architecure 相关的配置)

可能是`ios/Pods/Target Support Files/kraken/kraken-xcframeworks.sh`这个脚本有问题   调试发现`select_slice` 方法中没有能匹配成功的

**Comment by gplcn** [comment]
@wssgcg1213 产生的脚本中`ios/Pods/Target Support Files/kraken/kraken-xcframeworks.sh#select_slice()`函数有问题，我本地修复以后就正常了，下面是改之后的代码
```
select_slice() {
  local paths=("$@")
  # Locate the correct slice of the .xcframework for the current architectures
  local target_path=""

  # Split archs on space so we can find a slice that has all the needed archs
  local target_archs=$(echo $ARCHS | tr " " "\n")

  local target_variant=""
  if [[ "$PLATFORM_NAME" == *"simulator" ]]; then
    target_variant="simulator"
  fi
  if [[ ! -z ${EFFECTIVE_PLATFORM_NAME+x} && "$EFFECTIVE_PLATFORM_NAME" == *"maccatalyst" ]]; then
    target_variant="maccatalyst"
  fi
  for i in ${!paths[@]}; do
    local matched_all_archs="1"
    for target_arch in $target_archs
    do
      matched_all_archs="1"
      if ! [[ "${paths[$i]}" == *"$target_variant"* ]]; then
        matched_all_archs="0"
        continue
      fi

      # Verifies that the path contains the variant string (simulator or maccatalyst) if the variant is set.
      if [[ -z "$target_variant" && ("${paths[$i]}" == *"simulator"* || "${paths[$i]}" == *"maccatalyst"*) ]]; then
        matched_all_archs="0"
        continue
      fi

      # This regex matches all possible variants of the arch in the folder name:
      # Let's say the folder name is: ios-armv7_armv7s_arm64_arm64e/CoconutLib.framework
      # We match the following: -armv7_, _armv7s_, _arm64_ and _arm64e/.
      # If we have a specific variant: ios-i386_x86_64-simulator/CoconutLib.framework
      # We match the following: -i386_ and _x86_64-
      # When the .xcframework wraps a static library, the folder name does not include
      # any .framework. In that case, the folder name can be: ios-arm64_armv7
      # We also match _armv7$ to handle that case.
      local target_arch_regex="[_\-]${target_arch}([\/_\-]|$)"
      if ! [[ "${paths[$i]}" =~ $target_arch_regex ]]; then
        matched_all_archs="0"
        continue
      fi
      break
    done

    if [[ "$matched_all_archs" == "1" ]]; then
      # Found a matching slice
      echo "Selected xcframework slice ${paths[$i]}"
      SELECT_SLICE_RETVAL=${paths[$i]}
      break
    fi
  done
}
```

**Comment by wssgcg1213** [comment]
这个文件应该是 pods 自动生成的, 这样修改的话后续被 pod 脚本覆盖之后还是会失效, 感觉还是不太稳妥

**Comment by wssgcg1213** [comment]
找了一下来源在这里 https://github.com/cocoapods/cocoapods/blob/master/lib/cocoapods/generator/copy_xcframework_script.rb#L79

**Comment by gplcn** [comment]
> 这个文件应该是 pods 自动生成的, 这样修改的话后续被 pod 脚本覆盖之后还是会失效, 感觉还是不太稳妥

是的每次clean后要重新改下才行，或者该下ARCHS 这个数组元素顺序，M1的把ARM放在前, Intel的 X86放在前，能第一个匹配到就能避免

**Comment by dancancer** [comment]
> @wssgcg1213 产生的脚本中`ios/Pods/Target Support Files/kraken/kraken-xcframeworks.sh#select_slice()`函数有问题，我本地修复以后就正常了，下面是改之后的代码
> 
> ```
> select_slice() {
>   local paths=("$@")
>   # Locate the correct slice of the .xcframework for the current architectures
>   local target_path=""
> 
>   # Split archs on space so we can find a slice that has all the needed archs
>   local target_archs=$(echo $ARCHS | tr " " "\n")
> 
>   local target_variant=""
>   if [[ "$PLATFORM_NAME" == *"simulator" ]]; then
>     target_variant="simulator"
>   fi
>   if [[ ! -z ${EFFECTIVE_PLATFORM_NAME+x} && "$EFFECTIVE_PLATFORM_NAME" == *"maccatalyst" ]]; then
>     target_variant="maccatalyst"
>   fi
>   for i in ${!paths[@]}; do
>     local matched_all_archs="1"
>     for target_arch in $target_archs
>     do
>       matched_all_archs="1"
>       if ! [[ "${paths[$i]}" == *"$target_variant"* ]]; then
>         matched_all_archs="0"
>         continue
>       fi
> 
>       # Verifies that the path contains the variant string (simulator or maccatalyst) if the variant is set.
>       if [[ -z "$target_variant" && ("${paths[$i]}" == *"simulator"* || "${paths[$i]}" == *"maccatalyst"*) ]]; then
>         matched_all_archs="0"
>         continue
>       fi
> 
>       # This regex matches all possible variants of the arch in the folder name:
>       # Let's say the folder name is: ios-armv7_armv7s_arm64_arm64e/CoconutLib.framework
>       # We match the following: -armv7_, _armv7s_, _arm64_ and _arm64e/.
>       # If we have a specific variant: ios-i386_x86_64-simulator/CoconutLib.framework
>       # We match the following: -i386_ and _x86_64-
>       # When the .xcframework wraps a static library, the folder name does not include
>       # any .framework. In that case, the folder name can be: ios-arm64_armv7
>       # We also match _armv7$ to handle that case.
>       local target_arch_regex="[_\-]${target_arch}([\/_\-]|$)"
>       if ! [[ "${paths[$i]}" =~ $target_arch_regex ]]; then
>         matched_all_archs="0"
>         continue
>       fi
>       break
>     done
> 
>     if [[ "$matched_all_archs" == "1" ]]; then
>       # Found a matching slice
>       echo "Selected xcframework slice ${paths[$i]}"
>       SELECT_SLICE_RETVAL=${paths[$i]}
>       break
>     fi
>   done
> }
> ```

的确是这个问题，修改之后解决了，👍

**Comment by wssgcg1213** [comment]
👍

**Comment by JDongKhan** [comment]
我也遇到了，flutter sdk：2.5.3   kraken: ^0.10.2+1 
新建的module，不集成kraken iOS模拟器正常跑，集成了kraken模拟器就报这个错误

**Comment by JDongKhan** [comment]
我新建了个flutter_plugin，让demo依赖，里面放了FMDB.xcframework正常，放了kraken_bridge.xcframework和quickjs.xcframework虽然没编过，但是也能找的到kraken_bridge.xcframework。

**Comment by csjiabin** [comment]
> 是 M1 的机器吗?

M1机器怎么处理。我一直报错
Flutter 2.8.1 
kraken: ^0.11.0
kraken_websocket: ^2.0.0
