### ISSUE TITLE
HTML 文件中 class 无法赋值

### ISSUE THREAD

**Issue by wssgcg1213** [openkraken/kraken#1154]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/3922719/153181606-b670af18-7878-4848-887c-a4dd175c3222.png">  

<img width="358" alt="image" src="https://user-images.githubusercontent.com/3922719/153181669-575b5b33-72a2-4b8e-b0ed-6bb8afee7592.png">  

<img width="231" alt="image" src="https://user-images.githubusercontent.com/3922719/153181685-8b5053c3-1b1a-4b91-966d-52fc90e3e1a2.png">

**Comment by yuchonghua** [comment]
+1
