### ISSUE TITLE
input标签嵌入flutter 聚焦输入时焦点偏移

### ISSUE THREAD

**Issue by AlienegraGeek** [openkraken/kraken#1160]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

kraken: 0.10.1
flutter: 2.5.3
dart:2.14.4

### 重现步骤 ｜ Steps To Reproduce

input标签嵌入flutter聚焦输入时焦点偏移（自动下移），如下：

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 
在浏览器可以正常输入，android及ios真机测试报错
浏览器：Chrome
测试机：Android Xiaomi 11 & IPhone 13 pro max

**实际结果 ｜ Actual results:** 

![image](https://user-images.githubusercontent.com/33959579/153575644-2a60e556-c081-463d-892f-c922b23a5017.png)

**Comment by AlienegraGeek** [comment]
可以尽快修复吗？急...

**Comment by fadeAce** [comment]
我也遇到这个问题 还没有解决吗

**Comment by temper357** [comment]
我这边自测 input 输入时焦点并不会偏移，看 issue 截图也没有体现焦点是如何偏移的，前端代码能否贴一下？

**Comment by AlienegraGeek** [comment]
> 我这边自测 input 输入时焦点并不会偏移，看 issue 截图也没有体现焦点是如何偏移的，前端代码能否贴一下？

前端demo代码:
https://github.com/EntySquare/miniapp-nikestore-demo/blob/main/src/views/my.vue

**Comment by fadeAce** [comment]
@temper357 估计是键盘高度或者一些因素导致的，准确来说 应该是下降了键盘的高度，整个页面

**Comment by temper357** [comment]
使用提供的 demo 代码在两台 android 机（一台小米 6，一台 OPPO Find X3 Pro）上测试均没有复现问题，Kraken 为最新的主干代码，可以升级到 Kraken 最新版本 0.10.1 再确认下

**Comment by wssgcg1213** [comment]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/3922719/159407260-ba02f308-3a6f-4c32-881c-5694f82fae29.png">
<img width="485" alt="image" src="https://user-images.githubusercontent.com/3922719/159407724-e74ce393-10e9-4538-82c8-bbeadbbb0fad.png">

看起来都挺正常 emmm, 有没有复现方式 @fadeAce

**Comment by wssgcg1213** [comment]
不过我这边已经是新版本了, 建议升级一下试试有没有解决, 如果还有问题可以 reopen ~
