### ISSUE TITLE
支持 textarea element

### ISSUE THREAD

**Issue by temper357** [openkraken/kraken#1162]
## 使用场景 ｜ Use case

支持 textarea element，以满足多行文本编辑的业务需求。

**Comment by yuchonghua** [comment]
近期能支持吗？感觉这个功能比较急用，目前资金封装自定义组件，好像有很多问题，目前可以触发事件，但是如何传回事件的指呢

**Comment by yuchonghua** [comment]
> 近期计划支持，使用 Flutter Widget 封装自定义组件可以参考这篇接入文档 https://openkraken.com/guide/advanced/widget-custom-element, widget 可以通过 dispatchEvent 将自定义事件抛给前端监听。

这个例子我看到的，现在的主要问题是我在阅读文档的没有领悟到如何在dispatchEvent中传参

**Comment by answershuto** [comment]
可以用 CustomEvent

**Comment by yuchonghua** [comment]
好的，另外，我发现嵌套子组件目前有问题，这个可以解决吗

**Comment by temper357** [comment]
具体是什么问题

**Comment by yuchonghua** [comment]
如 这个所描述的问题啊，https://github.com/openkraken/kraken/issues/1175
