### ISSUE TITLE
急急急，发现flutter 集成 kraken 后无法正常发送大图片，不引入kraken 不会

### ISSUE THREAD

**Issue by yuchonghua** [openkraken/kraken#1171]
### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 

_picker.pickImage(source: ImageSource.gallery)
              .then((XFile? file) async {
            print('file');
            print(file!.path);

            var uri = 'http://10.111.80.89:18008/'+file!.name;
            HttpClient httpClient = HttpClient();

            var request = await httpClient.openUrl('PUT', Uri.parse(uri));
            request.headers.set(HttpHeaders.contentLengthHeader, await file.length());
            await request.addStream(file.openRead());
            // await request.flush();
            //3.关闭请求，等待响应
            var response = await request.close();
            var responseBody = '';
            //4.进行解码，获取数据
            try {
              responseBody = await response.transform(utf8.decoder).join();
            } catch (ee) {
              responseBody = '';
            }
            print('bg-00-5');
            // pp.readAsBytes
            print('responseBody');
            print(responseBody);
            // print(uri);
            return {
              'url': 'responseBody'
            };
          });

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:** 
![image](https://user-images.githubusercontent.com/17898715/155083280-cec18057-392e-44f7-a605-4cb2b9a863e5.png)

出现了D/SurfaceView( 6466): UPDATE Surface(name=SurfaceView - com.guanmengzs.chat_app/com.guanmengzs.chat_app.MainActivity)/@0x5c84c75, mIsProjectionMode = false
E/flutter ( 6466): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: RangeError: Value not in range: -171360
E/flutter ( 6466): #0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1092:20)
E/flutter ( 6466): #1      _RawSocket.write (dart:io-patch/socket_patch.dart:1765:15)
E/flutter ( 6466): #2      _Socket._write (dart:io-patch/socket_patch.dart:2198:18)
E/flutter ( 6466): #3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:1946:26)
E/flutter ( 6466): #4      _Socket._onData (dart:io-patch/socket_patch.dart:2169:19)
E/flutter ( 6466): #5      _rootRunUnary (dart:async/zone.dart:1444:13)
E/flutter ( 6466): #6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 6466): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 6466): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 6466): #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 6466): #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter ( 6466): #11     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter ( 6466): #12     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter ( 6466): #13     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1707:23)
E/flutter ( 6466): #14     _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1239:14)
E/flutter ( 6466): #15     _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1246:7)
E/flutter ( 6466): #16     _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1267:11)
E/flutter ( 6466): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 6466):

**Comment by wssgcg1213** [comment]
可以先把缓存关掉, HttpCacheController.mode = HttpCacheMode.NO_CACHE;  

这个问题我来看一下

**Comment by yuchonghua** [comment]
非常感谢您的回答

**Comment by yuchonghua** [comment]
![image](https://user-images.githubusercontent.com/17898715/155091380-8f34d2cf-556d-4a98-9f2c-1c19945c6443.png)
![image](https://user-images.githubusercontent.com/17898715/155091406-8eecec0a-e927-42b2-941f-60fe2cc51d41.png)
问题依旧不行，项目急上线，有解决冲突的方法吗
/ping @wssgcg1213

**Comment by wssgcg1213** [comment]
能确定是引入 Kraken 之后才有的异常吗

**Comment by yuchonghua** [comment]
非常确定，是使用了Kraken就不行，在有 Kraken 组件的页面弹出了任何页面，包括 Kraken 都无法正常使用HttpClient传输完所有流

**Comment by yuchonghua** [comment]
您方便加个微信吗？ 283114511

![image](https://user-images.githubusercontent.com/17898715/155098744-d0e18282-fc6b-427a-bf03-189440a9ab53.png)

**Comment by yuchonghua** [comment]
您那边可以用 image_picker 上传大文件吗？我使用了Kraken 渲染就不行，急等解决冲突，这个冲突太致命了...

**Comment by wssgcg1213** [comment]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/3922719/155272434-7d825f7c-8460-44be-97e1-bcddf1de19fb.png">

最近建了一个社区群 可以在这里找到我们
