### ISSUE TITLE
native crash

### ISSUE THREAD

**Issue by colorfulldays** [openkraken/kraken#1173]
natvie crash

version 0.10.1

    ( 4166): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xcb1 in tid 4717 (2.ui), pid 4166 (.kraken_example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HONOR/ALA-AN70/HNALA7:10/HONORALA-AN70/11.0.2.171C00:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-02-23 14:54:16+0800
pid: 4166, tid: 4717, name: 2.ui  >>> com.openkraken.kraken_example <<<
uid: 10221
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xcb1
Cause: null pointer dereference
    x0  0000007b0a78b780  x1  0000007b03dd476e  x2  0000000000000000  x3  6e6f43534a00656d
    x4  0000000000000000  x5  0000000000800000  x6  6d6e425248ff646c  x7  7f7f7f7f7f7f7f7f
    x8  0000007b984cd840  x9  0000000000000001  x10 0000007b98582a00  x11 000000000000002d
    x12 0000007b09eab000  x13 000000000000004a  x14 0000000000002000  x15 0000000000000000
    x16 0000007b03de7ee0  x17 0000007b03d388b8  x18 0000007b30bde000  x19 0000000000000cb1
    x20 0000007b03dd476e  x21 0000007b98417dc0  x22 0000000000000000  x23 0000000000000000
    x24 0000007b998f3020  x25 0000007b03dd476e  x26 0000000000000000  x27 0000007b998f3020
    x28 0000000400000000  x29 0000007b998e29a0
    sp  0000007b998e2930  lr  0000007b03d38708  pc  0000007b03d38d2c
backtrace:
      #00 pc 000000000001ad2c  /data/app/com.openkraken.kraken_example-QdDJiekPbnt8crE-oRaghQ==/lib/arm64/libquickjs.so (JS_NewStringLen+1140) (BuildId: 4c66eb35d58c10caf6a94230b029d9e4083f37a6)
      #01 pc 000000000001a704  /data/app/com.openkraken.kraken_example-QdDJiekPbnt8crE-oRaghQ==/lib/arm64/libquickjs.so (JS_NewAtomLen+264) (BuildId: 4c66eb35d58c10caf6a94230b029d9e4083f37a6)
      #02 pc 000000000001ca74  /data/app/com.openkraken.kraken_example-QdDJiekPbnt8crE-oRaghQ==/lib/arm64/libquickjs.so (BuildId: 4c66eb35d58c10caf6a94230b029d9e4083f37a6)
      #03 pc 0000000000017ce8  /data/app/com.openkraken.kraken_example-QdDJiekPbnt8crE-oRaghQ==/lib/arm64/libquickjs.so (JS_NewContextRaw+544) (BuildId: 4c66eb35d58c10caf6a94230b029d9e4083f37a6)
      #04 pc 0000000000017ee4  /data/app/com.openkraken.kraken_example-QdDJiekPbnt8crE-oRaghQ==/lib/arm64/libquickjs.so (JS_NewContext+12) (BuildId: 4c66eb35d58c10caf6a94230b029d9e4083f37a6)
      #05 pc 00000000000448ac  /data/app/com.openkraken.kraken_example-QdDJiekPbnt8crE-oRaghQ==/lib/arm64/libkraken.so (kraken::binding::qjs::ExecutionContext::ExecutionContext(int, std::__ndk1::function<void (int, char const*)> const&, void*)+436) (BuildId: 2d158b51e543957d483c38e22a4d873c00263de9)
      #06 pc 0000000000043198  /data/app/com.openkraken.kraken_example-QdDJiekPbnt8crE-oRaghQ==/lib/arm64/libkraken.so (kraken::KrakenPage::KrakenPage(int, std::__ndk1::function<void (int, char const*)> const&)+60) (BuildId: 2d158b51e543957d483c38e22a4d873c00263de9)
      #07 pc 000000000003da28  /data/app/com.openkraken.kraken_example-QdDJiekPbnt8crE-oRaghQ==/lib/arm64/libkraken.so (initJSPagePool+320) (BuildId: 2d158b51e543957d483c38e22a4d873c00263de9)
      #08 pc 0000000000006b04  <anonymous:7b22980000>
Lost connection to device.

**Comment by andycall** [comment]
duplicated with #1172 https://github.com/openkraken/kraken/issues/1163

**Comment by colorfulldays** [comment]
已经更新到最新代码，问题依然有。

**Comment by andycall** [comment]
https://github.com/openkraken/kraken/issues/1163 刚合入，再试一下
