### ISSUE TITLE
input无法通过样式修改输入框高度

### ISSUE THREAD

**Issue by yuchonghua** [openkraken/kraken#1177]
### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by temper357** [comment]
我这边测试没有问题，请提供有问题的前端代码

**Comment by yuchonghua** [comment]
稍等一天，发搞一个简单  的rax demo

**Comment by yuanyan** [comment]
有更多信息再重新打开 issue
