### ISSUE TITLE
kraken 非常期待能 成为一个优秀的 flutter组件

### ISSUE THREAD

**Issue by yuchonghua** [openkraken/kraken#1181]
kraken 在很大层面上解决了大部分的布局问题，降低了样式布局开发门槛，
期待能有之前weex的设计模式，那个模式感觉挺好用的，
很多公用的js-api和js-lib 希望能不要重复加载占用内存，

**Comment by yuanyan** [comment]
1. weex 里是早期隔离技术的不成熟的无奈之举，并不是有意为之。后期也是独立。
2. 公共js复用相同实例降低内存占用与提升初始化时间这个未来会有方案来支持

**Comment by yuchonghua** [comment]
在最近的实践中，发现了一个问题，
1、如果是用flutter书写的页面，我发现在push路由打开页面的时候，动画是可以明显看到渲染好的页面，给用户的体验感觉是非常的美好的
2、然而，通过隔离的js环境来渲染页面，在某种程度上，确实是解决了很多的js层面的变量污染问题
但是，这种方式，会导致页面在push过来的动画，显示内容一片空白，然后再慢慢的像网页的来加载

给人一个明显的感觉，就是这个app不像app，像一个网页，而且，会非常卡顿的动画切换效果，如果加入动画控制，似乎，空白的时间更长了，方便请教一下您们有什么解决方案吗？

/ping @yuanyan @wssgcg1213
