### ISSUE TITLE
首屏无法显示，容易白屏和样式错乱，然后需要切换，反复重新打开才行

### ISSUE THREAD

**Issue by yuchonghua** [openkraken/kraken#1183]
### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by yuchonghua** [comment]
就是一个非常普通的 rax kraken 官方版本的 项目 在安卓 打包，在很多机型会出现这种情况

**Comment by yuanyan** [comment]
具体是哪个demo，需要提供下更多信息

**Comment by yuanyan** [comment]
有更多信息再重新打开issue
