### ISSUE TITLE
以SDK形式接入Kraken后，如何测试应用性能以及为JS提供本地能力

### ISSUE THREAD

**Issue by hanzhicuilin** [openkraken/kraken#1184]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

Kraken SDK 0.9.0

### 重现步骤 ｜ Steps To Reproduce

已按照官网介绍在安卓应用中成功集成Kraken SDK 0.9.0。
目前存在两个问题：
1. 是否存在API等可以测量应用性能，比如首屏打开速度。
2. 是否能够通过Java代码为JS层提供插件能力。

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by andycall** [comment]
SDK 的集成方式未来将不再支持，可以使用 Flutter 的集成方式来获得更多的定制化能力
