### ISSUE TITLE
bundlePath读取本地资源，为什么要用assets:// 开头来判断

### ISSUE THREAD

**Issue by simonyxu** [openkraken/kraken#1188]
RT

**Comment by answershuto** [comment]
现在只有 `KrakenBundle.fromUrl` 来获取资源了，统一通过协议来判断是否读取本地资源，bundlePath 以及 loadPath 将会弃用。

**Comment by yuanyan** [comment]
`assets:// `  是对应在flutter app里assets配置的目录

**Comment by simonyxu** [comment]
> 

大佬有Demo看一下吗 好像并不行

**Comment by simonyxu** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/39670283/156345156-4c77b15c-357b-4705-b28d-d14408352fb9.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/39670283/156345188-76d922b5-f93c-4392-8123-2faa240c1618.png">
<img width="456" alt="image" src="https://user-images.githubusercontent.com/39670283/156345211-7a7bfe95-aec0-486d-875b-e6660e2d0912.png">
fromUrl读取本地路径是要路径以assets://开头吗？ 请问怎么添加assets://开头呢，用了UriParser也不可以

**Comment by answershuto** [comment]
KrakenBundle.fromUrl('assets://xxxPath/xxx.js');

**Comment by answershuto** [comment]
以及配置相应的 assets 目录配置，并将文件放入配置的路径中。

**Comment by answershuto** [comment]
以及配置相应的 assets 目录配置，并将文件放入配置的路径中。

**Comment by simonyxu** [comment]
已解决 感谢
