### ISSUE TITLE
http 缓存未生效

### ISSUE THREAD

**Issue by simonyxu** [openkraken/kraken#1189]
对请求资源设置了缓存，但是用同一个地址访问不同内容的资源，发现第二次并没有访问缓存资源

**Comment by answershuto** [comment]
提供一下 demo 以及使用方法

**Comment by simonyxu** [comment]
`  Kraken kraken = Kraken(
    bundle: KrakenBundle.fromUrl(
        "https://xxxx/bundle.js"),
    javaScriptChannel: KrakenNativeChannel(),
  );

  return Container(
      width: size.width,
      height: state.helper.height > 0 ? state.helper.height : size.height,
      decoration: const BoxDecoration(
        color: Color(0xff272541),
      ),
      child: SafeArea(
          top: !state.helper.isCard,
          bottom: false,
          child: Column(
            children: [
              kraken,
            ],
          )`
![111646136350_ pic](https://user-images.githubusercontent.com/39670283/156189018-73cc049d-02f1-4be6-b6bc-8c4c83ea2db7.jpg)

**Comment by wssgcg1213** [comment]
已定位问题, 是编码问题导致的, 稍后提交修复
