### ISSUE TITLE
加入dynamic import支持

### ISSUE THREAD

**Issue by huoxiangdong** [openkraken/kraken#119]
如果打包单文件过大的话，js加载、首次上屏都是负担，
加入`import`支持，可以按需加载，无论是对于性能、还有体验上，
会有很大提升

**Comment by yuanyan** [comment]
import 确定会支持

**Comment by wssgcg1213** [comment]
Definition https://tc39.es/ecma262/#sec-import-calls

**Comment by yuanyan** [comment]
考虑大部分情况大家都是通过 https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import 来使用 dynamic import，优先支持能让 babel 的编译后产物能正常工位
