### ISSUE TITLE
Failed to decode image,flutter 的图片无法正常使用，新版kraken

### ISSUE THREAD

**Issue by yuchonghua** [openkraken/kraken#1196]
### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:** 

![image](https://user-images.githubusercontent.com/17898715/157001806-c5a81309-8ef0-4a82-b91b-3de48b80fc7e.png)

**Comment by andycall** [comment]
新版 kraken 是那个版本？确认图片没有问题吗？

**Comment by yuchonghua** [comment]
最新的版本，本来是正常的 
![image](https://user-images.githubusercontent.com/17898715/157003439-bef3d748-4630-4850-befc-51731e55c4fe.png)

**Comment by andycall** [comment]
上个可用的版本是什么？

**Comment by yuchonghua** [comment]
0.10.1*

**Comment by yuchonghua** [comment]
https://github.com/openkraken/kraken/issues/1175 这个问题方便处理吗
/ping @andycall

**Comment by wssgcg1213** [comment]
请提供可以复现的问题最小复现代码方便我们研究此问题, 仅从错误日志看不出是何处导致的

**Comment by yuchonghua** [comment]
这问题，我临时关闭，然后我会在下周左右提供demo后重新打开
