### ISSUE TITLE
js中调用Axios执行网络请求失败

### ISSUE THREAD

**Issue by WK726** [openkraken/kraken#1199]
最新的main代码，并且用的release进行build

### 重现步骤 ｜ Steps To Reproduce

调用时报错
Error {config: {...}, isAxiosError: true, message: 'Network Error', request: {...}, response: undefined, stack: '    at createError ([assets://assets/app.js:1939]())
    at handleError ([assets://assets/app.js:17591]())
    at dispatchEvent (native)
    at handleError (vm://polyfill.js)
    at r (vm://polyfill.js)
    at <anonymous> (vm://polyfill.js)
', toJSON: ƒ ()}
load end

**重现代码 | Code example:** 

js中的axios代码如下：

function Axios(instanceConfig) {
  this.defaults = instanceConfig;
  this.interceptors = {
    request: new InterceptorManager(),
    response: new InterceptorManager()
  };
}

/**
 * Dispatch a request
 *
 * @param {Object} config The config specific for this request (merged with this.defaults)
 */
Axios.prototype.request = function request(configOrUrl, config) {
  /*eslint no-param-reassign:0*/
  // Allow for axios('example/url'[, config]) a la fetch API
  if (typeof configOrUrl === 'string') {
    config = config || {};
    config.url = configOrUrl;
  } else {
    config = configOrUrl || {};
  }

  config = mergeConfig(this.defaults, config);

  // Set config.method
  if (config.method) {
    config.method = config.method.toLowerCase();
  } else if (this.defaults.method) {
    config.method = this.defaults.method.toLowerCase();
  } else {
    config.method = 'get';
  }

  var transitional = config.transitional;

  if (transitional !== undefined) {
    validator.assertOptions(transitional, {
      silentJSONParsing: validators.transitional(validators.boolean),
      forcedJSONParsing: validators.transitional(validators.boolean),
      clarifyTimeoutError: validators.transitional(validators.boolean)
    }, false);
  }

  // filter out skipped interceptors
  var requestInterceptorChain = [];
  var synchronousRequestInterceptors = true;
  this.interceptors.request.forEach(function unshiftRequestInterceptors(interceptor) {
    if (typeof interceptor.runWhen === 'function' && interceptor.runWhen(config) === false) {
      return;
    }

    synchronousRequestInterceptors = synchronousRequestInterceptors && interceptor.synchronous;

    requestInterceptorChain.unshift(interceptor.fulfilled, interceptor.rejected);
  });

  var responseInterceptorChain = [];
  this.interceptors.response.forEach(function pushResponseInterceptors(interceptor) {
    responseInterceptorChain.push(interceptor.fulfilled, interceptor.rejected);
  });

  var promise;

  if (!synchronousRequestInterceptors) {
    var chain = [dispatchRequest, undefined];

    Array.prototype.unshift.apply(chain, requestInterceptorChain);
    chain = chain.concat(responseInterceptorChain);

    promise = Promise.resolve(config);
    while (chain.length) {
      promise = promise.then(chain.shift(), chain.shift());
    }

    return promise;
  }

  var newConfig = config;
  while (requestInterceptorChain.length) {
    var onFulfilled = requestInterceptorChain.shift();
    var onRejected = requestInterceptorChain.shift();
    try {
      newConfig = onFulfilled(newConfig);
    } catch (error) {
      onRejected(error);
      break;
    }
  }

  try {
    promise = dispatchRequest(newConfig);
  } catch (error) {
    return Promise.reject(error);
  }

  while (responseInterceptorChain.length) {
    promise = promise.then(responseInterceptorChain.shift(), responseInterceptorChain.shift());
  }

  return promise;
};

Axios.prototype.getUri = function getUri(config) {
  config = mergeConfig(this.defaults, config);
  return buildURL(config.url, config.params, config.paramsSerializer).replace(/^\?/, '');
};

**Comment by wssgcg1213** [comment]
能否提供更多信息, 暂时还无法判断问题

**Comment by WK726** [comment]
> 能否提供更多信息, 暂时还无法判断问题

用demo中提供的js可以，该js是我自己写的，需要提供js完整代码吗？

**Comment by WK726** [comment]
之前的报错是js里的代码执行axios时写的报错信息，现在改成fetch之后发现又报krakenPlugin里的getTemporaryDirectory没找到

InternalError: MissingPluginException(No implementation found for method getTemporaryDirectory on channel kraken)

在appdelegate里已经注册了    [KrakenPlugin registerWithRegistrar:[self registrarForPlugin:@"KrakenPlugin"]];
plugin里也包含getTemporaryDirectory这个方法

很奇怪会报错误

**Comment by wssgcg1213** [comment]
buildURL 方法在哪? InterceptorManager 是啥? 只有上面的js看起来无法运行呀

**Comment by WK726** [comment]
工程配置kraken：
demo调研阶段，现在是通过native里手动倒入的plugin相关的代码以及bridge和quickjs

buildURL：
![企业微信截图_514591bb-18ae-417e-bf25-5e63f47a659c](https://user-images.githubusercontent.com/17629919/157210750-0502b38d-4a68-49df-b008-cd53b490ea32.png)

目前的plugin配置注册部分代码：
<img width="1013" alt="企业微信截图_7027bc1f-cf31-4afc-88c3-5ef29e6e6a89" src="https://user-images.githubusercontent.com/17629919/157210947-3ecb8197-0461-400e-9828-b0e1cce1fcc7.png">

下边是用到的js代码
[app1.js.zip](https://github.com/openkraken/kraken/files/8204721/app1.js.zip)

InterceptorManager：
现在还是在demo调研阶段，所以暂时没用到

目前的问题：
项目运行完之后没有报js的错误，报了一个
InternalError: MissingPluginException(No implementation found for method getTemporaryDirectory on channel kraken)
这个错误，查看代码plugin里也是有这个方法的

**Comment by WK726** [comment]
补充：
在js中的mounted里调用loadData方法记载网络数据：

![截屏2022-03-09 下午12 01 26](https://user-images.githubusercontent.com/17629919/157370417-bca5d66e-0747-4c95-95bf-90ccc5a9a83a.png)

catch中打印了下边的报错
catch==InternalError: MissingPluginException(No implementation found for method getTemporaryDirectory on channel kraken)
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:154
<asynchronous suspension>
#1      getKrakenTemporaryPath (pac
5
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**Comment by wssgcg1213** [comment]
这个报错的意思是 kraken 插件没有正常初始化, 这个插件提供了获取系统临时文件夹路径的功能, 在执行 dart entrypoint 之前需要确保 plugin 已经注册好~

**Comment by wssgcg1213** [comment]
axios.js 我在本地试了它提供的 example, 不管是 get 还是 post, 目前看是正常工作的, 所以我觉得问题还是出在集成的插件上

**Comment by WK726** [comment]
> axios.js 我在本地试了它提供的 example, 不管是 get 还是 post, 目前看是正常工作的, 所以我觉得问题还是出在集成的插件上

确实是plugin初始化有关系，注册plugin和flutterViewController初始化没有用同一个engine，改成一个引擎可以了，非常🙏
