### ISSUE TITLE
标准的rax-kraken无法正常调整输入框的高度，输入框有很多竖杆

### ISSUE THREAD

**Issue by yuchonghua** [openkraken/kraken#1200]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

kraken-0.10.2+1

### 重现步骤 ｜ Steps To Reproduce

最基本的普通的rax编译的kranken存在该问题

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

希望能和普通web 的input一样使用
**实际结果 ｜ Actual results:** 
![IMG_20220308_151356](https://user-images.githubusercontent.com/17898715/157186624-647383e7-a212-4d42-b25e-af91fbc7cd8d.jpg)

**Comment by temper357** [comment]
竖杆是编辑 input 时出来的，你上面的截图是页面加载出来就有这么多竖杆？还是有做过什么操作

**Comment by yuchonghua** [comment]
直接进来就这样了哦

**Comment by yuchonghua** [comment]
只要绑定了初始化数据就会有这个问题

**Comment by wssgcg1213** [comment]
any progress?

**Comment by temper357** [comment]
@yuchonghua demo 提供一下

**Comment by yuchonghua** [comment]
@wssgcg1213 @temper357 就非常普通的官方的默认的rax框架，然后仅仅需要在一个非常原始的标准的rax上，书写几个输入框，然后通过rax的默认值，即可看到多个竖杆

**Comment by temper357** [comment]
使用 rax-textinput 组件可以复现，等 https://github.com/openkraken/kraken/pull/1180 这个 textarea PR 合并后可以解决

**Comment by yuchonghua** [comment]
好的，感谢

**Comment by liweq** [comment]
遇到同样的问题，希望能尽快解决，没办法使用

**Comment by wssgcg1213** [comment]
Relate to https://github.com/openkraken/kraken/pull/1180

**Comment by yuchonghua** [comment]
@wssgcg1213 你好，这个问题开始解决了吗

**Comment by temper357** [comment]
@yuchonghua https://github.com/openkraken/kraken/pull/1180 已经合并过主干了，安装最新的版本就行
