### ISSUE TITLE
构建页面时返回上一级会导致APP crash

### ISSUE THREAD

**Issue by simonyxu** [openkraken/kraken#1201]
操作路径：
在由Kraken构建页面的上一级页面点击进入Kraken页面，页面还未渲染完成时返回上一级，在Android某些机型上会导致APP crash

**Comment by simonyxu** [comment]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/39670283/157196589-ef66caab-a1a3-457e-9428-44323f39b4d3.png">

**Comment by airingursb** [comment]
https://user-images.githubusercontent.com/10513408/157197013-4ca302b6-bc39-4b8f-b489-6fd242dd2abb.mov

附带此 issue 录屏：录屏第 14 秒开始触发到崩溃

**Comment by airingursb** [comment]
Kraken: 0.10.2

**Comment by wssgcg1213** [comment]
@simonyxu 这个找到问题了吗?
