### ISSUE TITLE
预加载FlutterEngine情况 kraken页面无法展示

### ISSUE THREAD

**Issue by colorfulldays** [openkraken/kraken#1222]
在混合模式中 测试发现 预加载FlutterEngine情况 kraken页面无法展示，其他页面正常展示。

不知道这是机制问题，还是需要什么特殊处理。
kraken version  0.10.0

**Comment by wssgcg1213** [comment]
能否提供示例呢, 或者在 `readNativeUICommandToDart` 这个方法上打个断点看有没有执行

**Comment by colorfulldays** [comment]
> 能否提供示例呢, 或者在 `readNativeUICommandToDart` 这个方法上打个断点看有没有执行

这个问题我已经处理了，是因为预加载的时候未能取到屏幕信息的导致的。现在我遇到的新问题的是 https://github.com/openkraken/kraken/issues/1236

**Comment by wssgcg1213** [comment]
OK👌🏻
