### ISSUE TITLE
iOS下多开Kraken情况下，点击前一页元素会有崩溃问题

### ISSUE THREAD

**Issue by hellerchen** [openkraken/kraken#1223]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
Kraken：0.10.2
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (5 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

### 重现步骤 ｜ Steps To Reproduce
iOS下多开Kraken情况下，在后一页kraken页面上下滑动，点击元素后返回前一页，点击会有崩溃问题

下面是堆栈：
![17151647409988_ pic](https://user-images.githubusercontent.com/6426556/158607616-73ac2d6f-b19d-4f6e-8400-e47ab55aada0.png)

**Comment by wssgcg1213** [comment]
看起来是因为触发事件的时候空指针了? @andycall

**Comment by andycall** [comment]
应该和这个有关 https://github.com/openkraken/kraken/pull/1209

**Comment by wssgcg1213** [comment]
@andycall 下午发一个版本, 让 @hellerchen 验证一下

**Comment by hellerchen** [comment]
滑动点击崩溃的问题貌似没有了，但是新开kraken页面会发生偶然崩溃，而且概率还蛮高的
<img width="678" alt="WechatIMG3037" src="https://user-images.githubusercontent.com/6426556/160802994-a9e8acef-891d-4034-8c26-c9f731504762.png">

**Comment by hellerchen** [comment]
@wssgcg1213 @andycall

**Comment by wssgcg1213** [comment]
看起来是 raster thread 挂了, 有没有搜索过类似的问题

**Comment by hellerchen** [comment]
> 看起来是 raster thread 挂了, 有没有搜索过类似的问题

看起来不是kraken问题，我这边调试看看，issue先close了，感谢~
