### ISSUE TITLE
 <script src="xxx"> 标签执行顺序

### ISSUE THREAD

**Issue by devjiangzhou** [openkraken/kraken#1240]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

master

### 重现步骤 ｜ Steps To Reproduce

<img width="988" alt="image" src="https://user-images.githubusercontent.com/1578465/159859033-b9cf33d3-0da1-4a43-884f-afd9bbf0dd97.png">

script 标签执行顺序，现在引入 script 是 dart 层传入的，内置 script 标签是 bridge 层直接处理的，
如果内置 script 标签依赖引用 script，这时无法保证执行顺序

**重现代码 | Code example:** 
我是在测试 epub js example 时发现的

**预期结果 ｜ Expected results:** 
能正确处理 js 对象依赖

**实际结果 ｜ Actual results:** 
标签之间执行时没有顺序的

<img width="937" alt="image" src="https://user-images.githubusercontent.com/1578465/159858846-29030ea3-d631-45e5-b928-cc824f897492.png">

有什么好的解决方案么？

**Comment by wssgcg1213** [comment]
确实, 目前没有一个 queue 来给执行排队, 我们需要设计一下

**Comment by devjiangzhou** [comment]
> 确实, 目前没有一个 queue 来给执行排队, 我们需要设计一下

我晚上仔细看下 kraken 的 css 处理机制，看是不是有同样的问题

**Comment by wssgcg1213** [comment]
还包括 async, defer 的支持

**Comment by wssgcg1213** [comment]
是的
