### ISSUE TITLE
图片宽高解析失败导致图片不显示

### ISSUE THREAD

**Issue by bainian** [openkraken/kraken#1244]
### 使用的 Kraken 版本 
master 0.10.3

### 重现步骤
直接加载运行简单包含image 标签的 jsbundle 就可以重现，代码如下：

```
var aa_div = document.createElement('div');
aa_div.style.height = '35px';
aa_div.style.background = 'yellow'

const img = new Image();
img.src = 'https://gw.alicdn.com/tfs/TB1.A6OslBh1e4jSZFhXXcC9VXa-229-255.png';
img.width = '30px';
img.height = '30px'; // 不加单位就能显示出来
aa_div.appendChild(img);

document.body.appendChild(aa_div);
```

**预期结果 
显示图片

**实际结果 
没显示

## 原因分析

可能是因为element.dart中的属性解析没有处理单位。
```
T attributeToProperty<T>(String value) {
  // The most using type.
  if (T == String) {
    return value as T;
  } else if (T == bool) {
    return true as T;
  } else if (T == int) {
    return (int.tryParse(value) ?? 0) as T; // 这里
  } else if (T == double) {
    return (double.tryParse(value) ?? 0.0) as T; // 这里
  } else {
    return value as T;
  }
```

**Comment by wssgcg1213** [comment]
@bainian 是的哦, 简单的说浏览器也是这样的, 所以不是 BUG~   

原因是 HTMLImageElement 的 width 和 height 属性在 W3C 标准中是 [valid non-negative integers](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-non-negative-integer) 类型, 不是 CSSLength 类型, 所以你的这段代码在浏览器中也是获得 width=0, height=0 的表现  

标准定义: https://html.spec.whatwg.org/multipage/embedded-content-other.html#attr-dim-width

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/3922719/160336726-58d9c955-edfd-4893-bcc6-43ea6c03d253.png">

-----

一般使用上, 还是建议使用样式表来定义图片的样式

**Comment by wssgcg1213** [comment]
另外 image 的这几个 property (IDL attribute) 也是直接 reflect 到 attribute 的, 见 
<img width="986" alt="image" src="https://user-images.githubusercontent.com/3922719/160337562-1e89aa17-c10a-4a32-93c5-6e39f2f25b68.png">
