### ISSUE TITLE
integration_tests 支持单个功能的测试

### ISSUE THREAD

**Issue by devjiangzhou** [openkraken/kraken#1250]
## 使用场景 ｜ Use case

测试单个功能时，需要跑整个单测，太费事了
## 提案 ｜ Proposal
支持单个功能进行单测

**Comment by wssgcg1213** [comment]
describe 改成 fdescribe, 或者 it 改成 fit, 再执行测试就可以了 

jasmine 的功能: https://jasmine.github.io/api/4.0/global
