### ISSUE TITLE
0.10.3以上版本对bundle中有中文会报错

### ISSUE THREAD

**Issue by zelllez** [openkraken/kraken#1262]
### 重现步骤 ｜ Steps To Reproduce

![image](https://user-images.githubusercontent.com/36196697/160768189-f14aa8f6-bef5-4b2a-ad51-1a8ad134ed13.png)

**重现代码 | Code example:** 
见上

**预期结果 ｜ Expected results:** 
预期与0.10.2一致可以打印

**实际结果 ｜ Actual results:** 
报错

**Comment by wssgcg1213** [comment]
我看一下

**Comment by zelllez** [comment]
@wssgcg1213 你好，这个是不是跟bundle.dart修改了有关？

**Comment by zelllez** [comment]
```dart
bundle: KrakenBundle.fromContent('let a = "折";console.log(a);'),
```

**Comment by wssgcg1213** [comment]
是的, fromString 把字符串按照 utf16 编码了, 解析的时候是按照 utf8 解析的, 所以中文部分出错了, 我修复一下

**Comment by wssgcg1213** [comment]
@zelllez 你可以先这样: 

```dart
bundle: DataBundle(
  Uint8List.fromList(utf8.encode(content)),
  DEFAULT_URL,
  contentType: ContentType('text', 'javascript', charset: 'utf-8')
)
```
