### ISSUE TITLE
不支持层叠样式表

### ISSUE THREAD

**Issue by Arkey-zeng** [openkraken/kraken#1307]
### 使用的 Kraken 版本
Version: 0.10.4

### 重现步骤 
使用层叠样式（后代选择器，伪类，复杂选择器...）不生效

### 重现代码
`<style>
.page-container .div{
  background: red;
}
</style>`

`<div class="page-container">
  <div class="div" style="width: 100px; height: 100px;"></div>
</div>`

### 预期结果
子 div 背景颜色改变

### 实际结果
flutter 端不生效

**Comment by wssgcg1213** [comment]
https://openkraken.com/guide/basic/difference-to-web#%E6%A0%B7%E5%BC%8F%E8%83%BD%E5%8A%9B%E5%B7%AE%E5%BC%82  

CSS Parser 暂时只支持 class 选择器, 后代选择器还未支持, 可以关注一下 Feature 进展

**Comment by Arkey-zeng** [comment]
谢谢解答，这样的话前端生态的系列插件和 ui 库都无法使用了，项目发展会受阻
