### ISSUE TITLE
开放element的自定义调用dart侧方法的能力

### ISSUE THREAD

**Issue by 00SunnyDay00** [openkraken/kraken#1321]
## 使用场景 ｜ Use case

在自定义组件场景下， 往往需要自定义很多methods。目前这些方法需要通过C++定义的方式来实现，这是一个比较大的的成本。
是否可以提供一个通用的方法调用。

## 提案 ｜ Proposal

考虑到Element定义的规范。是不是可以在ObjectElement这样的自定义Element中提供类似
callNativeMethods(methodName,params) 具体API 可以调整
这样的方式来调用Dart侧的能力。

**Comment by andycall** [comment]
https://github.com/openkraken/website/pull/210
