### ISSUE TITLE
text control element 在 macOS 上不响应点击后拖动选择文本的手势

### ISSUE THREAD

**Issue by temper357** [openkraken/kraken#1325]
Web 的 input/textarea element 与 Flutter 的 EditableText Widget 在 macOS 上（移动端不支持）具备点击后拖动选择文本的手势，Kraken 目前的 input/textarea element 不支持，见下面截图对比。

![text-control](https://user-images.githubusercontent.com/5419233/163093254-65adabe5-5197-4809-a20f-f4aba9fc8c94.gif)

**Comment by xuzhongpeng** [comment]
拖动选中交互与滚动会冲突，先实现pc端上的滚轮滚动事件 #1438

**Comment by xuzhongpeng** [comment]
在#1450上跟踪
