### ISSUE TITLE
[兼容性问题] 在不同机型、不同操作系统、不同系统版本均出现了渲染问题，导致页面白屏以及点击事件无响应

### ISSUE THREAD

**Issue by JuneScut** [openkraken/kraken#1329]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

kraken 0.10, 适配 flutter 2.2 

### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 
[bundle.js.zip](https://github.com/openkraken/kraken/files/8488936/bundle.js.zip)

**预期结果 ｜ Expected results:** 
页面正常运行

**实际结果 ｜ Actual results:** 
渲染层报错，页面白屏
操作系统类型： iOS 和 Android
机型：iPhone10,1，iPhone14,5，iPhone13,4， HONOR HLK-AL00，HONOR CMA，HONOR KRJ-W09，vivo sdm660， HUAWEI CLT，HUAWEI ANG，Xiaomi odin，Xiaomi raphael
具体报错日志如：【腾讯文档】北海使用线上日志收集
https://docs.qq.com/sheet/DVGRKU0NsZ2JXZVJH?u=605d8cf09b2b491ebe34c884c3af1d48&tab=ucu92m

**Comment by airingursb** [comment]
复现用例待补齐

**Comment by JuneScut** [comment]
测试用例补齐：[bundle.js.zip](https://github.com/openkraken/kraken/files/8488936/bundle.js.zip)

**Comment by wssgcg1213** [comment]
Fixed at https://github.com/openkraken/kraken/pull/1334

**Comment by wssgcg1213** [comment]
其余的部分, 看起来是网络原因, 如果有具体的堆栈可以再提 issue 反馈~
