### ISSUE TITLE
UICommand 和 iOS 15 SDK UIKitCore中类名重复定义

### ISSUE THREAD

**Issue by 7fresh** [openkraken/kraken#1344]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.11.0
### 重现步骤 ｜ Steps To Reproduce

iOS中引入 `#include <kraken_bridge/kraken_bridge.h>`头文件

**重现代码 | Code example:** 

```#include <kraken_bridge/kraken_bridge.h>```

**预期结果 ｜ Expected results:** 

程序正常编译

**实际结果 ｜ Actual results:** 

![WX20220422-104743@2x](https://user-images.githubusercontent.com/86824369/164586770-63f19fae-b4f4-4ad1-9a67-6073de62527c.png)

**Comment by andycall** [comment]
我在重构的版本里面已经将这个 struct 从头文件删除了

https://github.com/openkraken/kraken/pull/1063
