### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by yifei8** [openkraken/kraken#1349]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.11.0

### 重现步骤 ｜ Steps To Reproduce
运行example

**预期结果 ｜ Expected results:** 
正常运行example

**实际结果 ｜ Actual results:** 
Launching lib\main.dart on V2024A in debug mode...
lib\main.dart:1
: Error: Type 'DeleteTextIntent' not found.
../…/widget/text_control.dart:218
  void _handleDeleteText(DeleteTextIntent intent) {
                         ^^^^^^^^^^^^^^^^
: Error: Type 'DeleteByWordTextIntent' not found.
../…/widget/text_control.dart:227
  void _handleDeleteByWordText(DeleteByWordTextIntent intent) {
                               ^^^^^^^^^^^^^^^^^^^^^^

**Comment by maoeryan** [comment]
+1

**Comment by YujiangLi** [comment]
@yifei8 请问下怎么解决这个问题的啊

**Comment by xzw168** [comment]
+1

**Comment by lion2tomato** [comment]
+1 I change flutter version from 3.3 to 2.8.0,this issue resolved
