### ISSUE TITLE
error  'kraken' is not defined  no-undef

### ISSUE THREAD

**Issue by yifei8** [openkraken/kraken#1376]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

新增方法invokeMethod用于js和native通信测试
```javascript
 methods: {
    invokeMethod () {
      kraken.methodChannel.invokeMethod('somemethod', 'parameter 1', ['parameter 2'], {
        value: 'parmeter 3',
      })
    }
  }
```

### 重现步骤 ｜ Steps To Reproduce
npm run build

**预期结果 ｜ Expected results:** 
编译成功

**实际结果 ｜ Actual results:** 
编译失败
```javascript
Module Error (from ./node_modules/eslint-loader/index.js):

E:\kraken_ws\kraken_smaple\demos\hello-vue\src\views\kraken.vue
  31:7  error  'kraken' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```

**Comment by wssgcg1213** [comment]
这是因为你的前端工程不识别 kraken 这个全局对象导致的, 可以尝试这里提到的方法 https://stackoverflow.com/questions/41552041/global-variables-in-javascript-and-eslint

**Comment by yifei8** [comment]
也就是按北海开发的页面，直接运行在h5下是跑不了的？那如何跨端呢

**Comment by wssgcg1213** [comment]
@yifei8 不是的, `kraken` 这个对象是宿主环境全局对象，就像 chrome 浏览器内有一个 `chrome` 对象一样, 它用于调用宿主环境特别(指不存在于 Web 标准中的)提供的能力
<img width="375" alt="image" src="https://user-images.githubusercontent.com/3922719/167090531-cc355356-4d2e-44bd-8eb1-b544f1dab119.png">

**Comment by yifei8** [comment]
@wssgcg1213 这个我知道，我的意思是咱们北海既然是支持跨平台，应该也是要支持跨端的，确保咱们前端的业务打包出来的产物也能直接在浏览器环境下运行（即kraken的端内和端外环境都可以正常运行），比如说这个kraken全局对象，在浏览器下是不是可以也有一个对应的支持，比如在window下挂一个kraken，以及相应的方法，当然这个可能需要提供相应的前端cli的支持。
