### ISSUE TITLE
运行滚动页面，部分item不支持

### ISSUE THREAD

**Issue by qq286838947** [openkraken/kraken#1385]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
/v0.11.0/

### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 
1.element instanceof win.HTMLIFrameElement
2.打包resize-observer-polyfill，typeof window.ResizeObserver !== 'undefined'
**预期结果 ｜ Expected results:** 
element instanceof win.HTMLIFrameElement 
typeof window.ResizeObserver !== 'undefined'结果为true

**实际结果 ｜ Actual results:** 
1.Window.HTMLIFrameElement类型不存在
2.typeof window.ResizeObserver == 'undefined'

**Comment by wssgcg1213** [comment]
iframe 需要引入插件实现，ResizeObserver 目前还未实现

**Comment by qq286838947** [comment]
在安卓手机上加载长列表页面，列表过长时应用会OOM退出，使用chrom打开则无这个问题

**Comment by wssgcg1213** [comment]
> 在安卓手机上加载长列表页面，列表过长时应用会OOM退出，使用chrom打开则无这个问题

具体 case 可以说明一下, 另外测试长列表的时候不要开启 devtoolsService, 这个会记录网络请求
