### ISSUE TITLE
安卓真机上加载sliver无限滚动列表，应用oom崩溃

### ISSUE THREAD

**Issue by qq286838947** [openkraken/kraken#1386]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.11.0

### 重现步骤 ｜ Steps To Reproduce

参照https://openkraken.com/guide/advanced/high-performance-list例子使用sliver进行列表加载
页面实际效果类似https://github.com/InVeritaSoft/Mobile_frameworks_UI-benchmarks/tree/master/usecase_1/React_native

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 
如知乎中有回收和加速效果https://zhuanlan.zhihu.com/p/366587010描述，有内存回收和加速优化，运行流畅

**实际结果 ｜ Actual results:** 
应用OOM退出

**Comment by wssgcg1213** [comment]
可以提供日志信息吗

**Comment by qq286838947** [comment]
const container = document.createElement('div');
// 修改 display 为 sliver.
container.style.display = 'sliver';
// 必须指定渲染容器节点滚动方向的尺寸(height).
container.style.height = '100vh';

// 创建 100 个子节点.
for (let i = 0; i < 1000; i++) {
  const ele = document.createElement('div');
  ele.style.background = i % 2 ? '#fff' : '#e6e6e6';
  // Sliver 元素默认滚动方向为垂直方向
  // 它的子元素在水平方向上的尺寸(width)会被自动撑满.
  ele.style.padding = '35rpx 60rpx';
  ele.appendChild(document.createTextNode(`第 ${i + 1} 个元素`));

  // 模拟内部元素高度不定场景
  var img = document.createElement('img');
  img.height = 100
  img.width = 100
  img.src = './images/1.jpeg'
    ele.appendChild(img);

  container.appendChild(ele);
}

document.body.appendChild(container);

**Comment by qq286838947** [comment]
加载图片是这个https://github.com/InVeritaSoft/Mobile_frameworks_UI-benchmarks/blob/master/usecase_1/React_native/images/0.jpeg

**Comment by qq286838947** [comment]
lowmemorykiller: Kill 'xxxxxxxxxxx' (xxxx), uid xxxx, oom_adj 0 to free 3313932kB
