### ISSUE TITLE
请问支持发起grpc请求么

### ISSUE THREAD

**Issue by yl-yue** [openkraken/kraken#1398]
## 使用场景 
请问支持发起grpc请求么，使用protobuf作为消息序列化协议。

## 提案 
1. 是否受到限制，无法实现
2. 使用Flutter原生实现？那么与原生集成兼容么？
3. 使用vue(grpc-web)实现，那么会受限制么？

**Comment by tang5011235** [comment]
基于jsv8引擎，按道理来说支持对js代码的运行。

**Comment by andycall** [comment]
可以使用自定义api，然后通过dart来实现

http://openkraken.com/guide/advanced/custom-js-api

**Comment by wssgcg1213** [comment]
不太清楚 grpc 是什么, 你可以依赖 Web API 实现对应的 Client 或者是通过 Flutter 扩展的形式实现，Kraken 内核不会对这些扩展能力有限制或干预  

扩展的文档上面提供了~

**Comment by yl-yue** [comment]
感谢回复，我让团队测试下，后续将测试结果记录在这。

**Comment by tang5011235** [comment]
I/KRAKEN_NATIVE_LOG( 2661): {code: 2, message: 'Http response at 400 or 500 level', metadata: {...}, stack: '    at call (native)
I/KRAKEN_NATIVE_LOG( 2661):     at F (assets:assets/app.js)
I/KRAKEN_NATIVE_LOG( 2661):     at lr (assets:assets/app.js)
I/KRAKEN_NATIVE_LOG( 2661):     at <anonymous> (assets:assets/app.js)
I/KRAKEN_NATIVE_LOG( 2661):     at call (native)
I/KRAKEN_NATIVE_LOG( 2661):     at tt (assets:assets/app.js)
I/KRAKEN_NATIVE_LOG( 2661):     at et (assets:assets/app.js)
I/KRAKEN_NATIVE_LOG( 2661):     at qt (assets:assets/app.js)
I/KRAKEN_NATIVE_LOG( 2661):     at $t (assets:assets/app.js)
I/KRAKEN_NATIVE_LOG( 2661):     at <anonymous> (assets:assets/app.js)
I/KRAKEN_NATIVE_LOG( 2661):     at <anonymous> (assets:assets/app.js)
I/KRAKEN_NATIVE_LOG( 2661):     at dispatchEvent (native)
I/KRAKEN_NATIVE_LOG( 2661):     at setState (vm://polyfill.js)
I/KRAKEN_NATIVE_LOG( 2661):     at handleError (vm://polyfill.js)
I/KRAKEN_NATIVE_LOG( 2661):     at r (vm://polyfill.js)
I/KRAKEN_NATIVE_LOG( 2661):     at <anonymous> (vm://polyfill.js)
I/KRAKEN_NATIVE_LOG( 2661): '}
E/KRAKEN_NATIVE_LOG( 2661): TypeError: not a function
E/KRAKEN_NATIVE_LOG( 2661): 
E/KRAKEN_NATIVE_LOG( 2661): TypeError: not a function
E/KRAKEN_NATIVE_LOG( 2661): 
F/libc    ( 2661): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 10569 (1.ui), pid 2661 (xample.untitled)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/a60qzc/a60q:11/RP1A.200720.012/A6060ZCU3CVC2:user/release-keys'
Revision: '8'
ABI: 'arm64'
Timestamp: 2022-05-28 09:07:22+0800
pid: 2661, tid: 10569, name: 1.ui  >>> com.example.untitled <<<
uid: 10661
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
Cause: null pointer dereference
    x0  b40000750e51e250  x1  b40000748e5cb0f8  x2  ffffffffffffffff  x3  0000000000000048
    x4  0000000000000010  x5  0000000000000018  x6  00000076d5d30000  x7  00000000094c5ea2
    x8  0000000000000000  x9  0000000000000000  x10 00000073b5c40ec8  x11 0000000000000000
    x12 0000000000000000  x13 00000000629175ca  x14 0000000000000000  x15 0000993a12ff04f4
    x16 00000073b5cedd78  x17 00000073b5c40e94  x18 00000073cba04000  x19 b40000750e51e250
    x20 b40000750e51e2e8  x21 b40000751e518450  x22 ffffffffffffffff  x23 b40000748e5cb0f0
    x24 b40000748e5cb090  x25 ffffffffffffffff  x26 00000074249ae000  x27 0000000000000010
    x28 0000000400000072  x29 00000074249acef0
    lr  00000073b5b186f0  sp  00000074249acee0  pc  00000073b5c40ee0  pst 0000000080000000
backtrace:
      #00 pc 000000000001cee0  /data/app/~~HXAUg9jWI6pzcOiciKhgyg==/com.example.untitled-D3M0lodLM2YCYvpRhuVG4g==/lib/arm64/libquickjs.so (__JS_FreeValueRT+76) (BuildId: 17faa7cfdb0be179f900669013f63e8bd13da596)
      #01 pc 000000000004d6ec  /data/app/~~HXAUg9jWI6pzcOiciKhgyg==/com.example.untitled-D3M0lodLM2YCYvpRhuVG4g==/lib/arm64/libkraken.so (kraken::binding::qjs::handleInvokeModuleTransientCallback(void*, int, char const*, NativeString*)+776) (BuildId: dc350115283db2c4d01d06d23d842cd130a826a3)
      #02 pc 0000000000006df4  [anon:dart-codespace]
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"60","method":"getMemoryUsage","params":{"isolateId":"isolates/3072841704154467"}}
Failed to send request: {"jsonrpc":"2.0","id":"61","method":"getMemoryUsage","params":{"isolateId":"isolates/2768893337223287"}}


grpc报错  程序奔溃

**Comment by andycall** [comment]
好像是 dart 触发 error 事件就会 crash 的bug。之前遇到过，我记得已经解决了。
请问你用的是哪个版本？

**Comment by tang5011235** [comment]
0.11

**Comment by tang5011235** [comment]
flutter 版本为2.8.1
