### ISSUE TITLE
自定义widget嵌套后，子widget 通过js appendChild后，子widget代码无法收到元素变更，断点看代码原因mount为false

### ISSUE THREAD

**Issue by zjt123** [openkraken/kraken#1408]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

main/v0.11.0

### 重现步骤 ｜ Steps To Reproduce
android、ios环境，自定义widget嵌套后，子widget 通过js appendChild后，子widget代码无法收到元素变更，断点看代码原因没有rebuild，mount为false

**重现代码 | Code example:** 

js代码：
const container = document.createElement('k-demo-root');
      // container是div是没问题的
        // const container = document.createElement('div');
        // 必须指定渲染容器节点滚动方向的尺寸(height).
        container.style.height = '100vh';
        const outter = document.createElement('k-demo-element2');
        container.appendChild(outter);
        const ele = document.createElement('div');
        ele.style.height = '100';
        const clickUi = document.createTextNode(`测试点击`);
        ele.appendChild(clickUi);
        container.appendChild(ele);

        ele.addEventListener('click', function() {
          // const tmpdiv1 = document.createElement('k-demo-element3');
          const tmpdiv = document.createElement('div');
          tmpdiv.style.height = '200px';
          tmpdiv.style.width = '100px';
          tmpdiv.appendChild(document.createTextNode(`第 1个元素`));
          // tmpdiv1.appendChild(tmpdiv)
          outter.appendChild(tmpdiv);
          console.log('zjt', outter.children.length);

          // outter.sayHi(tmpdiv); // flutter: Kraken: Hi!
        });
        document.body.appendChild(container);

dart代码

    Kraken.defineCustomElement('k-demo-element2',
        (context) {
      return DemoElement2(context);
    });
    Kraken.defineCustomElement('k-demo-root',
        (context) {
      return DemoElement4(context);
    });

demo_component2.dart

import 'package:kraken/widget.dart';
import 'package:flutter/material.dart';

class DemoElement4 extends WidgetElement {
  DemoElement4(context) : super(context, defaultStyle: {'display': 'block'});

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties,
      List<Widget> children) {
    return Container(child: Column(children: children,),);
  }

  @override
  void didAttachRenderer() {
    // TODO: implement didAttachRenderer
    print('zjt didAttachRenderer DemoElement4 ');
    super.didAttachRenderer();
  }
}

demo_component2.dart

import 'package:kraken/widget.dart';
import 'package:flutter/material.dart';

class DemoElement2 extends WidgetElement {
  List<MyList> goodsList = [];
  late Widget targetW;
  bool isInit = false;

  // DemoElement2(context) : super(context, defaultStyle: {'display': 'block'});
  DemoElement2(context) : super(context);

  append1(children) {
    goodsList[0].appendW(children);
  }

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties,
      List<Widget> children) {
    // setAttribute("id", "test1");
    if (children.length > 0) {
      append1(children);
    }
    if (isInit) {
      return targetW;
    }
    isInit = true;
    goodsList.add(MyList());
    targetW = Container(
        color: Colors.blue,
        width: 300,
        height: 500,
        child:CustomScrollView(
          slivers: goodsList,));
    return targetW;
  }

  dynamic sayHi(List<dynamic> args) {
    print(args);
    print(args[0]);
    print(args[0].runtimeType);
  }

  @override
  getBindingProperty(String key) {
    if (key == 'sayHi') {
      return sayHi;
    }

    return super.getBindingProperty(key);
  }
}
class MyList extends StatefulWidget {

  List<Widget> wList = [];
  _MyListState state = _MyListState();
  @override
  State<StatefulWidget> createState() {
    return state;
  }

  appendW(List<Widget> w) {
    wList = w;
    state.setState(() {

    });
  }
}
class _MyListState extends State<MyList> {
  @override
  Widget build(BuildContext context) {
    return SliverList(
        delegate: SliverChildBuilderDelegate(
              (_, index) => _ListWidget(index),
          childCount: widget.wList.length,
        )
    );
  }

  _ListWidget(index) {
    return Container(child: widget.wList[index]);
  }
}

**Comment by zjt123** [comment]
@answershuto 这个bug怎么解，能提供点思路不？

**Comment by xuzhongpeng** [comment]
先关闭，如果还有问题请在此issue下回复
