### ISSUE TITLE
Android 体验 apk 下载报权限错误

### ISSUE THREAD

**Issue by rickenwang** [openkraken/kraken#1427]
下载此体验 apk 报错无权限错误
![image](https://user-images.githubusercontent.com/24379487/173226473-66db4deb-698f-4d36-811e-4e6b0f6f5d89.png)

<img width="467" alt="image" src="https://user-images.githubusercontent.com/24379487/173226541-7d7a7a04-2a6c-4395-9c39-912101007612.png">

**Comment by answershuto** [comment]
OSS 出现了一些问题，代码在这可以先本地打包体验 https://github.com/openkraken/samples/tree/main/integration/playground

**Comment by rickenwang** [comment]
cli 安装也有类似的问题，看 install 脚本会下载一个 oss 上的资源，现在安装会失败

**Comment by answershuto** [comment]
对， OSS 访问最近都出现了问题，我们还在讨论方案来解决这个问题。

**Comment by rickenwang** [comment]
好，谢谢
