### ISSUE TITLE
windows 环境下编译失败

### ISSUE THREAD

**Issue by xu-baolin** [openkraken/kraken#151]
### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by andycall** [comment]
需要提供必要的信息

**Comment by xu-baolin** [comment]
`$ npm i @openkraken/cli -g` 报错；

` npm run build:bridge:android`同样报错，试着调试了下，错误有点多，貌似Windows下没有经过测试呢

**Comment by yuanyan** [comment]
> `$ npm i @openkraken/cli -g` 报错；
> 
> ` npm run build:bridge:android`同样报错，试着调试了下，错误有点多，貌似Windows下没有经过测试呢

因为主要都是 macOS，暂时还没有支持 windows 环境

**Comment by xu-baolin** [comment]
![image](https://user-images.githubusercontent.com/61075224/114392077-dee23d80-9bca-11eb-8f5d-99c7a5534d6b.png)

**Comment by wssgcg1213** [comment]
请按照 Issue 模板提供必要信息，如错误信息。

**Comment by andycall** [comment]
> > `$ npm i @openkraken/cli -g` 报错；
> > ` npm run build:bridge:android`同样报错，试着调试了下，错误有点多，貌似Windows下没有经过测试呢
> 
> 因为主要都是 macOS，暂时还没有支持 windows 环境

WIndows 构建是支持的，但是需要的一些环境依赖信息在文档里面。还没公开

**Comment by andycall** [comment]
https://github.com/openkraken/website/blob/main/docs/guide/contribute/environment.md
