### ISSUE TITLE
单击事件缺少坐标返回

### ISSUE THREAD

**Issue by freedom-shen** [openkraken/kraken#166]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
V0.7.1

### 重现步骤 ｜ Steps To Reproduce

任意标签添加单击事件

**重现代码 | Code example:** 

``` js
p.addEventListener('click', function (event) {
    console.log(event)
})
```

**预期结果 ｜ Expected results:** 

{.., timestamp: 1618891067095, type: 'click', deltaX:'xxx', deltaY: 'yyyy'}

**实际结果 ｜ Actual results:** 
{.., timestamp: 1618891067095, type: 'click'}

**Comment by wssgcg1213** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/MouseEvent  @answershuto 需要实现 MouseEvent 的接口
