### ISSUE TITLE
double click 支持

### ISSUE THREAD

**Issue by freedom-shen** [openkraken/kraken#167]
## 使用场景 ｜ Use case

目前缺少对于double click的支持，实际开发中还是存在类似 double click放大图片等需要。

## 提案 ｜ Proposal

实现 https://www.w3school.com.cn/jsref/event_ondblclick.asp 的api

``` js
p.addEventListener('dblclick', function(e){})
p.ondblclick = function(e){}
```

**Comment by yuanyan** [comment]
需要额外说明下，dblclick 在 chrome mobile 下是不支持的，但 safari mobile 又是支持的，技术上实现比较简单，但可能 tsc 投票下来决定是否支持该特性。

**Comment by yjhenan** [comment]
> 需要额外说明下，dblclick 在 chrome mobile 下是不支持的，但 safari mobile 又是支持的，技术上实现比较简单，但可能 tsc 投票下来决定是否支持该特性。

看官网你们不是还支持桌面端吗，双击桌面端用的多一些吧
