### ISSUE TITLE
无法使用splitchunk，将应用打成一个bundle，是否会出现包过大。加载速度慢的问题

### ISSUE THREAD

**Issue by DaiHuaXieHuaKai** [openkraken/kraken#171]
无法使用splitchunk，将应用打成一个bundle，是否会出现包过大。加载速度慢的问题

**Comment by wssgcg1213** [comment]
感谢你的建议~  
目前的方式是社区上比较普遍的做法，有没有人知道 React Native 是否遇到类似的问题?

**Comment by train860** [comment]
React Native 的bundle是放到应用里面的，相当于不是远程加载

**Comment by wssgcg1213** [comment]
> React Native 的bundle是放到应用里面的，相当于不是远程加载

本地和远程都可以支持，这一点上暂时没有差异。

**Comment by yuanyan** [comment]
会支持 import 一个 bundle url 的能力

**Comment by syanbo** [comment]
> 感谢你的建议〜
> 目前的方式是社区上比较普遍的做法，有没有人知道React Native是否遇到类似的问题？

会有类似问题 bundle 越大 加载时间成正比
当然可以使用RAM 内联引用优化

**Comment by wssgcg1213** [comment]
跟进 #119
