### ISSUE TITLE
讨论是否需要增加网络拦截的切面接口

### ISSUE THREAD

**Issue by wssgcg1213** [openkraken/kraken#172]
## 使用场景 ｜ Use case

类似 Android WebView 的 `shouldInterceptRequest`，用于对 WebView 中加载的资源的拦截，保证业务的弱网体验

https://developer.android.com/reference/android/webkit/WebViewClient#shouldInterceptRequest(android.webkit.WebView,%20android.webkit.WebResourceRequest)
## 提案 ｜ Proposal

增加可选参数 `shouldInterceptRequest` 类型为 `WebResponse Function(Uri uri, WebRequest request)`，若注册此方法，则 Kraken 内所有加载网络部分都会经过此方法，若返回非 null 值，则使用返回的内容，否则继续网络请求。

**Comment by andycall** [comment]
可以看下 Flutter Network View 是如何实现的

https://flutter.dev/docs/development/tools/devtools/network

**Comment by wssgcg1213** [comment]
@andycall devtools 是使用 observatory 接口实现的观测者模式，与业务需求不相符

**Comment by wssgcg1213** [comment]
这个问题 Android 和 iOS 做法是有差异的，Android WebView 提供了 shouldInterceptRequest 的 hook，iOS 则是需要通过 NSURLProtocol 捕获全局的请求 + 一些处理来实现，这是两种倾向性感觉称不上孰优孰劣，安卓的实现会对开发者友好一点。Flutter 提供了一个 HttpOverrides 的类可以实现类似 iOS 的功能，不过这个类的初衷是提供 mock 数据，重写一个 HttpClient 的成本也挺高的

**Comment by tylorvan** [comment]
如果是一个强需求，个人觉得是不是直接暴露override request 实现可能，默认走Flutter 的请求，
允许用户直接对接到客户端的自定义网络库，这样也不会入侵主库同时也有足够的灵活性

**Comment by wssgcg1213** [comment]
> 如果是一个强需求，个人觉得是不是直接暴露override request 实现可能，默认走Flutter 的请求，
> 允许用户直接对接到客户端的自定义网络库，这样也不会入侵主库同时也有足够的灵活性

Well, 你们这边的经验, 这种能力是否是强诉求? 有没有实现过, 有的话思路是怎么样的呢?

**Comment by tylorvan** [comment]
> > 如果是一个强需求，个人觉得是不是直接暴露override request 实现可能，默认走Flutter 的请求，
> > 允许用户直接对接到客户端的自定义网络库，这样也不会入侵主库同时也有足够的灵活性
> 
> Well, 你们这边的经验, 这种能力是否是强诉求? 有没有实现过, 有的话思路是怎么样的呢?

这块有类似的实现，其实这块与Kraken 中的Mtop、或者JSBundle 请求实现有些类似，有默认实现也可以完整替换，我看下目前的kraken 网络库对接部分，看看能否抽离一下

之前的 bundle override 能力设计：
![image](https://user-images.githubusercontent.com/5905365/115529858-d7571e80-a2c5-11eb-9fc4-e7a9878cf82c.png)
![image](https://user-images.githubusercontent.com/5905365/115529958-edfd7580-a2c5-11eb-9bc8-addfd38f5c6f.png)


对于是否是强需求，我理解这部分算是强需求，如果客户端原有的网络库上做了很多定制，比如通用网络请求错误率统计、网络接口下发token 过期要踢出账户，可能都需要依赖对网络请求的response 的监听

**Comment by wssgcg1213** [comment]
我会在下周尝试提一个 PR 实现，这边 Issue 保留可以继续讨论

**Comment by w4lle** [comment]
可以拦截Dio的HttpClient，支持修改请求、返回、模拟弱网等，可以参考我们开源的项目 https://github.com/KwaiAppTeam/KDebugTools

**Comment by wssgcg1213** [comment]
> 可以拦截Dio的HttpClient，支持修改请求、返回、模拟弱网等，可以参考我们开源的项目 https://github.com/KwaiAppTeam/KDebugTools

好的我们看下。像 NetworkImage 这种不通过 dio 发起请求的就没办法了，kraken 还需要保证多页面的时候页面之间的隔离性

**Comment by w4lle** [comment]
这个方案是拦截HttpClinet而非Dio，NetworkImage 应该也是走的HttpClient请求的，理论上也是支持的。
