### ISSUE TITLE
Mac 安装脚手架失败

### ISSUE THREAD

**Issue by kiradea** [openkraken/kraken#175]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/12182992/115544944-d0d0a300-a2d5-11eb-8088-8a208cb0e736.png">

**Comment by wssgcg1213** [comment]
根据截图无法判断, 需要提供更多信息, 麻烦补充并 reopen @kiradea

**Comment by kiradea** [comment]
> 根据截图无法判断, 需要提供更多信息, 麻烦补充并 reopen @kiradea

我就是安装脚手架失败了，还需要什么信息

**Comment by andycall** [comment]
有用的错误信息在你截图的上面，请提供完全错误日志

**Comment by kiradea** [comment]
> 有用的错误信息在你截图的上面，请提供完全错误日志

OK，One Seconds

**Comment by kiradea** [comment]
![image](https://user-images.githubusercontent.com/12182992/115678730-662a7080-a384-11eb-92d1-2b1d3fd4effc.png)

**Comment by andycall** [comment]
https://github.com/openkraken/kraken/issues/190

**Comment by kiradea** [comment]
> #190

Thanks
