### ISSUE TITLE
Failed to execute 'appendChild' on 'Node': first arguments should be an Node type.

### ISSUE THREAD

**Issue by andycall** [openkraken/kraken#177]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.7.2

### 重现步骤 ｜ Steps To Reproduce

kraken https://kraken.oss-cn-hangzhou.aliyuncs.com/demo/guide-high-performance-list.js

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

just works

**实际结果 ｜ Actual results:** 

```
Failed to execute 'appendChild' on 'Node': first arguments should be an Node type.
[native code]
global code@https://kraken.oss-cn-hangzhou.aliyuncs.com/demo/guide-high-performance-list.js:22:20
```

**Comment by qiaoyhh** [comment]
这个问题是在0.7.2版本中解决了么？

**Comment by andycall** [comment]
这几天发布0.7.2就会解决

**Comment by qiaoyhh** [comment]
> 这几天发布0.7.2就会解决

好的，Thanks♪(･ω･)ﾉ

**Comment by guotao** [comment]
> > 这几天发布0.7.2就会解决
> 
> 好的，Thanks♪(･ω･)ﾉ

已经解决了么？
