### ISSUE TITLE
App端显示与浏览器不一致

### ISSUE THREAD

**Issue by zhuyashan** [openkraken/kraken#183]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.7.1

### 重现步骤 ｜ Steps To Reproduce
使用rax创建项目

**重现代码 | Code example:** 
https://github.com/zhuyashan/KrakenDemo.git

**预期结果 ｜ Expected results:** 
![](https://ftp.bmp.ovh/imgs/2021/04/03a5ea83b5dad5d3.png)

**实际结果 ｜ Actual results:** 
![](https://ftp.bmp.ovh/imgs/2021/04/919cab023b6c334f.png)

**Comment by wssgcg1213** [comment]
感谢反馈  
看起来是 text-overflow 工作不正常，cc @temper357
