### ISSUE TITLE
是否有计划支持开发时热更新?

### ISSUE THREAD

**Issue by yeli19950109** [openkraken/kraken#184]
## 使用场景 ｜ Use case

在使用vue/react时如果每次都需要打包才是运行会拖慢开发效率,flutter在开发时的快速热更新的能力算是一个巨大的优势

**Comment by wssgcg1213** [comment]
感谢反馈  
1. 热更新属于前端框架支持的功能
2. 如果把 Kraken 类比为 WebView，也就不存在渲染引擎需要为前端框架开发热更新能力的诉求
3. 前端框架的热更新主要依赖的是 DOM API 和 WebSocket/XHR，这些能力理论上目前是完备的，如果工作起来有问题的话需要深入看一下原因

**Comment by wssgcg1213** [comment]
@answershuto Help 一起看一下为什么没有 work 吧

**Comment by yuanyan** [comment]
应该是Vue/React的demo工程上没有开启 hotreload

**Comment by aolsx** [comment]
+1 需要开发时热更新

**Comment by ni742015** [comment]
![image](https://user-images.githubusercontent.com/14267380/131281576-fb4435c6-97c6-46df-a472-5e6b292c80eb.png)

本地修改代码后，还是会遇到报错页面不刷新。用的最新的0.8.3版本
