### ISSUE TITLE
实现文档流block块上下margin合并

### ISSUE THREAD

**Issue by army8735** [openkraken/kraken#185]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
Version: master/v0.7.1

### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 
```js
var text1 = document.createTextNode('Hello');
var div1 = document.createElement('div');
div1.style.marginBottom = '10px';
div1.appendChild(text1);

var text2 = document.createTextNode('World!');
var div2 = document.createElement('div');
div2.style.marginTop = '10px';
div2.appendChild(text2);

document.body.appendChild(div1);
document.body.appendChild(div2);
```

**预期结果 ｜ Expected results:** 
**实际结果 ｜ Actual results:** 
运行和浏览器的差异截图：
![image](https://user-images.githubusercontent.com/174904/115645206-893c2c80-a352-11eb-9368-ec667366ced0.png)

### 其它思路建议
1. 设置`bottomList`和`topList`2个列表，用来保存一系列的需要合并的上下margin
2. 布局时遍历children时，遇到inline等非block节点，尝试进行合并margin并清空2个列表
3. 遇到block时，如果是空内容无高度block节点，记录添加上下margin2个值继续循环
4. 如果是普通block节点，记录添加marginTop，尝试进行合并margin并清空2个列表，再记录添加marginBottom
5. 如果是最后一个节点，尝试进行合并margin并清空2个列表

合并算法，获取diff偏移值，不为0则对节点的y进行相对调整：
```js
function getMergeMarginTB(topList, bottomList) {
  let total = 0;
  let max = topList[0];
  let min = topList[0];
  topList.forEach(item => {
    total += item;
    max = Math.max(max, item);
    min = Math.min(min, item);
  });
  bottomList.forEach(item => {
    total += item;
    max = Math.max(max, item);
    min = Math.min(min, item);
  });
  // 正数取最大，负数取最小，正负则相加
  let diff = 0;
  if(max > 0 && min > 0) {
    diff = Math.max(max, min) - total;
  }
  else if(max < 0 && min < 0) {
    diff = Math.min(max, min) - total;
  }
  else if(max !== 0 || min !== 0) {
    diff = max + min - total;
  }
  return diff;
}
```

**Comment by wssgcg1213** [comment]
感谢反馈  
https://openkraken.com/api/styles/difference  
margin 合并不生效为已知差异，这个在浏览器上的表现在社区上也有一些争议，所以暂时未支持  

我们会在下一次 TSC 会议讨论此议题，也欢迎其他同学在这个 issue 表达看法

**Comment by yuanyan** [comment]
浏览器下双边距合并的特性除了文本场景其他可能看都是“弊大于利”（也是历史原因，Web 诞生之初是为了文本文档设计的）
