### ISSUE TITLE
支持 Flutter 2.0

### ISSUE THREAD

**Issue by filusilia** [openkraken/kraken#187]
## 使用场景 ｜ Use case

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.5

冲鸭!

**Comment by wssgcg1213** [comment]
Flutter 2.0 将在下个版本 Release 时支持

**Comment by filusilia** [comment]
> Flutter 2.0 将在下个版本 Release 时支持

吼！辛苦辣！

**Comment by logoove** [comment]
搞了好久才发现 安装新版flutter2.0.5不支持

**Comment by andycall** [comment]
Supported
