### ISSUE TITLE
Kraken Binary NOT exists, try reinstall.

### ISSUE THREAD

**Issue by FantasyWind2016** [openkraken/kraken#188]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
kraken 0.7.2
npm 7.10.0
node v14.16.1
MacOS 10.15.7

### 重现步骤 ｜ Steps To Reproduce

```
$ sudo npm install -g @openkraken/cli

added 24 packages in 1s

$ kraken https://raw.githubusercontent.com/openkraken/kraken/master/kraken/example/assets/bundle.js

Kraken Binary NOT exists, try reinstall.

```

**预期结果 ｜ Expected results:** 

打开对应界面

**实际结果 ｜ Actual results:** 

命令行报错

**Comment by FantasyWind2016** [comment]
node是从官网下载的最新版本重装了，然后也更新了npm

**Comment by andycall** [comment]
node 官网下载的会安装在 /usr/local 目录，全局安装的话，下载 kraken app 会有权限问题。
可以使用下面的命令解决：

```
sudo chown <username>:staff /usr/local/lib # 把 <username> 替换成你的用户名
npm install -g @openkraken/cli # 不要带 sudo
```

**Comment by FantasyWind2016** [comment]
> node 官网下载的会安装在 /usr/local 目录，sudo 全局安装的话，下载 kraken app 会有权限问题。
> 可以使用下面的命令解决：
> 
> ```
> sudo chown <username>:staff /usr/local/lib # 把 <username> 替换成你的用户名
> npm install -g @openkraken/cli # 不要带 sudo
> ```

安装命令没带sudo，好像还是一样的问题

```
$ sudo npm uninstall -g @openkraken/cli

removed 24 packages, and audited 1 package in 531ms

found 0 vulnerabilities

$ sudo chown -R $(whoami) /usr/local/lib
$ npm install -g @openkraken/cli

added 24 packages in 1s
$ kraken https://raw.githubusercontent.com/openkraken/kraken/master/kraken/example/assets/bundle.js
Kraken Binary NOT exists, try reinstall.
```

**Comment by andycall** [comment]
请问安装的过程中没有一点报错异常吗？

**Comment by andycall** [comment]
正确的安装过程中，是会去执行一个 install.js 的脚本的

```
➜  ~ npm install -g @openkraken/cli
/usr/local/bin/kraken -> /usr/local/lib/node_modules/@openkraken/cli/bin/kraken.js

> @openkraken/cli@0.7.2 postinstall /usr/local/lib/node_modules/@openkraken/cli
> node install.js

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57.2M  100 57.2M    0     0  6293k      0  0:00:09  0:00:09 --:--:-- 7446k
+ @openkraken/cli@0.7.2
updated 1 package in 11.869s
```

**Comment by FantasyWind2016** [comment]
> 正确的安装过程中，是会去执行一个 install.js 的脚本的
> 
> ```
> ➜  ~ npm install -g @openkraken/cli
> /usr/local/bin/kraken -> /usr/local/lib/node_modules/@openkraken/cli/bin/kraken.js
> 
> > @openkraken/cli@0.7.2 postinstall /usr/local/lib/node_modules/@openkraken/cli
> > node install.js
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 57.2M  100 57.2M    0     0  6293k      0  0:00:09  0:00:09 --:--:-- 7446k
> + @openkraken/cli@0.7.2
> updated 1 package in 11.869s
> ```

现在是没有去执行这个脚本，直接就成功了

**Comment by FantasyWind2016** [comment]
昨天下午安装的时候执行这个脚本报编译错误，然后就重新安装了Node，再之后安装好像就不执行这个脚本了

**Comment by andycall** [comment]
这个说不通，postinstall 一定会在 npm install 完成之后执行

**Comment by FantasyWind2016** [comment]
> 这个说不通，postinstall 一定会在 npm install 完成之后执行

现在手动执行了一下install.js脚本，后面就正常了。

**Comment by FantasyWind2016** [comment]
> 这个说不通，postinstall 一定会在 npm install 完成之后执行

昨天一开始脚本执行报错之后，我尝试过npm install命令中增加--ignore-script参数，但只执行了一次；后面再安装就没添加这个参数了。难道这个参数还会影响后面逻辑？

**Comment by andycall** [comment]
看样子是这样的
https://docs.npmjs.com/cli/v7/commands/npm-install#configuration-options-affecting-build-process

**Comment by yuanyan** [comment]
国内网络环境问题还是比较多的，涉及到 下载 的过程可能就会出现不确定的情况

**Comment by Erchoc** [comment]
同样遇到了这个问题，v0.7.2 安装 后命令都正常，运行官网案例就报 kraken 二进制文件缺失（缺失我还能运行个锤锤）

![image](https://user-images.githubusercontent.com/19908809/115752850-17ed8f80-a3cd-11eb-9cf1-ebafa03c7514.png)

**Comment by andycall** [comment]
因为内置的 Kraken 可执行程序是需要一个 postinstall 脚本来下载，被各种原因导致没有执行所以就会出现上面的问题

**Comment by dancancer** [comment]
遇到同样的问题，当时环境为 mac m1， node版本 15.7.0

nvm 切换 node环境到 10.23.2 后重新安装就可以了

安装好后再切回 15.7.0 仍然可以正常运行，貌似只影响安装

**Comment by Eden-Harris** [comment]
非M1芯片遇到同样的问题, `Kraken Binary NOT exists, try reinstall.` 经测试 若nodejs版本在16或15.*均需要将nodejs版本回退到 14.*及略早版本，回退版本后重新执行 `npm i @openkraken/cli -g` 即可写入 Kraken 二进制程序。执行 `kraken https://raw.githubusercontent.com/openkraken/kraken/master/kraken/example/assets/bundle.js` 即可正常运行。这个问题应该是nodejs版本的兼容问题。
