### ISSUE TITLE
android example run error

### ISSUE THREAD

**Issue by siyukok** [openkraken/kraken#189]
kraken/example android平台运行时错误

E/flutter (10011): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libkraken_jsc.so" not found)
E/flutter (10011): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter (10011): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter (10011): #2      nativeDynamicLibrary (package:kraken/src/bridge/platform.dart:26:20)
E/flutter (10011): #3      nativeDynamicLibrary (package:kraken/src/bridge/platform.dart)
E/flutter (10011): #4      _registerDartMethods (package:kraken/src/bridge/from_native.dart:381:5)
E/flutter (10011): #5      _registerDartMethods (package:kraken/src/bridge/from_native.dart)
E/flutter (10011): #6      registerDartMethodsToCpp (package:kraken/src/bridge/from_native.dart:387:3)
E/flutter (10011): #7      initBridge (package:kraken/src/bridge/bridge.dart:25:3)
E/flutter (10011): #8      new KrakenViewController (package:kraken/src/launcher/controller.dart:107:20)
E/flutter (10011): #9      new KrakenController (package:kraken/src/launcher/controller.dart:482:13)
E/flutter (10011): #10     _KrakenRenderObjectWidget.createRenderObject (package:kraken/widget.dart:150:35)
E/flutter (10011): #11     RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5491:28)
E/flutter (10011): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6117:11)
E/flutter (10011): #13     _KrakenRenderObjectElement.mount (package:kraken/widget.dart:216:11)
E/flutter (10011): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (10011): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (10011): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (10011): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (10011): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (10011): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (10011): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (10011): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (10011): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (10011): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (10011): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (10011): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (10011): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (10011): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (10011): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (10011): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (10011): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (10011): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (10011): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (10011): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (10011): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (10011): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (10011): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (10011): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (10011): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (10011): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (10011): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (10011): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (10011): #42     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
E/flutter (10011): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (10011): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (10011): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)

把kraken本地依赖改成pub上的0.7.1版本后解决了

**Comment by andycall** [comment]
本地版本需要构建 kraken bridge，

https://openkraken.com/guide/contribute/development#%E6%9E%84%E5%BB%BA-bridge

**Comment by siyukok** [comment]
> 本地版本需要构建 kraken bridge，
> 
> https://openkraken.com/guide/contribute/development#%E6%9E%84%E5%BB%BA-bridge

好的，谢谢，建议把这个详细文档的地址贴在readme里，不然实在不太好发现

**Comment by andycall** [comment]
> > 本地版本需要构建 kraken bridge，
> > https://openkraken.com/guide/contribute/development#%E6%9E%84%E5%BB%BA-bridge
> 
> 好的，谢谢，建议把这个详细文档的地址贴在readme里，不然实在不太好发现

readme 的下面就有构件 bridge 的文档

**Comment by siyukok** [comment]
> > > 本地版本需要构建 kraken bridge，
> > > https://openkraken.com/guide/contribute/development#%E6%9E%84%E5%BB%BA-bridge
> > 
> > 
> > 好的，谢谢，建议把这个详细文档的地址贴在readme里，不然实在不太好发现
> 
> readme 的下面就有构建 bridge 的文档

我的意思是放在GitHub项目的README.md里会更直观一点，通常看开源项目都是先看Readme文档，想不到官网里有更详细的文档
