### ISSUE TITLE
为啥不直接基于Skia引擎实现自绘？

### ISSUE THREAD

**Issue by yhongm** [openkraken/kraken#191]
## 使用场景 ｜ Use case

既然实现了w3c的标准可以用js直接开发，又不用dart开发，那直接基于Skia引擎不是更好。去掉Flutter中间层不是更好

**Comment by andycall** [comment]
直接基于 skia 引擎实现的确会带来一些性能提升，但是缺引入了很多工程问题。

比如

1. 开发难度 C++ 比 Dart 要高很多
2. 无法和现有 Flutter 应用混合渲染
3. 很难跟随最新 Flutter 版本，享受 Flutter 升级所带来的收益

Dart  在 AOT 之后的性能并没有想象中那么差，至少比 JS 要好上不少。

**Comment by yuanyan** [comment]
Kraken 最早的原型阶段，架构上的确是直接基于图形引擎去实现的，为什么后面变了就如 @andycall  说的，成熟的架构设计需要考虑的因素会比较多，在不打破第一性原理（高性能）的情况下尽可能让他更有生长力。

**Comment by yhongm** [comment]
好的
