### ISSUE TITLE
Kraken运行不起来啊

### ISSUE THREAD

**Issue by infyzz** [openkraken/kraken#193]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.7.2

### 重现步骤 ｜ Steps To Reproduce
kraken http://kraken.oss-cn-hangzhou.aliyuncs.com/demo/guide-styles.js 
Kraken Binary NOT exists, try reinstall.
FAIL: 1

安装cmake出现这个问题
brew install cmake 
![image](https://user-images.githubusercontent.com/20716853/115669776-3aef5380-a37b-11eb-87b0-d484145512d8.png)
我xcode 也是最新的啊

**Comment by andycall** [comment]
```npm install @openkraken/cli -g ``` 的时候，不要带 `--ignore-script`

**Comment by infyzz** [comment]
> npm install @openkraken/cli -g
没有带啊

**Comment by andycall** [comment]
使用 `npm config list` 检查一下  ignore-scripts 是否被设置成全局选项

如果是的话，使用下面的命令关掉

```
npm config set ignore-scripts false

```

**Comment by infyzz** [comment]
还是不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 下午3:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [openkraken/kraken] Kraken运行不起来啊 (#193)





 
使用 npm config list 检查一下  ignore-scripts 是否被设置成全局选项
 
如果是的话，使用下面的命令关掉
 npm config set ignore-scripts false

**Comment by infyzz** [comment]
> 使用 `npm config list` 检查一下 ignore-scripts 是否被设置成全局选项
> 
> 如果是的话，使用下面的命令关掉
> 
> ```
> npm config set ignore-scripts false
> ```
![image](https://user-images.githubusercontent.com/20716853/115672371-134dba80-a37e-11eb-9591-79504085d8d2.png)

**Comment by andycall** [comment]
你这个看上去不是 macOS 系统？

现在 cli 目前仅支持 macOS

**Comment by infyzz** [comment]
> 你这个看上去不是 macOS 系统？
> 
> 现在 cli 目前仅支持 macOS

![Uploading image.png…]()

**Comment by infyzz** [comment]
> 你这个看上去不是 macOS 系统？
> 
> 现在 cli 目前仅支持 macOS

![image](https://user-images.githubusercontent.com/20716853/115674609-69236200-a380-11eb-8fed-c4610fb9835f.png)

**Comment by andycall** [comment]
看不出为啥 postinstall 又没有执行，现在可以先执行 kraken 这个 npm 包里面的 install.js 解决一下

**Comment by infyzz** [comment]
> 看不出为啥 postinstall 又没有执行，现在可以先执行 kraken 这个 npm 包里面的 install.js 解决一下

![image](https://user-images.githubusercontent.com/20716853/115675357-19916600-a381-11eb-8e35-317443729388.png)

**Comment by andycall** [comment]
```node install.js```

**Comment by infyzz** [comment]
> 看不出为啥 postinstall 又没有执行，现在可以先执行 kraken 这个 npm 包里面的 install.js 解决一下

![image](https://user-images.githubusercontent.com/20716853/115675508-39c12500-a381-11eb-8e9f-2ba74259c4d2.png)

**Comment by andycall** [comment]
删掉 build 目录再试一下

**Comment by infyzz** [comment]
> 删掉 build 目录再试一下

![image](https://user-images.githubusercontent.com/20716853/115676065-ccfa5a80-a381-11eb-95ec-f4da35566465.png)

**Comment by andycall** [comment]
https://github.com/openkraken/cli/blob/master/bin/kraken.js#L85

前后逻辑上说不通啊，你看下是不是哪里操作存在问题

**Comment by infyzz** [comment]
> https://github.com/openkraken/cli/blob/master/bin/kraken.js#L85

哥 我是个菜鸡啊 我看不懂

**Comment by andycall** [comment]
我有点怀疑你安装的 kraken 和你执行 install.js 不是同一个 npm package。

试下用 `./bin/kraken.js` 执行，或者使用 `type kraken` 看下路径是否正确

**Comment by infyzz** [comment]
> 我有点怀疑你安装的 kraken 和你执行 install.js 不是同一个 npm package。
> 
> 试下用 `./bin/kraken.js` 执行，或者使用 `type kraken` 看下路径是否正确
soga 我使用了nvm  这个咋整
![image](https://user-images.githubusercontent.com/20716853/115680174-e9989180-a385-11eb-947c-5d3e12392d4d.png)

**Comment by andycall** [comment]
那这个 npm package 应该在 /Users/mr-zhao/.nvm/versions/node/v14.15.4/lib/node_modules 里面

**Comment by infyzz** [comment]
> 那这个 npm package 应该在 /Users/mr-zhao/.nvm/versions/node/v14.15.4/lib/node_modules 里面

可以了哥 然后呢 就这吗
![image](https://user-images.githubusercontent.com/20716853/115681365-0aadb200-a387-11eb-94ba-b2071e6f9529.png)

**Comment by infyzz** [comment]
好吧 ok了 没看到另外一个屏幕上已经出现画面了 谢谢董大哥
