### ISSUE TITLE
请问kraken是如何打包应用为三端的

### ISSUE THREAD

**Issue by wanglinjiang** [openkraken/kraken#194]
如题，小白问，初始化了Vue项目，使用kraken运行起来，接下来如何打包应用为web端、iOS端、Android端。

**Comment by answershuto** [comment]
需要运行的环境集成 Kraken，具体见文档 http://openkraken.com/guide/native/interpolation-flutter

**Comment by andycall** [comment]
Kraken 没有做有关这块的事情，全部都用了 Flutter 现有的工具链

**Comment by andycall** [comment]
有兴趣可以去研究一下 Flutter 有关的工具链

https://flutter.dev/docs/deployment/android

https://flutter.dev/docs/deployment/ios

https://flutter.dev/docs/deployment/macos
