### ISSUE TITLE
如何使用本地图片

### ISSUE THREAD

**Issue by ruyadelaosan** [openkraken/kraken#195]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

master
### 重现步骤 ｜ Steps To Reproduce

执行build之后，使用cli工具加载bundle.js，报错找不到本地xxx图片
**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by andycall** [comment]
本地图片需要在构建的时候打包在 assets 才能够被访问到。

如何整合在 assets 里面：参考 Flutter 的用法 https://flutter.dev/docs/development/ui/assets-and-images

然后图片地址使用 `assets/your_image.png` 就可以访问到了

**Comment by andycall** [comment]
例如：

https://github.com/openkraken/gallery/blob/da5a89c2a12d7c5c1c889d7b57cc8f36481836ab/demos/gallery/src/pages/Home/index.jsx
https://github.com/openkraken/gallery/blob/main/pubspec.yaml#L71
