### ISSUE TITLE
希望文档加上用Angular开发Kraken应用

### ISSUE THREAD

**Issue by CrimsonHu** [openkraken/kraken#199]
## 使用场景 ｜ Use case

官网文档看到的三大框架是Rax，Vue，React，对此我是很震惊的

## 提案 ｜ Proposal

希望能加上Angular的示例

**Comment by andycall** [comment]
我印象中 Angular 是基于 HTML 构建的，至少 1.x 是这样，貌似 2.x 版本以后也是？？？
Kraken 现在还不支持 HTML，只支持 DOM API，所以支持 Angular 的难度不小，至少要等到 Kraken 支持 HTML 之后。

**Comment by wssgcg1213** [comment]
@CrimsonHu 可以帮忙提一个方案, Feel free to submit PR~

**Comment by yuanyan** [comment]
需要看下 angular 依赖了哪些 web 能力，目前项目组都没有使用 angular 的经验，@CrimsonHu 可以给一些信息

**Comment by yuanyan** [comment]
先关闭issue，有进一步讨论在reopen
