### ISSUE TITLE
when i run for web there are 1000s of error

### ISSUE THREAD

**Issue by abdulhamidalokzai** [openkraken/kraken#201]
Error: 'Pointer' isn't a type.
  DataElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                            ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/semantic
s_text.dart:141:30:
Error: 'Pointer' isn't a type.
  QuoteElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                             ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/semantic
s_text.dart:146:31:
Error: 'Pointer' isn't a type.
  StrongElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                              ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/semantic
s_text.dart:151:29:
Error: 'Pointer' isn't a type.
  TimeElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                            ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/semantic
s_text.dart:156:30:
Error: 'Pointer' isn't a type.
  SmallElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                             ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/semantic
s_text.dart:161:38:
Error: 'Pointer' isn't a type.
  StrikethroughElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                                     ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/semantic
s_text.dart:167:38:
Error: 'Pointer' isn't a type.
  UnarticulatedElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                                     ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/semantic
s_text.dart:172:33:
Error: 'Pointer' isn't a type.
  VariableElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                                ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/semantic
s_text.dart:177:29:
Error: 'Pointer' isn't a type.
  MarkElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                            ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:55:28:
Error: 'Pointer' isn't a type.
  DivElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                           ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:60:31:
Error: 'Pointer' isn't a type.
  FigureElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                              ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:65:38:
Error: 'Pointer' isn't a type.
  FigureCaptionElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                                     ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:70:39:
Error: 'Pointer' isn't a type.
  BlockQuotationElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager
  elementManager)
                                      ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:76:34:
Error: 'Pointer' isn't a type.
  ParagraphElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                                 ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:82:30:
Error: 'Pointer' isn't a type.
  UListElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                             ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:88:30:
Error: 'Pointer' isn't a type.
  OListElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                             ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:93:27:
Error: 'Pointer' isn't a type.
  LIElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                          ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:99:28:
Error: 'Pointer' isn't a type.
  PreElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                           ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:105:27:
Error: 'Pointer' isn't a type.
  DDElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                          ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:110:27:
Error: 'Pointer' isn't a type.
  DTElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                          ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/grouping
_content.dart:116:30:
Error: 'Pointer' isn't a type.
  DListElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                             ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/sections
.dart:32:32:
Error: 'Pointer' isn't a type.
  AddressElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                               ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/sections
.dart:37:32:
Error: 'Pointer' isn't a type.
  ArticleElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                               ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/sections
.dart:42:30:
Error: 'Pointer' isn't a type.
  AsideElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                             ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/sections
.dart:47:31:
Error: 'Pointer' isn't a type.
  FooterElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                              ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/sections
.dart:52:31:
Error: 'Pointer' isn't a type.
  HeaderElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                              ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/sections
.dart:57:29:
Error: 'Pointer' isn't a type.
  MainElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                            ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/sections
.dart:62:28:
Error: 'Pointer' isn't a type.
  NavElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                           ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/sections
.dart:67:32:
Error: 'Pointer' isn't a type.
  SectionElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                               ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/headings
.dart:55:27:
Error: 'Pointer' isn't a type.
  H1Element(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                          ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/headings
.dart:60:27:
Error: 'Pointer' isn't a type.
  H2Element(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                          ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/headings
.dart:65:27:
Error: 'Pointer' isn't a type.
  H3Element(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                          ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/headings
.dart:70:27:
Error: 'Pointer' isn't a type.
  H4Element(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                          ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/headings
.dart:75:27:
Error: 'Pointer' isn't a type.
  H5Element(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                          ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/headings
.dart:80:27:
Error: 'Pointer' isn't a type.
  H6Element(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                          ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/forms.da
rt:19:30:
Error: 'Pointer' isn't a type.
  LabelElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                             ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/forms.da
rt:24:31:
Error: 'Pointer' isn't a type.
  ButtonElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                              ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/edits.da
rt:24:28:
Error: 'Pointer' isn't a type.
  DelElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                           ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/edits.da
rt:29:28:
Error: 'Pointer' isn't a type.
  InsElement(int targetId, Pointer<NativeElement> nativePtr, ElementManager elementManager)
                           ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/a.dart:1
8:9:
Error: 'Pointer' isn't a type.
  final Pointer<NativeAnchorElement> nativeAnchorElement;
        ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/body.dar
t:16:74:
Error: 'Pointer' isn't a type.
  BodyElement(double viewportWidth, double viewportHeight, int targetId, Pointer<NativeElement>
  nativePtr, ElementManager elementManager)
                                                                         ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/canvas.d
art:23:15:
Error: 'NativeFunction' isn't a type.
final Pointer<NativeFunction<Native_CanvasGetContext>> nativeGetContext =
              ^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/canvas.d
art:23:7:
Error: 'Pointer' isn't a type.
final Pointer<NativeFunction<Native_CanvasGetContext>> nativeGetContext =
      ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/canvas.d
art:24:5:
Error: Getter not found: 'Pointer'.
    Pointer.fromFunction(CanvasElement._getContext);
    ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/canvas.d
art:47:52:
Error: 'Pointer' isn't a type.
  static CanvasElement getCanvasElementOfNativePtr(Pointer<NativeCanvasElement> nativeCanvasElement)
  {
                                                   ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/canvas.d
art:54:7:
Error: 'Pointer' isn't a type.
      Pointer<NativeCanvasElement> nativeCanvasElement, Pointer<NativeString> contextId) {
      ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/canvas.d
art:54:57:
Error: 'Pointer' isn't a type.
      Pointer<NativeCanvasElement> nativeCanvasElement, Pointer<NativeString> contextId) {
                                                        ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/canvas.d
art:60:9:
Error: 'Pointer' isn't a type.
  final Pointer<NativeCanvasElement> nativeCanvasElement;
        ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:29:15:
Error: 'NativeFunction' isn't a type.
final Pointer<NativeFunction<GetImageWidth>> nativeGetImageWidth =
Pointer.fromFunction(ImageElement.getImageWidth, 0.0);
              ^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:29:7:
Error: 'Pointer' isn't a type.
final Pointer<NativeFunction<GetImageWidth>> nativeGetImageWidth =
Pointer.fromFunction(ImageElement.getImageWidth, 0.0);
      ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:29:69:
Error: Getter not found: 'Pointer'.
final Pointer<NativeFunction<GetImageWidth>> nativeGetImageWidth =
Pointer.fromFunction(ImageElement.getImageWidth, 0.0);
                                                                    ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:30:15:
Error: 'NativeFunction' isn't a type.
final Pointer<NativeFunction<GetImageHeight>> nativeGetImageHeight =
Pointer.fromFunction(ImageElement.getImageHeight, 0.0);
              ^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:30:7:
Error: 'Pointer' isn't a type.
final Pointer<NativeFunction<GetImageHeight>> nativeGetImageHeight =
Pointer.fromFunction(ImageElement.getImageHeight, 0.0);
      ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:30:71:
Error: Getter not found: 'Pointer'.
final Pointer<NativeFunction<GetImageHeight>> nativeGetImageHeight =
Pointer.fromFunction(ImageElement.getImageHeight, 0.0);
                                                                      ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:31:15:
Error: 'NativeFunction' isn't a type.
final Pointer<NativeFunction<GetImageWidth>> nativeGetImageNaturalWidth =
Pointer.fromFunction(ImageElement.getImageNaturalWidth, 0.0);
              ^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:31:7:
Error: 'Pointer' isn't a type.
final Pointer<NativeFunction<GetImageWidth>> nativeGetImageNaturalWidth =
Pointer.fromFunction(ImageElement.getImageNaturalWidth, 0.0);
      ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:31:76:
Error: Getter not found: 'Pointer'.
final Pointer<NativeFunction<GetImageWidth>> nativeGetImageNaturalWidth =
Pointer.fromFunction(ImageElement.getImageNaturalWidth, 0.0);
                                                                           ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:32:15:
Error: 'NativeFunction' isn't a type.
final Pointer<NativeFunction<GetImageHeight>> nativeGetImageNaturalHeight =
Pointer.fromFunction(ImageElement.getImageNaturalHeight, 0.0);
              ^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:32:7:
Error: 'Pointer' isn't a type.
final Pointer<NativeFunction<GetImageHeight>> nativeGetImageNaturalHeight =
Pointer.fromFunction(ImageElement.getImageNaturalHeight, 0.0);
      ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:32:78:
Error: Getter not found: 'Pointer'.
final Pointer<NativeFunction<GetImageHeight>> nativeGetImageNaturalHeight =
Pointer.fromFunction(ImageElement.getImageNaturalHeight, 0.0);
                                                                             ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:55:45:
Error: 'Pointer' isn't a type.
  static Element getImageElementOfNativePtr(Pointer<NativeImgElement> nativeImageElement) {
                                            ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:61:31:
Error: 'Pointer' isn't a type.
  static double getImageWidth(Pointer<NativeImgElement> nativeImageElement) {
                              ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:66:32:
Error: 'Pointer' isn't a type.
  static double getImageHeight(Pointer<NativeImgElement> nativeImageElement) {
                               ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:72:38:
Error: 'Pointer' isn't a type.
  static double getImageNaturalWidth(Pointer<NativeImgElement> nativeImageElement) {
                                     ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:77:39:
Error: 'Pointer' isn't a type.
  static double getImageNaturalHeight(Pointer<NativeImgElement> nativeImageElement) {
                                      ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/img.dart
:82:9:
Error: 'Pointer' isn't a type.
  final Pointer<NativeImgElement> nativeImgElement;
        ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/input.da
rt:26:15:
Error: 'NativeFunction' isn't a type.
final Pointer<NativeFunction<GetInputWidth>> nativeGetInputWidth =
Pointer.fromFunction(InputElement.getInputWidth, 0.0);
              ^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/input.da
rt:26:7:
Error: 'Pointer' isn't a type.
final Pointer<NativeFunction<GetInputWidth>> nativeGetInputWidth =
Pointer.fromFunction(InputElement.getInputWidth, 0.0);
      ^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/kraken-0.7.1/lib/src/dom/elements/input.da
rt:26:68:
Error: Getter not found: 'Pointer'.
final Pointer<NativeFunction<GetInputWidth>> nativeGetInputWidth =
Pointer.fromFunction(InputElement.getInputWidth, 0.0);

**Comment by andycall** [comment]
flutter for web is not supported
