### ISSUE TITLE
kraken-0.7.1 build error

### ISSUE THREAD

**Issue by menchao** [openkraken/kraken#202]
../../../../../MyCode/FlutterDev/flutter/.pub-cache/hosted/pub.flutter-io.cn/kraken-0.7.1/lib/src/gesture/scroll_position_with_single_context.dart:37:7: Error: The non-abstract class 'ScrollPositionWithSingleContext' is missing implementations for these members:
     - ViewportOffset.hasPixels
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.

    class ScrollPositionWithSingleContext extends ScrollPosition implements ScrollActivityDelegate {
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by andycall** [comment]
0.7.1版本建议使用 flutter 1.22.4 版本编译

**Comment by wssgcg1213** [comment]
Flutter 版本目前支持 1.x 的最后一个 Stable 版本也就是 1.22.x
