### ISSUE TITLE
调试源码 xcode 报  could not find included file 'ephemeral/Flutter-Generated.xcconfig' in search paths

### ISSUE THREAD

**Issue by weixinjie** [openkraken/kraken#203]
问题：按照 https://openkraken.com/guide/contribute/development 文档调试 macos 代码(已重新构建了 bridge ) ，使用 xcode 运行 kraken/example/macos/Runner.xcworkspace 时报错 could not find included file 'ephemeral/Flutter-Generated.xcconfig' in search paths 

疑问点：已尝试使用在 example 目录下执行 flutter build macos 命令，但是 flutter 提示 "build macos" is not currently supported.

诉求：希望开发者帮看看是为什么报错

**Comment by wssgcg1213** [comment]
1. 确认下flutter版本 1.22.x stable
2. `flutter config --enable-macos-desktop` 打开 macos 支持

**Comment by weixinjie** [comment]
1. 现在的 flutter 版本为 1.22.0 
2. 已经打开了 flutter config --enable-macos-desktop 

flutter doctor 截图:
![image](https://user-images.githubusercontent.com/6205100/115810384-67a97680-a420-11eb-9dc0-b59d64bbbc0e.png)

flutter build macos 截图:
![image](https://user-images.githubusercontent.com/6205100/115810445-81e35480-a420-11eb-9238-ba2fe799963d.png)

**Comment by andycall** [comment]
flutter 需要从 github clone 执行，而不是下载官方的 stable 包。只有 flutter 2.0 提供的 stable 包才有 desktop 支持

**Comment by andycall** [comment]
xcode 抛出的异常是缺少一些构建依赖，这些依赖必须通过 flutter run -d macos 或者 flutter build macos 才能够生成出来

**Comment by weixinjie** [comment]
已解决  方案同步：
