### ISSUE TITLE
集成到Android 原生里 0.7.1用的预构建的 Android SDK 直接报错

### ISSUE THREAD

**Issue by zhaoqp2010** [openkraken/kraken#204]
io.flutter.embedding.engine.FlutterJNI.nativeAttach(Native Method)
--
2 io.flutter.embedding.engine.FlutterJNI.performNativeAttach(FlutterJNI.java:224)
3 io.flutter.embedding.engine.FlutterJNI.attachToNative(FlutterJNI.java:219)
4 io.flutter.embedding.engine.FlutterEngine.attachToJni(FlutterEngine.java:314)
5 io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:294)
6 io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:192)
7 io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:234)
8 io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:154)
9 io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)

**Comment by andycall** [comment]
还有一截关键的信息没有复制出来，现在确定不了问题

**Comment by wssgcg1213** [comment]
麻烦补充信息并 reopen
