### ISSUE TITLE
怎么编译到树莓派运行

### ISSUE THREAD

**Issue by 651016236** [openkraken/kraken#205]
iot低性能设备，直接使用树莓派这类低性能终端运行，看官方ppt中有介绍

**Comment by andycall** [comment]
这块主要是 Flutter 编译，可以参考这篇文章的内容

https://medium.com/flutter/flutter-on-raspberry-pi-mostly-from-scratch-2824c5e7dcb1

**Comment by 651016236** [comment]
> 这块主要是Flutter编译，可以参考这篇文章的内容
> 
> https://medium.com/flutter/flutter-on-raspberry-pi-mostly-from-scratch-2824c5e7dcb1

十分感谢
