### ISSUE TITLE
xcode 调试 bridge 失败

### ISSUE THREAD

**Issue by weixinjie** [openkraken/kraken#210]
前提：按照文档 https://openkraken.com/guide/contribute/development 调试 bridge 代码的教程执行后 使用 xcode 打开 macos 项目

问题：
1. 使用 edit schema -> release 启动时不会崩溃（bridge 代码中已按照文档添加了 assert(false)）
2. 使用 edit schema -> debug  启动就崩溃 截图如下
![image](https://user-images.githubusercontent.com/6205100/115877144-b2a3a800-a479-11eb-8dbc-50bd37792785.png)

**Comment by andycall** [comment]
这个是 flutter 的锅，release 和 debug 构建需要先 `flutter clean` 一下，然后再使用 `flutter run -d macos --debug` 重新生成依赖。
也就是说，只要是涉及 debug，profile，release 切换这些，都需要重复上诉步骤
