### ISSUE TITLE
可以加载打包到android_asset目录内的文件吗？

### ISSUE THREAD

**Issue by CarlTien** [openkraken/kraken#211]
把js bundle放到android assets目录下提示无法加载
flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Unable to load asset: file:///android_asset/app.js
    #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:225:7)
    <asynchronous suspension>
    #1      AssetsBundle.resolve (package:kraken/src/launcher/bundle.dart:171:38)
    #2      KrakenBundle.getBundle (package:kraken/src/launcher/bundle.dart:61:20)
    #3      KrakenController.loadBundle (package:kraken/src/launcher/controller.dart:655:36)
    <asynchronous suspension>
    #4      launch (package:kraken/src/launcher/launcher.dart:37:20)
    #5      main (package:kraken_sdk_module/main.dart:4:3)
    #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
    #7      _rootRun (dart:async/zone.dart:1190:13)
    #8      _CustomZone.run (dart:async/zone.dart:1093:19)
    #9      _runZoned (dart:async/zone.dart:1630:10)
    #10     runZonedGuarded (dart:async/zone.dart:1618:12)
    #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
    #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
    #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by CarlTien** [comment]
![image](https://user-images.githubusercontent.com/8737996/115993134-03470c80-a604-11eb-9385-d9d1b4f051c5.png)
实测这样可以加载assets目录下的js文件，哪位发现如何加载sdcard上的js文件方法的话辛苦贴一下

**Comment by wssgcg1213** [comment]
loadUrl 目前只支持了远程地址, 需要支持 `loadPath` 的功能

**Comment by wssgcg1213** [comment]
Widget 侧可以传入 bundlePath 来指定

**Comment by andycall** [comment]
现在可以用了临时办法：先读取 flutter assets 里面的文件，然后将纯文本传给 Kraken

https://flutter.dev/docs/development/ui/assets-and-images#loading-flutter-assets-in-android

**Comment by wssgcg1213** [comment]
1. Native API 支持 loadPath
2. bundlePath 目前仅支持 flutter assets, 不支持 local path (document)

Assign to myself.

**Comment by andycall** [comment]
移动到这里 https://github.com/openkraken/kraken/issues/232
