### ISSUE TITLE
npm run build:bridge:android报错error: cannot open crtbegin_dynamic.o: No such file or directory

### ISSUE THREAD

**Issue by Owenli0202** [openkraken/kraken#213]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
v0.7

### 重现步骤 ｜ Steps To Reproduce
npm run build:bridge:android

**预期结果 ｜ Expected results:** 
生成so文件

**实际结果 ｜ Actual results:** 

mac:kraken-0.7.1 lijianqing$ npm run build:bridge:android

> @ build:bridge:android /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1
> node scripts/build_android_so

npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> fsevents@1.2.13 install /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/polyfill/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN rollup-plugin-uglify@6.0.4 requires a peer of rollup@>=0.66.0 <2 but none is installed. You must install peer dependencies yourself.

added 882 packages from 443 contributors and audited 882 packages in 29.062s
found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> @ build /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/polyfill
> NODE_ENV=development rollup --config rollup.config.js && npm run mainToC && npm run testToC

src/index.ts → dist/main.js...
Created bundle main.js: 124.45 kB → 26.48 kB (gzip)
(!) Circular dependencies
src/kom/kraken.ts -> src/modules/method-channel.ts -> src/kom/kraken.ts
src/kom/kraken.ts -> src/modules/connection.ts -> src/kom/kraken.ts
src/modules/websocket.ts -> src/kom/kraken.ts -> src/modules/websocket.ts
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
created dist/main.js in 2.5s

src/test/index.js → dist/test.js...
Created bundle test.js: 254.19 kB → 50.68 kB (gzip)
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
created dist/test.js in 762ms

> @ mainToC /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/polyfill
> node scripts/js_to_c.js -s ../dist/main.js -o ../dist

> @ testToC /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/polyfill
> node scripts/js_to_c.js -s ../dist/test.js -o ../dist -n TestFramework

-- Android: Targeting API '16' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- Android: Selected unified Clang toolchain
-- The C compiler identification is Clang 12.0.4
-- The CXX compiler identification is Clang 12.0.4
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /Users/lijianqing/Library/Android/sdk/ndk/23.0.7272597/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/lijianqing/Library/Android/sdk/ndk/23.0.7272597/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - broken
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/Users/lijianqing/Library/Android/sdk/ndk/23.0.7272597/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/cmake-build-android-arm64-v8a/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_bf344/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_bf344.dir/build.make CMakeFiles/cmTC_bf344.dir/build
    Building C object CMakeFiles/cmTC_bf344.dir/testCCompiler.c.o
    /Users/lijianqing/Library/Android/sdk/ndk/23.0.7272597/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=aarch64-none-linux-android16 --sysroot=/Users/lijianqing/Library/Android/sdk/ndk/23.0.7272597/toolchains/llvm/prebuilt/darwin-x86_64/sysroot   -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions  -O2 -g -DNDEBUG -fPIE -MD -MT CMakeFiles/cmTC_bf344.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_bf344.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_bf344.dir/testCCompiler.c.o -c /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/cmake-build-android-arm64-v8a/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_bf344
    /Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTC_bf344.dir/link.txt --verbose=1
    /Users/lijianqing/Library/Android/sdk/ndk/23.0.7272597/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=aarch64-none-linux-android16 --sysroot=/Users/lijianqing/Library/Android/sdk/ndk/23.0.7272597/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions  -O2 -g -DNDEBUG -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Qunused-arguments -Wl,--no-undefined  -Wl,--gc-sections  CMakeFiles/cmTC_bf344.dir/testCCompiler.c.o -o cmTC_bf344   -latomic -lm 
    ld: error: cannot open crtbegin_dynamic.o: No such file or directory
    ld: error: cannot open crtend_android.o: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_bf344] Error 1
    make: *** [cmTC_bf344/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/cmake-build-android-arm64-v8a/CMakeFiles/CMakeOutput.log".
See also "/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/cmake-build-android-arm64-v8a/CMakeFiles/CMakeError.log".
/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 2,
  name: 'build-android-kraken-lib',
  branch: false,
  error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=/Users/lijianqing/Library/Android/sdk/ndk/23.0.7272597/build/cmake/android.toolchain.cmake     -DANDROID_NDK=/Users/lijianqing/Library/Android/sdk/ndk/23.0.7272597     -DIS_ANDROID=TRUE     -DANDROID_ABI="arm64-v8a"     \
      -DANDROID_PLATFORM="android-16"     -DANDROID_STL=c++_shared     -G "Unix Makefiles"     -B /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/cmake-build-android-arm64-v8a -S /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge
      at checkExecSyncError (child_process.js:631:11)
      at execSync (child_process.js:668:15)
      at /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/scripts/tasks.js:418:5
      at Array.forEach (<anonymous>)
      at /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/scripts/tasks.js:414:9
      at taskWrapper (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/undertaker/lib/set-task.js:13:15)
      at bound (domain.js:415:14)
      at runBound (domain.js:428:12)
      at asyncRunner (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/async-done/index.js:55:18)
      at processTicksAndRejections (internal/process/task_queues.js:81:9) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 1167,
    stdout: null,
    stderr: null,
    domainThrown: true
  },
  duration: [ 1, 254921002 ],
  time: 1619245254261
})
    at Gulp.emit (events.js:185:17)
    at Gulp.EventEmitter.emit (domain.js:471:20)
    at Object.error (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/once/once.js:25:25)
    at f (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/once/once.js:25:25)
    at tryCatch (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/async-done/index.js:24:15)
    at done (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/async-done/index.js:40:12)
    at Domain.onError (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/async-done/index.js:51:5)
    at Object.onceWrapper (events.js:284:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:bridge:android: `node scripts/build_android_so`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:bridge:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lijianqing/.npm/_logs/2021-04-24T06_20_54_272Z-debug.log

**Comment by Owenli0202** [comment]
node 版本12.0.0
cmake 3.20.1
ndk 23.0.7272597

**Comment by andycall** [comment]
ndk toolchains 初始化报错了，估计是ndk的问题，可以试一下 ndk 20 版本

**Comment by Owenli0202** [comment]
> ndk toolchains 初始化报错了，估计是ndk的问题，可以试一下 ndk 20 版本

cmake 改为3.6.0-rc2
ndk 改为20.0.5594570 后依然报错


> @ build:bridge:android /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1
> node scripts/build_android_so

npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> fsevents@1.2.13 install /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/polyfill/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN rollup-plugin-uglify@6.0.4 requires a peer of rollup@>=0.66.0 <2 but none is installed. You must install peer dependencies yourself.

added 882 packages from 443 contributors and audited 882 packages in 27.02s
found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> @ build /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/polyfill
> NODE_ENV=development rollup --config rollup.config.js && npm run mainToC && npm run testToC


src/index.ts → dist/main.js...
Created bundle main.js: 124.45 kB → 26.48 kB (gzip)
(!) Circular dependencies
src/kom/kraken.ts -> src/modules/method-channel.ts -> src/kom/kraken.ts
src/kom/kraken.ts -> src/modules/connection.ts -> src/kom/kraken.ts
src/modules/websocket.ts -> src/kom/kraken.ts -> src/modules/websocket.ts
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
created dist/main.js in 2.5s

src/test/index.js → dist/test.js...
Created bundle test.js: 254.19 kB → 50.68 kB (gzip)
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
created dist/test.js in 771ms

> @ mainToC /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/polyfill
> node scripts/js_to_c.js -s ../dist/main.js -o ../dist


> @ testToC /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/polyfill
> node scripts/js_to_c.js -s ../dist/test.js -o ../dist -n TestFramework

-- Check for working C compiler: /Users/lijianqing/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/lijianqing/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/lijianqing/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Check for working CXX compiler: /Users/lijianqing/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
fatal: not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:232 (string):
  string sub-command REPLACE requires at least four arguments.


-- Configuring incomplete, errors occurred!
See also "/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/CMakeFiles/CMakeOutput.log".
/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 2,
  name: 'build-android-kraken-lib',
  branch: false,
  error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=/Users/lijianqing/Library/Android/sdk/ndk/20.0.5594570/build/cmake/android.toolchain.cmake     -DANDROID_NDK=/Users/lijianqing/Library/Android/sdk/ndk/20.0.5594570     -DIS_ANDROID=TRUE     -DANDROID_ABI="arm64-v8a"     \
      -DANDROID_PLATFORM="android-16"     -DANDROID_STL=c++_shared     -G "Unix Makefiles"     -B /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge/cmake-build-android-arm64-v8a -S /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/bridge
      at checkExecSyncError (child_process.js:631:11)
      at execSync (child_process.js:668:15)
      at /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/scripts/tasks.js:418:5
      at Array.forEach (<anonymous>)
      at /Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/scripts/tasks.js:414:9
      at taskWrapper (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/undertaker/lib/set-task.js:13:15)
      at bound (domain.js:415:14)
      at runBound (domain.js:428:12)
      at asyncRunner (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/async-done/index.js:55:18)
      at processTicksAndRejections (internal/process/task_queues.js:81:9) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 1737,
    stdout: null,
    stderr: null,
    domainThrown: true
  },
  duration: [ 1, 754123412 ],
  time: 1619319955146
})
    at Gulp.emit (events.js:185:17)
    at Gulp.EventEmitter.emit (domain.js:471:20)
    at Object.error (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/once/once.js:25:25)
    at f (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/once/once.js:25:25)
    at tryCatch (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/async-done/index.js:24:15)
    at done (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/async-done/index.js:40:12)
    at Domain.onError (/Users/lijianqing/Documents/work/android/opensource/kraken-0.7.1/node_modules/async-done/index.js:51:5)
    at Object.onceWrapper (events.js:284:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:bridge:android: `node scripts/build_android_so`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:bridge:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lijianqing/.npm/_logs/2021-04-25T03_05_55_157Z-debug.log
mac:kraken-0.7.1 lijianqing$ cmake --version
cmake version 3.6.0-rc2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by wssgcg1213** [comment]
我这边本地的环境 cmake 3.17.x, ndk 20.0.5594570

**Comment by OwenliNew** [comment]
> 我这边本地的环境 cmake 3.17.x, ndk 20.0.5594570

你那边可以的吗？

**Comment by andycall** [comment]
cmake 需要 3.10 以上版本

**Comment by Owenli0202** [comment]
> cmake 需要 3.10 以上版本

cmake 3.10 3.18 都试过了，还是不行，cmake我是在Android studio中的sdk tools中安装的，不知道安装完之后还要做什么配置吗？
下面是我的报错日志

mac:kraken-main lijianqing$ node --version
v12.0.0
mac:kraken-main lijianqing$ cmake --version
cmake version 3.18.1-g262b901

CMake suite maintained and supported by Kitware (kitware.com/cmake).
mac:kraken-main lijianqing$ npm run build:bridge:android

> @ build:bridge:android /Users/lijianqing/Documents/work/android/opensource/kraken-main
> node scripts/build_android_so

npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> fsevents@1.2.13 install /Users/lijianqing/Documents/work/android/opensource/kraken-main/bridge/polyfill/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN rollup-plugin-uglify@6.0.4 requires a peer of rollup@>=0.66.0 <2 but none is installed. You must install peer dependencies yourself.

added 882 packages from 443 contributors and audited 882 packages in 27.895s
found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> @ build /Users/lijianqing/Documents/work/android/opensource/kraken-main/bridge/polyfill
> NODE_ENV=development rollup --config rollup.config.js && npm run mainToC && npm run testToC


src/index.ts → dist/main.js...
Created bundle main.js: 124.45 kB → 26.48 kB (gzip)
(!) Circular dependencies
src/kom/kraken.ts -> src/modules/method-channel.ts -> src/kom/kraken.ts
src/kom/kraken.ts -> src/modules/connection.ts -> src/kom/kraken.ts
src/modules/websocket.ts -> src/kom/kraken.ts -> src/modules/websocket.ts
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
created dist/main.js in 2.8s

src/test/index.js → dist/test.js...
Created bundle test.js: 255.76 kB → 51.36 kB (gzip)
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
created dist/test.js in 948ms

> @ mainToC /Users/lijianqing/Documents/work/android/opensource/kraken-main/bridge/polyfill
> node scripts/js_to_c.js -s ../dist/main.js -o ../dist


> @ testToC /Users/lijianqing/Documents/work/android/opensource/kraken-main/bridge/polyfill
> node scripts/js_to_c.js -s ../dist/test.js -o ../dist -n TestFramework

-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/lijianqing/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/lijianqing/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
fatal: not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:232 (string):
  string sub-command REPLACE requires at least four arguments.


-- Configuring incomplete, errors occurred!
See also "/Users/lijianqing/Documents/work/android/opensource/kraken-main/bridge/cmake-build-android-arm64-v8a/CMakeFiles/CMakeOutput.log".
/Users/lijianqing/Documents/work/android/opensource/kraken-main/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 2,
  name: 'build-android-kraken-lib',
  branch: false,
  error: Error: Command failed: cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=/Users/lijianqing/Library/Android/sdk/ndk/20.0.5594570/build/cmake/android.toolchain.cmake     -DANDROID_NDK=/Users/lijianqing/Library/Android/sdk/ndk/20.0.5594570     -DIS_ANDROID=TRUE     -DANDROID_ABI="arm64-v8a"     \
      -DANDROID_PLATFORM="android-16"     -DANDROID_STL=c++_shared     -G "Unix Makefiles"     -B /Users/lijianqing/Documents/work/android/opensource/kraken-main/bridge/cmake-build-android-arm64-v8a -S /Users/lijianqing/Documents/work/android/opensource/kraken-main/bridge
      at checkExecSyncError (child_process.js:631:11)
      at execSync (child_process.js:668:15)
      at /Users/lijianqing/Documents/work/android/opensource/kraken-main/scripts/tasks.js:402:5
      at Array.forEach (<anonymous>)
      at /Users/lijianqing/Documents/work/android/opensource/kraken-main/scripts/tasks.js:398:9
      at taskWrapper (/Users/lijianqing/Documents/work/android/opensource/kraken-main/node_modules/undertaker/lib/set-task.js:13:15)
      at bound (domain.js:415:14)
      at runBound (domain.js:428:12)
      at asyncRunner (/Users/lijianqing/Documents/work/android/opensource/kraken-main/node_modules/async-done/index.js:55:18)
      at processTicksAndRejections (internal/process/task_queues.js:81:9) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 2042,
    stdout: null,
    stderr: null,
    domainThrown: true
  },
  duration: [ 0, 434063023 ],
  time: 1619406211787
})
    at Gulp.emit (events.js:185:17)
    at Gulp.EventEmitter.emit (domain.js:471:20)
    at Object.error (/Users/lijianqing/Documents/work/android/opensource/kraken-main/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/lijianqing/Documents/work/android/opensource/kraken-main/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/lijianqing/Documents/work/android/opensource/kraken-main/node_modules/once/once.js:25:25)
    at f (/Users/lijianqing/Documents/work/android/opensource/kraken-main/node_modules/once/once.js:25:25)
    at tryCatch (/Users/lijianqing/Documents/work/android/opensource/kraken-main/node_modules/async-done/index.js:24:15)
    at done (/Users/lijianqing/Documents/work/android/opensource/kraken-main/node_modules/async-done/index.js:40:12)
    at Domain.onError (/Users/lijianqing/Documents/work/android/opensource/kraken-main/node_modules/async-done/index.js:51:5)
    at Object.onceWrapper (events.js:284:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:bridge:android: `node scripts/build_android_so`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:bridge:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lijianqing/.npm/_logs/2021-04-26T03_03_31_798Z-debug.log

**Comment by andycall** [comment]
问题出在这里， 是 cmake 执行 git 命令出了问题。

```
execute_process(
  COMMAND git rev-parse --short HEAD
  WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_HEAD
)
string(REPLACE \n "" GIT_HEAD ${GIT_HEAD}) # Remove last \n
```

这里有行关键的错误日志，你是不是直接下载的 zip bundle 编译的，这样是不行的，需要使用 git clone 下来的版本进行构建，因为依赖 git 仓库信息。
```
fatal: not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:232 (string):
string sub-command REPLACE requires at least four arguments.
```

**Comment by Owenli0202** [comment]
> 问题出在这里， 是 cmake 执行 git 命令出了问题。
> 
> ```
> execute_process(
>   COMMAND git rev-parse --short HEAD
>   WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
>   OUTPUT_VARIABLE GIT_HEAD
> )
> string(REPLACE \n "" GIT_HEAD ${GIT_HEAD}) # Remove last \n
> ```
> 
> 这里有行关键的错误日志，你是不是直接下载的 zip bundle 编译的，这样是不行的，需要使用 git clone 下来的版本进行构建，因为依赖 git 仓库信息。
> 
> ```
> fatal: not a git repository (or any of the parent directories): .git
> CMake Error at CMakeLists.txt:232 (string):
> string sub-command REPLACE requires at least four arguments.
> ```

哇~就是这个问题，可以编译通过了，太感谢了~
