### ISSUE TITLE
无法启动demo

### ISSUE THREAD

**Issue by brizer** [openkraken/kraken#216]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

master

### 重现步骤 ｜ Steps To Reproduce

``` 
git clone https://github.com/openkraken/samples.git
cd /demo/hello-react
npm i
npm run build
kraken ./build/static/js/bundle.js
```

**重现代码 | Code example:** 

```
flutter: Observatory listening on http://127.0.0.1:54625/1AJhDbuSws4=/
dyld: lazy symbol binding failed: Symbol not found: _objc_alloc_initor Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_alloc_init
  Expected in: /usr/lib/libobjc.A.dylib
```
**预期结果 ｜ Expected results:** 

正确启动

**实际结果 ｜ Actual results:** 

无法正确启动

**Comment by answershuto** [comment]
我试了一下没有问题可以起起来的，有什么报错或者更多信息吗？

**Comment by wssgcg1213** [comment]
貌似跟系统版本有关? 尝试找一个10.15系统复现看看

**Comment by Yumwey** [comment]
一样的问题. 

系统版本： OSX Mojave 10.14

**Comment by brizer** [comment]
> 貌似跟系统版本有关? 尝试找一个10.15系统复现看看

我就是10.15，也是醉了。demo开始第一步就跪了。跨端坑多果然名不虚传。

**Comment by andycall** [comment]
> > 貌似跟系统版本有关? 尝试找一个10.15系统复现看看
> 
> 我就是10.15，也是醉了。demo开始第一步就跪了。跨端坑多果然名不虚传。

跨端技术是客户端领域的技术，客户端坑比前端多那是必然的，iOS，Android 开发每天都会遇到各种编译构建问题，这和环境复杂性有关，JS 引擎抹平平台差异后，复杂就少了很多。

**Comment by andycall** [comment]
是 kraken cli 集成 jsc 的问题，我待会重新发布一个新的 patch 版本

**Comment by brizer** [comment]
> 是 kraken cli 集成 jsc 的问题，我待会重新发布一个新的 patch 版本

改好了吗？兄弟

**Comment by andycall** [comment]
已经在 0.7.3 版本的 cli 中修复
