### ISSUE TITLE
按照文档集成到现有 iOS 应用时报错！

### ISSUE THREAD

**Issue by rzshuo** [openkraken/kraken#219]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

v0.7.1

### 重现步骤 ｜ Steps To Reproduce

<img width="1836" alt="WX20210425-165019@2x" src="https://user-images.githubusercontent.com/57256049/115987143-58742580-a5e6-11eb-9cba-b57d73aa80fe.png">

**重现代码 | Code example:** 
我是按照文档一步一步创建的项目，Xcode12.4
[test2021.zip](https://github.com/openkraken/kraken/files/6371583/test2021.zip)

**预期结果 ｜ Expected results:** 
运行起来

**实际结果 ｜ Actual results:** 
报错

**Comment by yuanyan** [comment]
点击报错有更详细的日志吗？

**Comment by wssgcg1213** [comment]
看一下你的项目类型是否选择了 universal 类型 (iOS/iPad/macOS), 选择 iOS 就可以了   
如果有更多细节补充可以 reopen

**Comment by rzshuo** [comment]
@wssgcg1213 只选择的iOS
<img width="1836" alt="WX20210426-085600@2x" src="https://user-images.githubusercontent.com/57256049/116015931-a08a5b00-a66d-11eb-82bd-2756dc279b68.png">

**Comment by rzshuo** [comment]
我这个项目就是Create a new Xcode project开始的，用的Xcode12.4，系统11.2.3

**Comment by rzshuo** [comment]
@yuanyan  这是项目代码，没啥其他提示，就是报错
[https://github.com/openkraken/kraken/files/6371583/test2021.zip](url)

**Comment by rzshuo** [comment]
@yuanyan @wssgcg1213 我录了下屏你们可以看看，操作就是按照你们文档来的。
[https://b23.tv/b41rYl](url)

**Comment by airingursb** [comment]
Xcode 12.3 以上版本的问题，改下配置可以编过
![image](https://user-images.githubusercontent.com/10513408/116090409-699c5f80-a6d6-11eb-8200-35aef6cc8c74.png)


@rzshuo

**Comment by rzshuo** [comment]
@airingursb 报ld: framework not found FlutterPluginRegistrant
