### ISSUE TITLE
请问下，你们自研的这个web渲染引擎，Google会不会禁止使用？

### ISSUE THREAD

**Issue by nmhuang** [openkraken/kraken#223]
因为Google为了防止其它引擎会拦截敏感信息，从而禁止使用第三方引擎，比如Google已经明确禁止腾讯X5

**Comment by yuanyan** [comment]
Kraken 不是浏览器，没有拦截敏感信息的能力

**Comment by yjhenan** [comment]
`Google已经明确禁止腾讯X5`
哪看到的，有链接吗？

**Comment by lycool** [comment]
https://x5.tencent.com/docs/questions.html
1.11 TBS 是否支持海外版本app 使用？
为了减少您的apk包大小增量，及时动态发版解决安全隐患，TBS SDK采用了后台动态下发内核的方案。由于Google Play 禁止任何二进制代码的下发（包括so、dex、jar）和插件化技术的使用，故使用X5 内核的app不支持在海外Google Play上架。

如果您有多渠道打包能力，您可以在海外版本接入仅保留接口的SDK，保证编译通过，仅使用系统webview，在其他渠道使用标准SDK版本以便正常使用X5能力

"比如Google已经明确禁止腾讯X5" 这个说法应该是不正确的

**Comment by wssgcg1213** [comment]
如果 Google 禁用了 Flutter, 那么 Kraken 也就无法使用了~
政策的外部因素不在这里讨论, 大家如果有更多已知的明确的信息也可以同步~
