### ISSUE TITLE
建议增加url资源加载过程事件上报、错误消息上报

### ISSUE THREAD

**Issue by iammsun** [openkraken/kraken#227]
使用场景 ｜ Use case
类似 Android WebView 的 onPageStart、onPageFinish、onReceiveError，用于对 WebView 中加载的资源状态显示

https://developer.android.com/reference/android/webkit/WebViewClient#onPageStarted(android.webkit.WebView,%20java.lang.String,%20android.graphics.Bitmap)

https://developer.android.com/reference/android/webkit/WebViewClient#onPageFinished(android.webkit.WebView,%20java.lang.String)

https://developer.android.com/reference/android/webkit/WebViewClient#onReceivedError(android.webkit.WebView,%20android.webkit.WebResourceRequest,%20android.webkit.WebResourceError)

**Comment by wssgcg1213** [comment]
@iammsun 可否给出给详细的设计提案

**Comment by iammsun** [comment]
目前kraken支持onLoad、onLoadError拦截页面加载完成、加载错误消息，可先忽略这个提案
