### ISSUE TITLE
Boost warm up by jsc/quickjs snapshot

### ISSUE THREAD

**Issue by yuanyan** [openkraken/kraken#23]
1. 优先考虑 android 的 jsc 是不是有机会支持 bytecode，ios 下放弃支持 bytecode
2. 如果 1 不可行考虑支持 quickjs 引擎，同时做到 android/ios 两边引擎对齐

**Comment by cnryb** [comment]
看样子是 Android 下的 JSC 没法支持 bytecode 吗？
