### ISSUE TITLE
运行vue项目报错

### ISSUE THREAD

**Issue by chenyulun** [openkraken/kraken#230]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

```shell
kraken -V
0.7.2
```

### 重现步骤 ｜ Steps To Reproduce

按照官方文档提供的vue demo
`cd demos/hello-vue`
`yarn`
这个时候安装的vue版本是`3.0.11`
然后运行`yarn build`
```shell
$ kraken ./dist/js/app.js
Execute binary: /Users/myusername/.npm-global/lib/node_modules/@openkraken/cli/build/darwin/debug/app.app/Contents/MacOS/app 

flutter: Observatory listening on http://127.0.0.1:51933/TuOa5GAW2_4=/
Can't find variable: SVGElement
/Users/myusername/github/samples/demos/hello-vue/dist/js/app.js:10140:78
56d7@/Users/myusername/github/samples/demos/hello-vue/dist/js/app.js:1184:110
__webpack_require__@/Users/myusername/github/samples/demos/hello-vue/dist/js/app.js:20:34
/Users/myusername/github/samples/demos/hello-vue/dist/js/app.js:97:37
__webpack_require__@/Users/myusername/github/samples/demos/hello-vue/dist/js/app.js:20:34
/Users/myusername/github/samples/demos/hello-vue/dist/js/app.js:84:37
global code@/Users/myusername/github/samples/demos/hello-vue/dist/js/app.js:85:12

flutter: ERROR: unexpected element type "SCRIPT"
flutter: Kraken DevTool listening at ws://22.17.157.113:9222
flutter: Open Chrome/Edge and paste following url to your navigator:
flutter:     devtools://devtools/bundled/inspector.html?ws=22.17.157.113:9222
```
这个版本的vue里面有一个段这样的代码,createApp函数有问题
```js
const createApp = ((...args) => {
    const app = ensureRenderer().createApp(...args);
    if ((false)) {}
    const { mount } = app;
    app.mount = (containerOrSelector) => {
        const container = normalizeContainer(containerOrSelector);
        if (!container)
            return;
        const component = app._component;
        if (!Object(_vue_shared__WEBPACK_IMPORTED_MODULE_1__["isFunction"])(component) && !component.render && !component.template) {
            component.template = container.innerHTML;
        }
        // clear content before mounting
        container.innerHTML = '';
        const proxy = mount(container, false, container instanceof SVGElement);
        if (container instanceof Element) {
            container.removeAttribute('v-cloak');
            container.setAttribute('data-v-app', '');
        }
        return proxy;
    };
    return app;
});
```
导致的

**重现代码 | Code example:** 
github地址就是官方提供的`https://github.com/openkraken/samples.git`

**预期结果 ｜ Expected results:** 
能正常屏蔽`SVGElement`对象

**实际结果 ｜ Actual results:** 
实际效果报了`Can't find variable: SVGElement`

**Comment by andycall** [comment]
svg现在还没有支持，@answershuto 你当时运行起来的vue是哪个版本？

**Comment by answershuto** [comment]
看起来是 svg 没实现

**Comment by answershuto** [comment]
先用 Vue 版本 3.0.7 吧，这个我们处理一下。

**Comment by chenyulun** [comment]
我同事用cnpm安装的使用3.0.7打包出来的createApp函数就没有这句话，
我使用的是yarn安装的3.0.11,先告诉我怎么mock掉他

**Comment by answershuto** [comment]
package.json 写死版本就好

**Comment by chenyulun** [comment]
也有其他的问题，不用管吗
```shell
flutter: ERROR: unexpected element type "SCRIPT"
flutter: NoSuchMethodError: The method 'send' was called on null.
Receiver: null
Tried calling: send(Instance of 'DOMUpdatedEvent')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      UIInspector.onDOMTreeChanged (package:kraken/src/inspector/ui_inspector.dart:101:38)
#2      ElementManager._debugDOMTreeChanged (package:kraken/src/dom/element_manager.dart:486:26)
#3      ElementManager.insertAdjacentNode (package:kraken/src/dom/element_manager.dart:380:5)
#4      KrakenViewController.insertAdjacentNode (package:kraken/src/launcher/controller.dart:320:21)
#5      flushUICommand (package:kraken/src/bridge/to_native.dart:393:29)
#6      initBridge.<anonymous closure>.<anonymous closure> (package:kraken/src/bridge/bridge.dart:40:9)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
#10     _rootRun (dart:async/zone.dart:1190:13)
#11     _CustomZone.run (dart:async/zone.dart:1093:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#13     _invoke (dart:ui/hooks.dart:251:10)
#14     _drawFrame (dart:ui/hooks.dart:209:3)
```

**Comment by andycall** [comment]
> 也有其他的问题，不用管吗
> 
> ```shell
> flutter: ERROR: unexpected element type "SCRIPT"
> flutter: NoSuchMethodError: The method 'send' was called on null.
> Receiver: null
> Tried calling: send(Instance of 'DOMUpdatedEvent')
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> #1      UIInspector.onDOMTreeChanged (package:kraken/src/inspector/ui_inspector.dart:101:38)
> #2      ElementManager._debugDOMTreeChanged (package:kraken/src/dom/element_manager.dart:486:26)
> #3      ElementManager.insertAdjacentNode (package:kraken/src/dom/element_manager.dart:380:5)
> #4      KrakenViewController.insertAdjacentNode (package:kraken/src/launcher/controller.dart:320:21)
> #5      flushUICommand (package:kraken/src/bridge/to_native.dart:393:29)
> #6      initBridge.<anonymous closure>.<anonymous closure> (package:kraken/src/bridge/bridge.dart:40:9)
> #7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
> #8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
> #9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
> #10     _rootRun (dart:async/zone.dart:1190:13)
> #11     _CustomZone.run (dart:async/zone.dart:1093:19)
> #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> #13     _invoke (dart:ui/hooks.dart:251:10)
> #14     _drawFrame (dart:ui/hooks.dart:209:3)
> ```

诶，怎么还有报错，我在另外一个 Issue 也看到过类似的情况。我看下是为啥

**Comment by wssgcg1213** [comment]
To #237
