### ISSUE TITLE
Kraken集成到APP内是否可以加载本地Vue应用？

### ISSUE THREAD

**Issue by LvzcThrash** [openkraken/kraken#231]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

ios.sdk.0.7.1

### 重现步骤 ｜ Steps To Reproduce

使用官方的demo通过npm run build，生成了dist目录下的应用，通过kraken ./dist/js/app.js 可以运行起来应用；
但是在iOS APP内集成了应用，可以通过[kraken loadUrl:@"http://kraken.oss-cn-hangzhou.aliyuncs.com/demo/guide-animation.js"]; 唤起flutter应用，但是好像没有api可以加载本地的app.js；

**重现代码 | Code example:** 
success:
Kraken* kraken = [[Kraken alloc] initWithFlutterEngine:flutterEngine];
[kraken loadUrl:@"http://kraken.oss-cn-hangzhou.aliyuncs.com/demo/guide-animation.js"];
failed:
Kraken* kraken = [[Kraken alloc] initWithFlutterEngine:flutterEngine];
[kraken loadUrl:@"file:///xxxx/demo/app.js"];

**预期结果 ｜ Expected results:** 
可以加载本地编译ok的应用

**实际结果 ｜ Actual results:** 
在app内打开白屏

**Comment by yuanyan** [comment]
本地资源需要在 flutter yml 文件中配置 assets

**Comment by andycall** [comment]
Objective-C 那边的 API 还没有提供加载本地文件的功能

https://github.com/openkraken/kraken/issues/232

**Comment by super-chao** [comment]
> Objective-C 那边的 API 还没有提供加载本地文件的功能
> 
> #232

android的就有了？我android试了也没用还是白屏

**Comment by andycall** [comment]
Java 也没有支持，现在只有 Dart API 支持这个功能。

**Comment by andycall** [comment]
移动到这里 https://github.com/openkraken/kraken/issues/232
