### ISSUE TITLE
React Demo 改 ts 之后运行白屏

### ISSUE THREAD

**Issue by airingursb** [openkraken/kraken#233]
### 重现步骤 ｜ Steps To Reproduce

App.js 与 index.js 直接改 tsx，补上 tsconfig.json，npm run start 发现 web 是正常显示的，但是 kraken 是白屏。

**重现代码 | Code example:** 

tsconfig.js
```json
{
    "compilerOptions": {
        "outDir": "./build/",
        "noImplicitAny": true,
        "module": "es6",
        "target": "es5",
        "jsx": "react",
        "allowJs": true,
        "moduleResolution": "node",
        "esModuleInterop": true,
    }
}
```

**Comment by andycall** [comment]
有错误日志吗？

**Comment by airingursb** [comment]
@andycall 
dev 服务没有起起来，日志如下

```
flutter: Observatory listening on http://127.0.0.1:63511/EkK-XGzMDXo=/
flutter: NoSuchMethodError: The method 'send' was called on null.
Receiver: null
Tried calling: send(Instance of 'DOMUpdatedEvent')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      UIInspector.onDOMTreeChanged (package:kraken/src/inspector/ui_inspector.dart:101:38)
#2      ElementManager._debugDOMTreeChanged (package:kraken/src/dom/element_manager.dart:486:26)
#3      ElementManager.insertAdjacentNode (package:kraken/src/dom/element_manager.dart:380:5)
#4      KrakenViewController.insertAdjacentNode (package:kraken/src/launcher/controller.dart:320:21)
#5      flushUICommand (package:kraken/src/bridge/to_native.dart:393:29)
```

另外，`DOMUpdatedEvent` 这个 error 在给的 react demo 里也有这个报错，虽然能跑起来，但是疯狂报错。。
我的 Flutter 版本是 2.0.5

**Comment by andycall** [comment]
flutter 2.x 版本没有任何测试过，不清楚是不是 flutter 2.0 的问题。使用 1.22.4 版本的 flutter 应该是可以正常工作的。

> 我们计划在 5月底支持 flutter 2.0

**Comment by airingursb** [comment]
好的，我降级一下试试看

**Comment by airingursb** [comment]
1.22.4 也是一样的，并不行，我猜测是 babel 的时候出了问题，可否发一下没问题的 tsconfig 看一下？

**Comment by andycall** [comment]
还没有试过，我先试试看

**Comment by airingursb** [comment]
恩，麻烦看一下这个问题，我们想做同构，h5 目前都是 tsx

**Comment by wssgcg1213** [comment]
Will continue at #237

**Comment by airingursb** [comment]
这里调试了一下找到原因了

改 tsx 之后我注释掉了一个 flexDirection 样式，因为本身 dom.style 的声明没有这个字段，所以我去掉了方便通过构建，因此 h5 这里理想情况是横排。但是北海渲染时，横排的元素如果超出了屏幕的宽度，就直接白屏了。

我进源码断点看了下，这种情况下 `evaluateScripts` 内走到后面某个 element 的 `insertAdjacentNode` 时就直接挂掉了，但是没有被任何 catch 捕获住，直接挂掉。估计 flutter 渲染会红屏提示 ui 错误，希望这种情况能够把 ui 布局错误透传给业务侧。 @andycall

**Comment by andycall** [comment]
可以提供一份前端的代码吗？

**Comment by airingursb** [comment]
官方示例提供的 react demo，去掉 style.AppHeader 中的 ‘flexDirection’ 样式即可复现。去掉之后默认为 row 横向布局，就会导致 element 总宽度超出屏幕，然后就白屏了。 @andycall
