### ISSUE TITLE
kraken.loadUrl()多次执行，未成功

### ISSUE THREAD

**Issue by qiaoyhh** [openkraken/kraken#234]
## 使用场景 ｜ Use case
kraken version:0.7.1

Android Nativit端与前端互相跳转页面
目前Android端跳转前端：
`Kraken kraken = new Kraken(engine);
  kraken.loadUrl(“url");`

我想在多个页面执行多次执行loadUrl方法，经过多次尝试均未成功，请问这种需求目前框架支持么

## 提案 ｜ Proposal
类似于Flutter_boost那样，可以随意在Android端跳转Flutter

**Comment by andycall** [comment]
Java/OC API 还没有支持这个功能。现阶段可以用 Dart API，然后通过 Flutter Boost 对接到

**Comment by wssgcg1213** [comment]
redirect #280
