### ISSUE TITLE
Android端使用kraken SDK release包加载页面黑屏

### ISSUE THREAD

**Issue by xiaodb123** [openkraken/kraken#235]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.7.1

### 重现步骤 ｜ Steps To Reproduce

在Android真机上，debug包可以正常加载，release包则黑屏

**重现代码 | Code example:** 
public class JumpTestActivity extends FlutterActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        FlutterEngine engine = getFlutterEngine();
        if (engine == null) return;
        Kraken kraken = new Kraken(engine);
        String url = "https://raw.githubusercontent.com/openkraken/kraken/main/kraken/example/assets/bundle.js";
        kraken.loadUrl(url);
    }
}

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by andycall** [comment]
SDK API 之前一直投入不多，没想到这么多人用。可以先用 Widget API，和 Flutter 应用一块构建进行一些测试。

待我们修好了这个问题再使用 SDK 集成的方式

**Comment by xiaodb123** [comment]
> SDK API 之前一直投入不多，没想到这么多人用。可以先用 Widget API，和 Flutter 应用一块构建进行一些测试。
> 
> 待我们修好了这个问题再使用 SDK 集成的方式

想请教一下目前SDK集成方式和Flutter集成方式相比，主要的差别都有哪些，两种方式在对外提供的功能上是对齐的吗？后续的支持上以那种方式为准？

**Comment by andycall** [comment]
从功能上讲，SDK 集成就是把 Flutter 集成再封装一层，添加一些 Java/OC 的 API，最终实现还是回到 Dart 这边。所以最新的功能肯定都是先有 Dart API，然后再有 Java/OC API。在阿里内部，几乎每个团队都在用 Dart API，所以 SDK 集成这块的投入就偏少。
看样子社区上使用 SDK 集成的人要更多一些，我们后续会把 SDK 集成的功能与 Dart API 进行补齐。
