### ISSUE TITLE
希望支持离线包加载方式

### ISSUE THREAD

**Issue by xiaodb123** [openkraken/kraken#236]
## 使用场景 ｜ Use case

将js页面及资源打包到压缩包，将该压缩包下载到客户端本地，然后通过客户端加载下载好的本地离线包

**Comment by andycall** [comment]
Kraken 的 [bundlePath](https://github.com/openkraken/kraken/blob/main/kraken/lib/widget.dart#L30) 支持加载 assets 里面的文件。可以通过这个功能再写个离线包下载功能来实现

**Comment by xiaodb123** [comment]
> Kraken 的 [bundlePath](https://github.com/openkraken/kraken/blob/main/kraken/lib/widget.dart#L30) 支持加载 assets 里面的文件。可以通过这个功能再写个离线包下载功能来实现

目前需要从assets的flutter_assets中加载文件，能否支持从本地路径加载离线包呢？

**Comment by andycall** [comment]
Android assets 也可以直接加载

https://stackoverflow.com/questions/63294620/how-to-access-image-in-android-from-flutter

**Comment by wssgcg1213** [comment]
你好已知问题, Duplicated to #211
