### ISSUE TITLE
native控制页面跳转

### ISSUE THREAD

**Issue by ruyadelaosan** [openkraken/kraken#238]
请问页面跳转有没有完整的例子可以参考？跑官网的示例跳转页面出现白屏。
复现示例：http://openkraken.com/guide/advanced/handle-navigation

**Comment by wssgcg1213** [comment]
你好, 文档中提供的是一个不完整的示例, 你需要将回调函数中的逻辑补全, 调用你在全局创建的路由来进行页面级别的跳转 
```
KrakenNavigationDelegate navigationDelegate = KrakenNavigationDelegate();
navigationDelegate.errorHandler = (Object error, Object stack) {};
navigationDelegate.setDecisionHandler((KrakenNavigationAction action) async {
  // 这部分的响应需要自行实现
  print(action);
  if (action.target == 'b.js') {
    return KrakenNavigationActionPolicy.allow;
  }
  return KrakenNavigationActionPolicy.cancel;
});

Kraken kraken = Kraken(
  bundlePath: 'assets/bundle.js',
  navigationDelegate: navigationDelegate,
);
```

**Comment by xiaodb123** [comment]
> 你好, 文档中提供的是一个不完整的示例, 你需要将回调函数中的逻辑补全, 调用你在全局创建的路由来进行页面级别的跳转
> 
> ```
> KrakenNavigationDelegate navigationDelegate = KrakenNavigationDelegate();
> navigationDelegate.errorHandler = (Object error, Object stack) {};
> navigationDelegate.setDecisionHandler((KrakenNavigationAction action) async {
>   // 这部分的响应需要自行实现
>   print(action);
>   if (action.target == 'b.js') {
>     return KrakenNavigationActionPolicy.allow;
>   }
>   return KrakenNavigationActionPolicy.cancel;
> });
> 
> Kraken kraken = Kraken(
>   bundlePath: 'assets/bundle.js',
>   navigationDelegate: navigationDelegate,
> );
> ```

"全局创建的路由来进行页面级别的跳转" 这个可以详细说一下吗？有示例代码吗？

**Comment by xiaodb123** [comment]
> 你好, 文档中提供的是一个不完整的示例, 你需要将回调函数中的逻辑补全, 调用你在全局创建的路由来进行页面级别的跳转
> 
> ```
> KrakenNavigationDelegate navigationDelegate = KrakenNavigationDelegate();
> navigationDelegate.errorHandler = (Object error, Object stack) {};
> navigationDelegate.setDecisionHandler((KrakenNavigationAction action) async {
>   // 这部分的响应需要自行实现
>   print(action);
>   if (action.target == 'b.js') {
>     return KrakenNavigationActionPolicy.allow;
>   }
>   return KrakenNavigationActionPolicy.cancel;
> });
> 
> Kraken kraken = Kraken(
>   bundlePath: 'assets/bundle.js',
>   navigationDelegate: navigationDelegate,
> );
> ```
页面级别的跳转，是指跳转一个新的dart页面吗？还是在原有dart页面上加载新的js？

**Comment by xiaodb123** [comment]
> gallery 是个很好的例子
> 
> https://github.com/openkraken/gallery/blob/main/lib/main.dart

页面跳转DetailScreen后，点击Back，返回MainScreen页面，MainScreen展现内容变成了DetailScreen——是否是bug？
试了一下，把代码31行的KrakenNavigationActionPolicy.allow改为KrakenNavigationActionPolicy.cancel，页面也可正常跳转，且点击返回后不影响MainScreen原有展现内容。——这是为什么？

**Comment by xiaodb123** [comment]
> gallery 是个很好的例子
> 
> https://github.com/openkraken/gallery/blob/main/lib/main.dart

页面跳转DetailScreen后，点击Back，返回MainScreen页面，MainScreen展现内容变成了DetailScreen——是否是bug？
试了一下，把代码31行的KrakenNavigationActionPolicy.allow改为KrakenNavigationActionPolicy.cancel，页面也可正常跳转，且点击返回后不影响MainScreen原有展现内容。——这是为什么？

**Comment by andycall** [comment]
`页面跳转DetailScreen后，点击Back，返回MainScreen页面，MainScreen展现内容变成了DetailScreen——是否是bug？` 没太懂这段描述，点击 Back 之后，页面上显示不就是 MainScreen 的内容吗？

`KrakenNavigationActionPolicy.cancel` 控制的是 Kraken 的默认跳转行为，像 `<a>` 标签是存在一些默认行为，通过这个变量可以进行控制。


只要调用   Navigator.push 就会进行跳转，所以改为 cancel 是没有效果的。
```
navigationDelegate.setDecisionHandler((KrakenNavigationAction action) async {
      Navigator.push(context, MaterialPageRoute(builder: (_) {
        return DetailScreen(action);
      }));

      return KrakenNavigationActionPolicy.cancel;
    });
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

```
target
Where to display the linked URL, as the name for a browsing context (a tab, window, or <iframe>). The following keywords have special meanings for where to load the URL:
_self: the current browsing context. (Default)
_blank: usually a new tab, but users can configure browsers to open a new window instead.
_parent: the parent browsing context of the current one. If no parent, behaves as _self.
_top: the topmost browsing context (the "highest" context that’s an ancestor of the current one). If no ancestors, behaves as _self.
```

**Comment by xiaodb123** [comment]
> `页面跳转DetailScreen后，点击Back，返回MainScreen页面，MainScreen展现内容变成了DetailScreen——是否是bug？` 没太懂这段描述，点击 Back 之后，页面上显示不就是 MainScreen 的内容吗？--- 举个例子，MainScreen的内容为test，DetailScreen内容为hello，点击Back之后，返回的MainScreen内容变成了hello。这个Android和iOS表现还不太一样，上面的是Android端的现象，iOS端返回后MainScreen变为白屏
> 
> `KrakenNavigationActionPolicy.cancel` 控制的是 Kraken 的默认跳转行为，像 `<a>` 标签是存在一些默认行为，通过这个变量可以进行控制。
> 
> 只要调用 Navigator.push 就会进行跳转，所以改为 cancel 是没有效果的。
> 
> ```
> navigationDelegate.setDecisionHandler((KrakenNavigationAction action) async {
>       Navigator.push(context, MaterialPageRoute(builder: (_) {
>         return DetailScreen(action);
>       }));
> 
>       return KrakenNavigationActionPolicy.cancel;
>     });
> ```
> 
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
> 
> ```
> target
> Where to display the linked URL, as the name for a browsing context (a tab, window, or <iframe>). The following keywords have special meanings for where to load the URL:
> _self: the current browsing context. (Default)
> _blank: usually a new tab, but users can configure browsers to open a new window instead.
> _parent: the parent browsing context of the current one. If no parent, behaves as _self.
> _top: the topmost browsing context (the "highest" context that’s an ancestor of the current one). If no ancestors, behaves as _self.
> ```

**Comment by xiaodb123** [comment]
> `页面跳转DetailScreen后，点击Back，返回MainScreen页面，MainScreen展现内容变成了DetailScreen——是否是bug？` 没太懂这段描述，点击 Back 之后，页面上显示不就是 MainScreen 的内容吗？
> 
> `KrakenNavigationActionPolicy.cancel` 控制的是 Kraken 的默认跳转行为，像 `<a>` 标签是存在一些默认行为，通过这个变量可以进行控制。
> 
> 只要调用 Navigator.push 就会进行跳转，所以改为 cancel 是没有效果的。
> 
> ```
> navigationDelegate.setDecisionHandler((KrakenNavigationAction action) async {
>       Navigator.push(context, MaterialPageRoute(builder: (_) {
>         return DetailScreen(action);
>       }));
> 
>       return KrakenNavigationActionPolicy.cancel;
>     });
> ```
> 
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
> 
> ```
> target
> Where to display the linked URL, as the name for a browsing context (a tab, window, or <iframe>). The following keywords have special meanings for where to load the URL:
> _self: the current browsing context. (Default)
> _blank: usually a new tab, but users can configure browsers to open a new window instead.
> _parent: the parent browsing context of the current one. If no parent, behaves as _self.
> _top: the topmost browsing context (the "highest" context that’s an ancestor of the current one). If no ancestors, behaves as _self.
> ```
举个例子，MainScreen的内容为test，DetailScreen内容为hello，点击Back之后，返回的MainScreen内容变成了hello。这个Android和iOS表现还不太一样，上面的是Android端的现象，iOS端返回后MainScreen变为白屏

**Comment by xieyingze** [comment]
通过Native控制跳转，发现连续跳转8个页面后，直接白屏了。
