### ISSUE TITLE
样式background中引用的图片路径找不到

### ISSUE THREAD

**Issue by jianming1999** [openkraken/kraken#239]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

v0.7.2

### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 
<template>
<div :style="styles.icon_choose1">test</div>
</template>
<script>
var styles = {
 "icon_choose1": {
    "background": "url(images/icon-choose1.png) no-repeat",
    "backgroundSize": "100% 100%"
  }
}
export default {
  data(){
   return {
    styles
  }
 }
}
</script>

然后打出的bundle文件app.js和images目录是放在同一目录下的

**预期结果 ｜ Expected results:** 
可以正确以背景图的形式加载本地图片

**实际结果 ｜ Actual results:** 
Another exception was thrown: Unable to load asset: images/icon-choose1.png

**Comment by wssgcg1213** [comment]
目前图片的本地文件加载也依赖 Flutter 自带的 assets 机制  
https://flutter.dev/docs/development/ui/assets-and-images   
目前需要你提前把图片文件声明到 pubspec.yaml, 以在打包时获得正确的索引关系
