### ISSUE TITLE
希望将 Flutter 的布局错误透传给业务侧方便调试

### ISSUE THREAD

**Issue by airingursb** [openkraken/kraken#240]
## 使用场景 ｜ Use case

场景可见 #233 
目前如果 web 的样式交给 flutter engine 渲染时有布局错误，在浏览器内是可以正常展示的，但是交由北海渲染会直接白屏，且没有任何提示（也没有被 kraken 内的 try catch 捕获到）。希望可以将 flutter 的布局错误透传给业务侧方便定位问题。

## 提案 ｜ Proposal

直接显示 flutter 红屏信息即可，或者将错误信息打印到 devtools 的控制台上。

**Comment by answershuto** [comment]
感觉可以透出给 Native，Native 做具体的自定义行为，透给前端不是特别合适。

**Comment by andycall** [comment]
Dart 会在控制台会输出错误堆栈的，不清楚为啥没有看到日志，是被其他信息冲掉了吗？

**Comment by airingursb** [comment]
出现这种情况时 devtools 没有启动起来，即，终端里以下三行**没有打印**出来

```
flutter: Kraken DevTool listening at ws://127.0.0.1:9222
flutter: Open Chrome/Edge and paste following url to your navigator:
flutter:     devtools://devtools/bundled/inspector.html?ws=127.0.0.1:9222
```
