### ISSUE TITLE
子 DOM 节点没有继承父节点定义的样式

### ISSUE THREAD

**Issue by airingursb** [openkraken/kraken#241]
### 重现步骤 ｜ Steps To Reproduce

React Demo 即可

**重现代码 | Code example:** 

```javascript
const styles = {
  AppHeader: {
      backgroundColor: '#282c34',
      minHeight: '100vh',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '32px',
      color: 'white', // 白色
  },
}
```

```jsx
<div style={styles.AppHeader as CSSProperties} className="App-header">
  <p>
      Edit <span>src/App.js</span> and save to reload.
    </p>
</div>
```

此时 Web 下 `p` 标签为白色，但是 kraken 渲染的 `p` 标签文字是黑色。

**预期结果 ｜ Expected results:** 

预期结果如左 Chrome 浏览器所示，实际结果如右

![image](https://user-images.githubusercontent.com/10513408/116217050-dd447800-a77b-11eb-985c-3e94c4d9ead0.png)

**Comment by andycall** [comment]
样式继承还没有支持，现在需要把文本样式直接设置在包含文本色标签上

**Comment by airingursb** [comment]
> 样式继承还没有支持，现在需要把文本样式直接设置在包含文本色标签上

恩，那改 feature request 吧

**Comment by wssgcg1213** [comment]
Conflicted to #125 , Deadline 0.8 milestone cc @temper357 .
