### ISSUE TITLE
click 事件绑定的 console.log，在三端都没有看到日志输出

### ISSUE THREAD

**Issue by airingursb** [openkraken/kraken#242]
### 重现步骤 ｜ Steps To Reproduce

React Demo，给 span 绑定 onClick 事件。

1. kraken 直接加载 bundle，在 devtools 没有看到日志输出
2. flutter 源码调试，在 flutter 侧控制台没有看到日志输出
3. iOS 源码调试，在 Xcode 控制台也没有看到日志输出

不清楚是 click 事件的问题还是 console.log 的问题

**重现代码 | Code example:** 

```
<span id="sp" onClick={() => {
            console.log('111111');
}}>src/App.js</span>
```

**预期结果 ｜ Expected results:** 

三端都能看到日志输出

**实际结果 ｜ Actual results:** 

三端都没有看到日志

![image](https://user-images.githubusercontent.com/10513408/116220481-4bd70500-a77f-11eb-9e7c-3ac7dfdde6ef.png)

![image](https://user-images.githubusercontent.com/10513408/116220536-598c8a80-a77f-11eb-85ed-99ec62409b29.png)

![image](https://user-images.githubusercontent.com/10513408/116220501-509bb900-a77f-11eb-9caa-eadf24c633f9.png)

**Comment by answershuto** [comment]
直接用 Kraken Cli 运行 bundle 试试

**Comment by airingursb** [comment]
onClick 事件不生效，点击之后没有变红。


```
<span id="sp" onClick={() => {
            document.getElementById("sp")!.style.color = 'red';
          }}>src/App.js</span>
```

**Comment by airingursb** [comment]
> 直接用 Kraken Cli 运行 bundle 试试

也试过

**Comment by answershuto** [comment]
这个是哪个框架的工程，有 Bundle 或者 Demo 可以看看吗？

**Comment by airingursb** [comment]
console.log 在三端也是没有打印的， useEffect 之前验证是生效的

```js
useEffect(() => {
    console.log('useEffect')
  }, []);
```

**Comment by airingursb** [comment]
> 这个是哪个框架的工程，有 Bundle 或者 Demo 可以看看吗？

直接用官网提供的 react demo，

1. 在 span 标签上绑定 onClick 事件即可，能复现 click 事件不生效
2. 在 useEffect 打印日志，能复现 console.log 不生效

**Comment by answershuto** [comment]
我看一下

**Comment by airingursb** [comment]
请问有官网钉钉 or wechat 群吗，方便复现沟通

**Comment by answershuto** [comment]
我复现出来了，可以加我微信 answershuto，不过我们还是提倡用 issue 异步沟通，这样可以有个记录。

**Comment by airingursb** [comment]
> 我复现出来了，可以加我微信 answershuto，不过我们还是提倡用 issue 异步沟通，这样可以有个记录。

理解，所以我这里遇到问题会照常提 issue 的

**Comment by wssgcg1213** [comment]
React 的 click 事件是代理到 body 上触发的, 看起来是事件冒泡有一些问题

**Comment by airingursb** [comment]
日志这里应该是 Kraken 对 React 支持的问题，试了下 Rax 是没问题的

**Comment by jimboyeah** [comment]
Cli on Windows 什么时能上呢？

**Comment by zhangking** [comment]
这个有进展吗

**Comment by andycall** [comment]
#264

**Comment by airingursb** [comment]
> 这里可能要 reopen，自测 react 给 DOM 元素绑定的 onClick 事件还是不生效。但是用 addEventListener 做 click 事件绑定是没问题的

react 16 的问题，事件被代理到 document 上，无法被 kraken 处理 #360
