### ISSUE TITLE
报错提示：Kraken Binary NOT exists, try reinstall.

### ISSUE THREAD

**Issue by jiahuajiang60** [openkraken/kraken#247]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.7.2

### 重现步骤 ｜ Steps To Reproduce

根据你们的教程,运行下面指令
1. npm i @openkraken/cli -g
2. kraken https://raw.githubusercontent.com/openkraken/kraken/master/kraken/example/assets/bundle.js  这句报错

**预期结果 ｜ Expected results:** 
出现预览应用

**实际结果 ｜ Actual results:** 
![image](https://user-images.githubusercontent.com/27067501/116339037-59d46680-a80f-11eb-98a1-d560a0b4d732.png)
报错提示：**Kraken Binary NOT exists, try reinstall.**

**Comment by wssgcg1213** [comment]
Duplicated to #188
