### ISSUE TITLE
vue demo 绑定click 事件无反应

### ISSUE THREAD

**Issue by 627974327** [openkraken/kraken#248]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

Kraken: 0.7.2

### 重现步骤 ｜ Steps To Reproduce

Vue Demo，给 div 或者button绑定 onClick 事件。

kraken 直接加载 bundle，在 devtools 没有看到日志输出
不清楚是 click 事件的问题还是 console.log 的问题

**重现代码 | Code example:** 

`const more = document.createElement('button')
more.style["width"] = '100px'
more.style["height"] = '50px'
more.style["background"] = '#666'
more.addEventListener('click',function(){
  console.log('pppp')
  alert(1)
})`

或者

`<div v-on:click="loadMore">加载更多...</div>
methods: {
  loadMore(){
 console.log('pppp')
    alert(1)
  }
}`

**预期结果 ｜ Expected results:** 
日志输出

**实际结果 ｜ Actual results:** 

无反应

**Comment by wssgcg1213** [comment]
console.log 目前输出在命令行中

**Comment by 627974327** [comment]
> console.log 目前输出在命令行中, 你看看命令行界面中是否有

没有的，在方法中改变变量值显示在页面上，也是没反应，值不变

**Comment by 627974327** [comment]
> console.log 目前输出在命令行中, 你看看命令行界面中是否有

没有的，在方法中改变变量值显示在页面上，也是没反应，值不变

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/116343778-b471c080-a817-11eb-9fc9-b5d08eae6230.png)
我这边尝试了一下你的复现代码, 命令行中是可以输出的, 可以提供更多信息吗

**Comment by 627974327** [comment]
> ![image](https://user-images.githubusercontent.com/3922719/116343778-b471c080-a817-11eb-9fc9-b5d08eae6230.png)
> 我这边尝试了一下你的复现代码, 命令行中是可以输出的, 可以提供更多信息吗

找到问题了，是其它问题导致的，谢谢🙏
