### ISSUE TITLE
input 标签不支持 type=password, maxlength

### ISSUE THREAD

**Issue by Ryan-Shz** [openkraken/kraken#251]
input组件Rax代码：
```
import { createElement } from 'rax';
import styles from './index.module.css';

function PasswordInput() {

  return <input className={styles.passwordInputWrapper} type="password" placeholder="密码" maxlength={10} />;
}

export default PasswordInput;
```

使用Mac Kraken Cli运行时：
1. `type="password"`无效，输入框仍然以明文展示
2. `maxlength={10}`无效，输入框仍然可以输入超过10个以上的字符

在浏览器上运行正常。

**Comment by andycall** [comment]
表单相关的能力现在支持还很有限，后续的版本我们会支持更多的功能

**Comment by Ryan-Shz** [comment]
> 表单相关的能力现在支持还很有限，后续的版本我们会支持更多的功能

好的，后续的版本是否有时间节点？这些属于很基础的能力

**Comment by Ryan-Shz** [comment]
@wssgcg1213 value属性也不支持：`<input value="123"/>` 不生效。

**Comment by andycall** [comment]
@wssgcg1213 这个搞定了吗？
