### ISSUE TITLE
Rax 打印性能数据时会直接 Crash

### ISSUE THREAD

**Issue by airingursb** [openkraken/kraken#254]
### 重现步骤 ｜ Steps To Reproduce
Rax Demo 工程，给 View 绑定 Click 事件，打印 `performance.__kraken_navigation_summary__()`

**重现代码 | Code example:** 

```jsx
export default function Home() {
  return (
    <View onClick={() => {
      console.log(performance.__kraken_navigation_summary__());
    }} className={styles.homeContainer}>
      <Logo uri="//gw.alicdn.com/tfs/TB1MRC_cvb2gK0jSZK9XXaEgFXa-1701-1535.png" />
      <Text className={styles.homeTitle}>Welcome to Your Rax App</Text>
      <Text className={styles.homeInfo}>More information about Rax</Text>
      <Text className={styles.homeInfo}>Visit https://rax.js.org</Text>
    </View>
  );
}
```

**实际结果 ｜ Actual results:** 

1. 正常启动，但是点击时应用崩溃。
2. rax js 或 ts 都是同样的现象。
3. 打印其他信息无问题

堆栈如下：

![image](https://user-images.githubusercontent.com/10513408/116395102-439dc900-a856-11eb-995d-5d5888ef330c.png)

**Comment by airingursb** [comment]
Debug 模式的原因

**Comment by airingursb** [comment]
非 Profile 模式调用 `__kraken_navigation_summary__ ` 可以加个保护的

**Comment by andycall** [comment]
Already fixed
