### ISSUE TITLE
Can't build bridges due to conflict of version of rollup

### ISSUE THREAD

**Issue by kikuchy** [openkraken/kraken#255]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

I tried both of

* main 0eda1eacdbce0dd1a546b36480c4dd0fb87a4cdf
* 0.7.1 a8a5495461e816e03471a2abfeb0e169634fe727

### 重现步骤 ｜ Steps To Reproduce

```
$ git clone git@github.com:openkraken/kraken.git
$ cd kraken
$ npm init
$ npm run build:bridge:all
```

**重现代码 | Code example:** 

Environment

* macOS `10.15.7（19H524）`
* node `v12.13.0`

**预期结果 ｜ Expected results:** 

Exit with code 0

**实际结果 ｜ Actual results:** 

```

> build:bridge:all
> node scripts/prepare_kraken_release_binary

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: rollup@2.45.2
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"^2.6.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@">=0.66.0 <2" from rollup-plugin-uglify@6.0.4
npm ERR! node_modules/rollup-plugin-uglify
npm ERR!   dev rollup-plugin-uglify@"^6.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/kikuchy/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kikuchy/.npm/_logs/2021-04-28T10_56_09_286Z-debug.log

> build
> NODE_ENV=development rollup --config rollup.config.js && npm run mainToC && npm run testToC

sh: rollup: command not found
npm ERR! code 127
npm ERR! path /Users/kikuchy/tmp/kraken/bridge/polyfill
npm ERR! command failed
npm ERR! command sh -c NODE_ENV=development rollup --config rollup.config.js && npm run mainToC && npm run testToC

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kikuchy/.npm/_logs/2021-04-28T10_56_09_707Z-debug.log
/Users/kikuchy/tmp/kraken/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 1,
  name: 'compile-polyfill',
  branch: false,
  error: 127,
  duration: [ 2, 614492361 ],
  time: 1619607369721
})
    at Gulp.emit (events.js:199:17)
    at Gulp.EventEmitter.emit (domain.js:476:20)
    at Object.error (/Users/kikuchy/tmp/kraken/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/kikuchy/tmp/kraken/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/kikuchy/tmp/kraken/node_modules/once/once.js:25:25)
    at f (/Users/kikuchy/tmp/kraken/node_modules/once/once.js:25:25)
    at tryCatch (/Users/kikuchy/tmp/kraken/node_modules/async-done/index.js:24:15)
    at done (/Users/kikuchy/tmp/kraken/node_modules/async-done/index.js:40:12)
    at /Users/kikuchy/tmp/kraken/scripts/tasks.js:201:12
    at compile-polyfill (/Users/kikuchy/tmp/kraken/node_modules/undertaker/lib/set-task.js:13:15) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    uid: 1,
    name: 'compile-polyfill',
    branch: false,
    error: 127,
    duration: [ 2, 614492361 ],
    time: 1619607369721
  }
}
npm ERR! code 1
npm ERR! path /Users/kikuchy/tmp/kraken
npm ERR! command failed
npm ERR! command sh -c node scripts/prepare_kraken_release_binary

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kikuchy/.npm/_logs/2021-04-28T10_56_09_739Z-debug.log
```

<details>
<summary>/Users/kikuchy/.npm/_logs/2021-04-28T10_56_09_739Z-debug.log</summary>
<pre>
<code>
0 verbose cli [
0 verbose cli   '/Users/kikuchy/.nvm/versions/node/v12.13.0/bin/node',
0 verbose cli   '/Users/kikuchy/.nvm/versions/node/v12.13.0/bin/npm',
0 verbose cli   'run',
0 verbose cli   'build:bridge:all'
0 verbose cli ]
1 info using npm@7.5.4
2 info using node@v12.13.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/Users/kikuchy/.nvm/versions/node/v12.13.0/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/Users/kikuchy/tmp/kraken/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/kikuchy/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/Users/kikuchy/.nvm/versions/node/v12.13.0/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session f08668c255b94fe0
20 timing npm:load Completed in 25ms
21 timing command:run-script Completed in 4092ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/Users/kikuchy/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:210:5)
22 verbose stack     at maybeClose (internal/child_process.js:1021:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
23 verbose cwd /Users/kikuchy/tmp/kraken
24 verbose Darwin 19.6.0
25 verbose argv "/Users/kikuchy/.nvm/versions/node/v12.13.0/bin/node" "/Users/kikuchy/.nvm/versions/node/v12.13.0/bin/npm" "run" "build:bridge:all"
26 verbose node v12.13.0
27 verbose npm  v7.5.4
28 error code 1
29 error path /Users/kikuchy/tmp/kraken
30 error command failed
31 error command sh -c node scripts/prepare_kraken_release_binary
32 verbose exit 1
</code>
</pre>
</details>

**Comment by andycall** [comment]
npm 依赖安装冲突，可以看下这里的解法

https://stackoverflow.com/questions/64573177/unable-to-resolve-dependency-tree-error-when-installing-npm-packages

**Comment by wssgcg1213** [comment]
fixed at https://github.com/openkraken/kraken/pull/264/files
