### ISSUE TITLE
Kraken SDK集成方式，希望支持共享Flutter引擎的页面混合跳转方式

### ISSUE THREAD

**Issue by xiaodb123** [openkraken/kraken#256]
## 使用场景 ｜ Use case

在原生(Android/iOS)页面与Flutter页面相互跳转的场景下，支持Flutter页面使用同一个FlutterEngine

**Comment by andycall** [comment]
这个能力应该超出 kraken 这个项目本身的范畴，或许你应该看下 [flutter_boost](https://github.com/alibaba/flutter_boost)
