### ISSUE TITLE
web w3c标准支持范围

### ISSUE THREAD

**Issue by ruyadelaosan** [openkraken/kraken#258]
1、官方网站上说支持全部w3c的标准，但是又明确列出了kraken所支持的HTML标签、CSS样式等web标准，是不是未明确列出的还存在一定的支持问题？在使用过程中发现了浮动布局的支持度没有弹性盒子布局高，会有一些表现差异。
2、所有rax的标签或api，kraken都支持吗？是不是使用rax开发会相对好一点呢？我看文档也没有提及rax在kraken上的注意事项。

**Comment by andycall** [comment]
1. kraken 不会支持全部 w3c 的标准，而是有限子集，在功能有限的情况下，提供更快更轻量的实现。现在文档列出来的都是已经支持的功能，没有列出来的还没做，如果有需求，欢迎提 Issue。
2. 有一些过时的功能 Kraken 并不打算去支持，比如 float
3. kraken 并不会绑定任何一个前端框架，不管是 rax，react，vue 都可以使用。只是现在这个阶段来看，rax 的用户多一些（因为阿里内部 rax 用户多），所以看上去 rax 支持就更好。
4. 任何和 react，vue 使用遇到的问题都可以在这里提出 Issue，我们都会一同看待并解决。
