### ISSUE TITLE
iOS 设备上访问  http://192.168.41.163:3002 黑屏

### ISSUE THREAD

**Issue by dadigua2333** [openkraken/kraken#259]
项目可以运行成功. 
但是加载示例代码时候. 也黑屏.
加载 示例项目 npm  start以后生成的网址 一样黑屏

**Comment by andycall** [comment]
应该和这个是一个问题 https://github.com/openkraken/kraken/issues/235

现在可以尝试使用 debug 包，或者使用 Widget 的方式来使用。
