### ISSUE TITLE
device_info 依赖版本太低了，建议升级

### ISSUE THREAD

**Issue by airingursb** [openkraken/kraken#260]
## 使用场景 ｜ Use case

目前 kraken 依赖 device_info 的是 0.4.1，但是实际业务中用到的 device_info 的版本普遍大于它，导致依赖冲突无法安装 kraken plugin。

## 提案 ｜ Proposal

目前的 device_info 最新版是 [2.0](https://pub.dev/packages/device_info/versions)，建议升级

**Comment by andycall** [comment]
欢迎提个 PR

**Comment by airingursb** [comment]
好的
