### ISSUE TITLE
react工程点击事件报错

### ISSUE THREAD

**Issue by ruyadelaosan** [openkraken/kraken#261]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.7.0

### 重现步骤 ｜ Steps To Reproduce

修改react示例工程/app.js

**重现代码 | Code example:** 

import { useState } from 'react';
function App() {
  const [isToggleOn, setIsToggleOn] = useState(0);
  return (
    <div style={{'padding-top':'40px'}}>
    <button onClick={() => setIsToggleOn(!isToggleOn)}>
      {isToggleOn ? 'ON' : 'OFF'}
    </button>
    </div>
  );
}
export default App;

**预期结果 ｜ Expected results:** 
1、点击与样式与web端一致

**实际结果 ｜ Actual results:** 
1、点击按钮没反应
2、无button样式，仅有文字
3、点击后flutter控制台日志如下：  
D/stylus  (14173): init stylus touchlistener.
W/Settings(14173): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(14173): User setup is finished.

**Comment by yuanyan** [comment]
react 的适配问题正在定位原因
