### ISSUE TITLE
实现 DocumentFragment 功能

### ISSUE THREAD

**Issue by freedom-shen** [openkraken/kraken#263]
## 使用场景 ｜ Use case

DocumentFragment相关API在实际开发中，为减少不必要的刷新，使用频率还是较高。

## 提案 ｜ Proposal

``` js
var fragment = new DocumentFragment()
var fragment = document.createDocumentFragment();
fragment.appendChild..
fragment.replaceChild..
```

**Comment by wssgcg1213** [comment]
`class DocumentFragment extends Node `
https://hg.mozilla.org/mozilla-central/file/tip/dom/webidl/DocumentFragment.webidl
成本不高, 安排到 milestone 0.8
