### ISSUE TITLE
Demo 集成到Flutter中报错   Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by dadigua2333** [openkraken/kraken#266]
按照官网上的步骤.和flutter版本.
我的xcode版本是 12.4

Xcode报错:  Command PhaseScriptExecution failed with a nonzero exit code

**Comment by wssgcg1213** [comment]
你好, 需要提供更详细的信息，退出码非 0 表示构建异常

**Comment by dadigua2333** [comment]
> 你好, 需要提供更详细的信息，退出码非 0 表示构建异常

就是跟着官网步骤走, Flutter的计时器Demo可以正常跑.
然后flutter pub get
把文档上的代码粘贴到 main.dart中. 此时 AS中报错 :
Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

然后我进入iOS目录用 Xcode跑Runner项目. 就这样了

**Comment by dadigua2333** [comment]
我的flutter版本是 1.20.0 是这个关系吗
