### ISSUE TITLE
kraken/example/iOS demo不能启动

### ISSUE THREAD

**Issue by ohrl** [openkraken/kraken#267]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.7.2

### 重现步骤 ｜ Steps To Reproduce

1.clone kraken 主目录
2.npm install
3.npm run build:bridge:ios
4.cd kraken/example 5
5.flutter run

**重现代码 | Code example:** 
demo工程无改动

**预期结果 ｜ Expected results:** 
真机运行并启动demo应用

**实际结果 ｜ Actual results:** 

log:
../lib/src/gesture/scroll_position_with_single_context.dart:37:7: Error: The
    non-abstract class 'ScrollPositionWithSingleContext' is missing implementations for
    these members:
     - ViewportOffset.hasPixels
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.

    class ScrollPositionWithSingleContext extends ScrollPosition implements
    ScrollActivityDelegate {
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../flutter/packages/flutter/lib/src/rendering/viewport_offset.dart:96:12:
    Context: 'ViewportOffset.hasPixels' is defined here.
      bool get hasPixels;
               ^^^^^^^^^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
   ~/Desktop/improve/git-hub/kraken/kraken/example/ios/Pods/Pods.xcodep
    roj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0,
    but the range of supported deployment target versions is 9.0 to 14.5.99. (in target
    'Reachability' from project 'Pods')
    ~/Desktop/improve/git-hub/kraken/kraken/example/ios/Pods/Pods.xcodep
    roj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0,
    but the range of supported deployment target versions is 9.0 to 14.5.99. (in target
    'Flutter' from project 'Pods')

Could not build the precompiled application for the device.

env:  pod 1.10.0
        flutter 2.0.5
        mac os 11.2

**Comment by andycall** [comment]
flutter 2.x 版本还不支持，请使用 flutter 1.22.4 版本

**Comment by luwuer** [comment]
> flutter 2.x 版本还不支持，请使用 flutter 1.22.4 版本

flutter 1.22-candidate.4 / 1.22-candidate.0 分支依然报错，如下：
```
In file included from /Users/mdy/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/ios/Classes/FLTSharedPreferencesPlugin.m:5:
    /Users/mdy/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/ios/Classes/FLTSharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/mdy/.pub-cache/hosted/pub.dartlang.org/kraken_websocket-0.1.1/ios/Classes/KrakenWebsocketPlugin.m:1:
    /Users/mdy/.pub-cache/hosted/pub.dartlang.org/kraken_websocket-0.1.1/ios/Classes/KrakenWebsocketPlugin.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    Command CompileSwift failed with a nonzero exit code
    In file included from /Users/mdy/workspace_test/kraken/kraken/kraken/ios/Classes/Kraken.m:2:
    /Users/mdy/workspace_test/kraken/kraken/kraken/ios/Classes/Kraken.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/mdy/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.28/ios/Classes/FLTPathProviderPlugin.m:5:
    /Users/mdy/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.28/ios/Classes/FLTPathProviderPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/mdy/workspace_test/kraken/kraken/kraken/ios/Classes/KrakenPlugin.m:1:
    /Users/mdy/workspace_test/kraken/kraken/kraken/ios/Classes/Kraken.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/mdy/.pub-cache/hosted/pub.dartlang.org/kraken_devtools-0.1.2+2/ios/Classes/KrakenDevtoolsPlugin.m:1:
    /Users/mdy/.pub-cache/hosted/pub.dartlang.org/kraken_devtools-0.1.2+2/ios/Classes/KrakenDevtoolsPlugin.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/mdy/.pub-cache/hosted/pub.dartlang.org/jsc-0.1.5/ios/Classes/JscPlugin.m:1:
    /Users/mdy/.pub-cache/hosted/pub.dartlang.org/jsc-0.1.5/ios/Classes/JscPlugin.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/mdy/.pub-cache/hosted/pub.dartlang.org/device_info-1.0.0/ios/Classes/FLTDeviceInfoPlugin.m:5:
    /Users/mdy/.pub-cache/hosted/pub.dartlang.org/device_info-1.0.0/ios/Classes/FLTDeviceInfoPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
```
