### ISSUE TITLE
断点 C++ 的疑问

### ISSUE THREAD

**Issue by weixinjie** [openkraken/kraken#276]
1. 按照  https://openkraken.com/guide/contribute/development 文档
![image](https://user-images.githubusercontent.com/6205100/117258198-4a909100-ae7f-11eb-9583-99b2a6aa230c.png)

2. 在 insertBefore 函数中插入了 assert(false) 
![image](https://user-images.githubusercontent.com/6205100/117258438-90e5f000-ae7f-11eb-8c8a-bd56350ad3c2.png)

问题：
运行 xcode 项目后没有崩溃断点，是需要在 demo 中做什么操作才能断住还是运行起项目后就能断住？

**Comment by andycall** [comment]
bridge 重新构建了吗？

**Comment by weixinjie** [comment]
执行步骤：
1. 添加了 assert(false) 后 bridge 重新构建的方式为：npm run build:bridge:macos
2.清理了 flutter 产物 flutter clean 
3. 重新生成了 flutter debug 构建 flutter build macos --debug

现象：
1. 执行完上述步骤后 xcode 重新运行并不能断住
2. 尝试在 JSNode 构造函数中添加 assert(false) 后能成功断点，但是源码链接不出来
![image](https://user-images.githubusercontent.com/6205100/117259621-cf2fdf00-ae80-11eb-9d61-6a71cef1da39.png)
![image](https://user-images.githubusercontent.com/6205100/117259703-e373dc00-ae80-11eb-857d-071964f60021.png)

**Comment by andycall** [comment]
之前遇到过一个断点后，Xcode 反编译不了源码的bug，后来又修复了。

你可以检查一下你的代码是不是和这里一样

https://github.com/openkraken/kraken/blob/main/bridge/CMakeLists.txt#L5

**Comment by weixinjie** [comment]
拉取最新代码后成功了   分享一下原因？ 目前看就是 CMakeList.txt 文件的编译规则发生了改动造成的
