### ISSUE TITLE
兼容在 Widget 使用情况下调用 Plugin 的 loadUrl 能覆盖 Widget 传递的 bundleUrl/bundlePath/bundleContent

### ISSUE THREAD

**Issue by wssgcg1213** [openkraken/kraken#280]
## 使用场景 ｜ Use case

使用 Widget 创建 View 的情况下, 需要在外部使用 Native API 控制 KrakenView 的导航和加载

## 提案 ｜ Proposal

```
kraken.loadUrl(String url); // Always works, like WebView.
```

**Comment by andycall** [comment]
https://github.com/openkraken/kraken/issues/232

**Comment by andycall** [comment]
Fixed in https://github.com/openkraken/kraken/pull/419
