### ISSUE TITLE
给div添加点击事件. 和a标签点击 没反应

### ISSUE THREAD

**Issue by dadigua2333** [openkraken/kraken#281]
用Flutter 加载本地js文件.
在网页中点击没问题.但是在app中无效

**Comment by answershuto** [comment]
是 react 工程吗？

**Comment by wssgcg1213** [comment]
已修复, 请使用 main 分支构建, cli 会尽快更新新版本

**Comment by dadigua2333** [comment]
> 已修复, 请使用 main 分支构建, cli 会尽快更新新版本

请问 怎么用main分支构建. 能再详细点嘛? 新手请谅解
