### ISSUE TITLE
添加一套独立于引擎之上的 JS Engine API 设计

### ISSUE THREAD

**Issue by andycall** [openkraken/kraken#283]
Kraken 未来会在 JS Engine 领域上进行更多的探索，包括尝试不同的 JS Engine，使用一些 Private API 等，但是这些工作又会对上层的 bridge 功能实现带来很多 Break Changes，因此需要设计并实现一层独立于引擎之外的抽象设计。

Node.js 的 （[Node-API](https://nodejs.org/api/n-api.html)）是个很好的参考

这个设计上，有几个目标需要达成：

1. 使用模版及内联函数去降低函数调用开销
2. 禁用 copy 语义，借鉴 rapidJSON 的 move 语义
3. 优先将 JS 对象分配到栈上，同时也支持分配在堆上。
4. 支持 JS  类，函数的创建，并支持实现 JS 原型继承的 API

**Comment by ghkjgod** [comment]
考虑支持v8吗？

**Comment by andycall** [comment]
v8在移动设备上没有很高的使用场景，主要问题是 JIT 在 iOS 设备上受限，并且体积庞大。

**Comment by andycall** [comment]
Kraken 计划支持一款嵌入式 JS 引擎和一款现代浏览器内置的 JS 引擎（JSC），用于支撑不同的应用场景。

嵌入式 JS 引擎相比现代浏览器内置的 JS 引擎有着启动速度快，内存占用小的特点，适合运行内存压力复杂较低和 CPU 较少的页面。
现代浏览器内置的 JS 引擎的 GC 要更加强大，优化策略也更多，所以跑一些复杂页面也更有优势，但是启动速度和内存使用要劣势很多。

**Comment by andycall** [comment]
现在社区上 android 版本的 jsc 都是阉割版的 JIT，所以性能比 v8 差是肯定的。我们也把 v8 纳入设计的考虑范围

https://github.com/react-native-community/jsc-android-buildscripts/blob/master/scripts/compile/jsc.sh#L81

**Comment by yjhenan** [comment]
ScriptX是一个脚本引擎抽象层。对下封装多种脚本引擎，对上暴露统一的API，使得上层调用者可以完全隔离底层的引擎实现(后端)。
ScriptX不仅隔离了几种JavaScript引擎，甚至可以隔离不同脚本语言，使得上层仅需修改一个编译选项即可无缝切换脚本引擎和脚本语言。
ScriptX的术语中，"前端"指对外的C++ API，"后端"则指不同的底层引擎，目前已经实现的后端有：V8, node.js, JavaScriptCore, WebAssembly, Lua.
https://github.com/Tencent/ScriptX

**Comment by andycall** [comment]
> ScriptX是一个脚本引擎抽象层。对下封装多种脚本引擎，对上暴露统一的API，使得上层调用者可以完全隔离底层的引擎实现(后端)。
ScriptX不仅隔离了几种JavaScript引擎，甚至可以隔离不同脚本语言，使得上层仅需修改一个编译选项即可无缝切换脚本引擎和脚本语言。
ScriptX的术语中，"前端"指对外的C++ API，"后端"则指不同的底层引擎，目前已经实现的后端有：V8, node.js, JavaScriptCore, WebAssembly, Lua.
https://github.com/Tencent/ScriptX

看上去是个好东西，我研究一下

**Comment by yuanyan** [comment]
因为是比较大的改动，确定方案之前得明确下 Kraken 的目标是什么？我的想法是 Kraken 目标是解决 WebView 不足的地方，是 WebView 的选择，比如 WebView 因为网络 IO 过多与 JS 初始化时间长导致的的加载体验问题，WebView 的长列表白屏体验问题等，在众多问题中第一要解决的依旧是加载体验问题，JS 引擎的选择与加载体验优化强相关。所以 JS 引擎的选择需要符合几个特质：

1. JS 引擎要在双端能支持 类bytecode 读取
2. JS 引擎冷动足够快

**Comment by andycall** [comment]
Quickjs 的确能够解决上面 1，2 的问题，但是不能忽视的是，Quickjs 在实现这两个目标的同时，也舍弃了一些特性，比如 concurrency GC，因此在一些内存压力场景下，会有卡顿的存在，这个是像 V8，JSC这些已经支持 concurrency GC 都不存在的问题。
我的担忧是我们希望去解决1，2这些问题，但是又会引入新的问题，引入抽象层的目标是让我们应对这些问题会更加从容一些，因为上面所说的问题都是设计问题，都是很难使用简单方法进行规避的，毕竟我们不能要求用户少些 JS 代码。

**Comment by andycall** [comment]
或许直接用 hermas 而不是 quickjs，能平衡上面的各种问题

**Comment by yjhenan** [comment]
<html>
<body>


引擎 | QuickJS | DukTape | XS | MuJS | JerryScript | Hermes | V8 --jitless | V8 (JIT)
-- | -- | -- | -- | -- | -- | -- | -- | --
可执行文件尺寸 | 620K | 331K | 1.2M | 244K | 211K | 27M | 28M | 28M


</body>
</html>

包体积也考虑下呗🤣

**Comment by andycall** [comment]
依据当时 TSC 的讨论，多引擎抽象暂时不搞，先直接支持 quickjs

https://github.com/openkraken/TSC/blob/master/meetings/2021-05-13.md
