### ISSUE TITLE
dart代码无法直接通过 javaScriptChannel.invokeMethod 调用js方法

### ISSUE THREAD

**Issue by xiaodb123** [openkraken/kraken#287]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.7.1

### 重现步骤 ｜ Steps To Reproduce

dart代码无法直接通过 javaScriptChannel.invokeMethod 调用js方法
但在javaScriptChannel.onMethodCal中可以通过javaScriptChannel.invokeMethod 调用js方法

**重现代码 | Code example:** 

class _MainBodyState extends State<MainBody>{

  @override
  Widget build(BuildContext context) {
    final MediaQueryData queryData = MediaQuery.of(context);

    AppBar appBar = new AppBar(
      leading: new IconButton(icon: Icon(Icons.arrow_back_ios), onPressed:_goBackToNativePage,),
      title: new Text("1000条列表"),
      centerTitle: true,
    );

    final Size viewportSize = queryData.size;

    //js桥接dart
    KrakenJavaScriptChannel javaScriptChannel = KrakenJavaScriptChannel();
    javaScriptChannel.onMethodCall = (String method, dynamic arguments) async {
      Completer completer = Completer<String>();
      switch (method) {
        case 'bridge':
          print(' dart桥接js ');
          Timer(Duration(seconds: 1), () {
            //可以调用
            javaScriptChannel.invokeMethod('foo', [1234]);
          });
          completer.complete('finish');
          return completer.future;
      }
    };

    Timer(Duration(seconds: 1), () {
      //不能调用
      javaScriptChannel.invokeMethod('foo', [1234]);
    });

   return Scaffold(
        appBar: appBar,
        body: Kraken(
          viewportWidth: viewportSize.width - queryData.padding.horizontal,
          viewportHeight: viewportSize.height - appBar.preferredSize.height - queryData.padding.vertical,
          bundlePath: 'static/message.js',
          //桥接Channel
          javaScriptChannel: javaScriptChannel,
        ),
   );
  }

  static const platform = const MethodChannel('samples.flutter.dev/goToNativePage');
  Future<void> _goBackToNativePage() async {
    try {
      final String result = await platform.invokeMethod('goBackToNativePage');
    } on PlatformException catch (e) {
    }
  }
}

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by wssgcg1213** [comment]
在默认情况下，客户端发送过来的任何调用都会被抛弃，除非使用 JavaScript 调用 kraken.methodChannel.setMethodCallHandler 注册一个处理函数。

在设置了处理函数之后，任何客户端发送过来的任何调用都将调用这个处理函数。

```js
kraken.methodChannel.setMethodCallHandler((method, args) => {
  switch (method) {
    case 'foo':
      handleFoo(args);
      break;
    case 'bar':
      handleBar(args);
      break;
  }
});
```

> https://openkraken.com/guide/advanced/communicate-with-native

**Comment by xiaodb123** [comment]
> 在默认情况下，客户端发送过来的任何调用都会被抛弃，除非使用 JavaScript 调用 kraken.methodChannel.setMethodCallHandler 注册一个处理函数。
> 
> 在设置了处理函数之后，任何客户端发送过来的任何调用都将调用这个处理函数。
> 
> ```js
> kraken.methodChannel.setMethodCallHandler((method, args) => {
>   switch (method) {
>     case 'foo':
>       handleFoo(args);
>       break;
>     case 'bar':
>       handleBar(args);
>       break;
>   }
> });
> ```
> 
> > https://openkraken.com/guide/advanced/communicate-with-native

js代码里面已经设置了处理函数，且在javaScriptChannel.onMethodCal中可以通过javaScriptChannel.invokeMethod 调用js方法，只有在dart代码直接通过 javaScriptChannel.invokeMethod 无法调用js方法
下面是js代码：

var root = document.createElement('div');
var button = document.createElement('div');
button.appendChild(document.createTextNode('桥接调用Dart bridge方法'));
button.style.fontSize = "20px";
button.setAttribute("id","button")
//调用Dart bridge方法
button.addEventListener('click',function(){
  kraken.methodChannel
  .invokeMethod('bridge', 'parameter 1', ['parameter 2'], {
    value: 'parmeter 3',
  })
  .then(result => {
    console.log('data from native', result);
  })
  .catch(err => {
    console.log('some error occured', err);
  });
});

//提供给Dart调用的方法
kraken.methodChannel.setMethodCallHandler((method, args) => {
  switch (method) {
    case 'foo':
      console.log('method foo, args：',args);
      root.appendChild(document.createTextNode('Dart bridge方法，桥接调用JS foo方法，传入参数：'+ args));
      break;
    case 'bar':
      console.log('method bar, args：',args);
      break;
  }
});
root.appendChild(button)
document.body.style.padding='50px 0px';
document.body.appendChild(root);

**Comment by andycall** [comment]
刚才用一个简单的例子试了下，看上去真的有 bug，我看下是为啥

**Comment by xiaodb123** [comment]
想请教一下，dart桥接调用js方法，对于如下场景，dart页面A中通过js代码设置了处理函数foo，能否在Dart页面B中通过javaScriptChannel.invokeMethod来调用函数foo呢？

**Comment by xiaodb123** [comment]
> 刚才用一个简单的例子试了下，看上去真的有 bug，我看下是为啥

想请教一下，dart桥接调用js方法，对于如下场景，dart页面A中通过js代码设置了处理函数foo，能否在Dart页面B中通过javaScriptChannel.invokeMethod来调用函数foo呢？

**Comment by andycall** [comment]
每个页面的通道都是独立的，所以不能直接跨页面进行通信。不过可以在 Dart 层做转接，即 A 页面的 JS -> A 页面的 Dart -> B 页面的 Dart -> B 页面的 JS
