### ISSUE TITLE
Building for iOS, but the embedded framework 'kraken_bridge.framework' was built for iOS + iOS Simulator. 

### ISSUE THREAD

**Issue by yanghuittxs** [openkraken/kraken#295]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

版本是 ：ios.sdk.0.7.2

### 重现步骤 ｜ Steps To Reproduce

按照这个步骤添加的：http://openkraken.com/guide/native/interpolation-app

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 
xcode项目编译通过，成功集成框架

**实际结果 ｜ Actual results:** 
提示：Building for iOS, but the embedded framework 'kraken_bridge.framework' was built for iOS + iOS Simulator.

**Comment by andycall** [comment]
https://github.com/openkraken/kraken/issues/219
