### ISSUE TITLE
react 工程在 kraken devtools 和 flutter 调试工程均无法看到日志打印

### ISSUE THREAD

**Issue by JuneScut** [openkraken/kraken#299]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
^0.7.2

### 重现步骤 ｜ Steps To Reproduce
使用 hello-react, 在渲染前打印一行日志。

**重现代码 | Code example:** 
![image](https://user-images.githubusercontent.com/29206208/117771279-830de180-b268-11eb-87b2-2315be1bfb1c.png)

**预期结果 ｜ Expected results:** 
flutter 调试工程或 kraken devtools 有日志输出

**实际结果 ｜ Actual results:** 
1. kraken 加载js，devtools 没有日志输出
2. flutter 调试工程没有日志输出

**Comment by JuneScut** [comment]
![image](https://user-images.githubusercontent.com/29206208/117778531-5231aa80-b270-11eb-9212-2452e904491d.png)
命令行也没有

**Comment by andycall** [comment]
使用了最新的 0.7.3 版本的 kraken 吗？

![image](https://user-images.githubusercontent.com/4409743/117780044-d3d60800-b271-11eb-97f0-ea991f319880.png)
![image](https://user-images.githubusercontent.com/4409743/117780095-e2242400-b271-11eb-973d-66ab0ba36507.png)

**Comment by JuneScut** [comment]
我锁定了版本 0.7.2+4。这是 pub.dev 的最新版本，还是有这个错误：can not dispatch method: Log.startViolationsReport

**Comment by JuneScut** [comment]
![image](https://user-images.githubusercontent.com/29206208/117783461-249b3000-b275-11eb-9e80-e92f08bfbfb3.png)
是 0.7.3
