### ISSUE TITLE
Android 安装了APK  是如何做到和 chrome inspector 进行调试的？

### ISSUE THREAD

**Issue by mrme2014** [openkraken/kraken#306]
## 使用场景 ｜ Use case

Android 安装了APK  是如何做到和 chrome inspector 进行调试的？
这块代码在哪里呢？有开源吗？

**Comment by andycall** [comment]
https://github.com/openkraken/devtools

通过 C++ 调用了 JSC 的一些私有 API，然后启动一个 WebSocket 服务和 DevTools 进行通讯

**Comment by mrme2014** [comment]
> https://github.com/openkraken/devtools
> 
> 通过 C++ 调用了 JSC 的一些私有 API，然后启动一个 WebSocket 服务和 Chrome DevTools 进行通讯

看了devtools的readme.

看起来像是在PC上起了一个kraken ws server用于中转chrome devtool 和 jscore的往来协议？

那APP 是如何连接到PC上的ws server的呢？

**Comment by andycall** [comment]
是手机启动一个 ws server，然后 PC 连接上去

**Comment by mrme2014** [comment]
> 是手机启动一个 ws server，然后 PC 连接上去

手机起ws server, PC怎么连接啊？  手机上的ip+port服务 PC能链接吗？

**Comment by andycall** [comment]
同一个 WIFI 环境下可以，日志中有访问的地址

**Comment by mrme2014** [comment]
> 同一个 WIFI 环境下可以，日志中有访问的地址

APP上启动了一个socket server,  chrome devtool 怎么知道连接这个服务啊？

方便加个微信交流下吗？谢谢   维信：QooBee2020

**Comment by andycall** [comment]
调试服务的发现还没有做，目前需要在日志中找到调试地址，然后直接连接
