### ISSUE TITLE
监听touch事件改变元素位置，程序闪退

### ISSUE THREAD

**Issue by JuneScut** [openkraken/kraken#307]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
master分支

### 重现步骤 ｜ Steps To Reproduce
拖动元素，如下图所示，触发了几个事件后闪退
![image](https://user-images.githubusercontent.com/29206208/117816321-fb8c9680-b298-11eb-8f4a-9eb7d18c9ac2.png)

**重现代码 | Code example:** 

**实际结果 ｜ Actual results:**

**Comment by JuneScut** [comment]
请问这里有头绪了吗 @answershuto

**Comment by airingursb** [comment]
我看了一下，这里是 bridge 没有注册手势取消事件导致的闪退，我提个 pr 修一下吧 @answershuto
