### ISSUE TITLE
运行macos app时白屏

### ISSUE THREAD

**Issue by vanney9** [openkraken/kraken#308]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
<master>

本意是想按照文档说明的：源码调试bridge

### 重现步骤 ｜ Steps To Reproduce
1. 使用的flutter版本 1.22.2-stable
2. 然后切换到其他channel  git checkout 1.22.2
3. 支持macos应用： flutter config --enable-macos-desktop
4. 运行flutter： flutter run

然后白屏了，报错信息是 :
[ +566 ms] 2021-05-12 10:57:05.357 kraken_example[50263:7265000] Failed to find path for "flutter_assets"
[   +1 ms] embedder.cc (740): 'FlutterEngineInitialize' returned 'kInvalidArguments'. The assets path in the Flutter project arguments
was missing.
[        ] 2021-05-12 10:57:05.357 kraken_example[50263:7265000] Failed to initialize Flutter engine: error 2

**Comment by andycall** [comment]
flutter clean 一下再运行

https://github.com/flutter/flutter/issues/72608

**Comment by vanney9** [comment]
还是同样的问题，想问下：你们运行的时候 flutter是什么版本呢？ @andycall

**Comment by andycall** [comment]
https://github.com/openkraken/kraken/blob/main/kraken/pubspec.yaml#L8

**Comment by airingursb** [comment]
我这里也是同样的问题和报错信息

https://github.com/openkraken/website/issues/136

**Comment by airingursb** [comment]
猜测是产物没清干净导致的，clean 了也清掉了 build 文件还是不行。
最后重新 clone，直接走跑 flutter run -d macos --debug 可以

**Comment by Fantasy9527** [comment]
我也出现了同样的问题,升级到最新的cli就出现了.
旧的没有这样的问题

**Comment by andycall** [comment]
最新的 0.7.3+2 版本发布产物有些问题，先回滚了。
可以使用 `npm install -g @openkraken/cli` 重新安装一下。
