### ISSUE TITLE
如何更好的实现多个元素的相同动画？

### ISSUE THREAD

**Issue by JuneScut** [openkraken/kraken#309]
## 使用场景 ｜ Use case

如视频所示，我想实现这个动画场景，由于不支持 Animation，我是通过 getElementByClassName 获得多个元素，再通过 transition 属性来实现多个元素的相同动画。但是显然 kraken 并不支持 getElementByCalssName。请问是否有更好的方式支持实现多个元素的相同动画，或者是否能支持下获取多个元素？

## 提案 ｜ Proposal

https://user-images.githubusercontent.com/29206208/117913347-cbcea480-b313-11eb-821b-c6d112d69630.mov

**Comment by andycall** [comment]
不用选择器，用 useRef 不可以吗？

**Comment by JuneScut** [comment]
可以，开始是担心对react的支持程度所以没有考虑到，感谢

**Comment by andycall** [comment]
Kraken 对 React 的支持还没有差到那个地步。。。
