### ISSUE TITLE
动态库ibkraken_jsc.so找不到

### ISSUE THREAD

**Issue by hankedang** [openkraken/kraken#311]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.7.2+4

使用官网中的 flutter 中集成 Kraken的demo失败

错误：
```
E/flutter ( 9946): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libkraken_jsc.so" not found)
E/flutter ( 9946): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter ( 9946): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
```

**Comment by andycall** [comment]
需要先构建 bridge 再运行，

请先阅读官网文档 https://openkraken.com/guide/contribute/environment

**Comment by HCan53** [comment]
> 需要先构建 bridge 再运行，
> 
> 请先阅读官网文档 https://openkraken.com/guide/contribute/environment

如何构建？

**Comment by posuihushui** [comment]
构建之后如何引入？如何运行flutter例子，这个文档有点简单啊。

**Comment by andycall** [comment]
> 构建之后如何引入？如何运行flutter例子，这个文档有点简单啊。

请先看完文档再提出问题

https://openkraken.com/guide/native/interpolation-flutter
https://openkraken.com/guide/contribute/development
