### ISSUE TITLE
请问有没有优雅的方式同时断点 dart 侧和 bridge

### ISSUE THREAD

**Issue by airingursb** [openkraken/kraken#314]
## 使用场景 ｜ Use case

现在只能两端分开断点调试，没有找到好的联调方法，请教下有没有优雅的方式同时断 dart 侧和 bridge

**Comment by andycall** [comment]
可以使用 Android Studio 和 Clion 的 Attach To Process 给一个进程绑定 2 个 debugger，这样就可以同时调试了

**Comment by andycall** [comment]
不过 Dart 的 Debugger 实现会有 bug，可能会遇到 Debugger 闪退的情况
