### ISSUE TITLE
Vuejs <transition> supported

### ISSUE THREAD

**Issue by zishenWang** [openkraken/kraken#316]
## 使用场景 ｜ Use case

支持Vue中的<transition>
## 提案 ｜ Proposal
kraken目前只支持样式内联，不支持css类的写法，影响<transition>标签的使用，虽然可以通过内联样式设置相应transition，但是迁移工作还是很多

**Comment by andycall** [comment]
CSS 文本文件确定会支持，不过还需要再等三四个月才能搞完

**Comment by wssgcg1213** [comment]
transition 是完整支持的

CSS 能力 #38

**Comment by zishenWang** [comment]
我知道transition是支持的，但是vue封装的<transition>和<transition-grop>会有问题
