### ISSUE TITLE
如何做到让kraken Android App中的js 日志，输出到devtool console面板上？

### ISSUE THREAD

**Issue by mrme2014** [openkraken/kraken#317]
## 使用场景 ｜ Use case

如何做到让kraken Android App中的js 或native 日志 输出到devtool console面板上？

这样调试的时候查看日志 会更加方便些

**Comment by andycall** [comment]
https://github.com/openkraken/devtools

难道这个不行 ？

**Comment by qingyangmoke** [comment]
> https://github.com/openkraken/devtools
> 
> 难道这个不行 ？

main 分支用不了   重构代码目前还在 inspector分支吧

**Comment by wssgcg1213** [comment]
Related to https://github.com/openkraken/kraken/pull/334
