### ISSUE TITLE
请问会优化在安卓侧的性能？

### ISSUE THREAD

**Issue by JuneScut** [openkraken/kraken#325]
hi, 我在几种场景下测试 kraken 的性能表现，Android 在长列表的性能显然不如 ios, sliver的增强看起来也没有明显优化。请问官方是否有优化 android 侧性能的计划呢？比如接入 quickJS? 若有的话，有计划时间吗？ 
![image](https://user-images.githubusercontent.com/29206208/118259758-19017080-b4e4-11eb-9d8e-c9ac2fa3fa3c.png)

![image](https://user-images.githubusercontent.com/29206208/118259611-f3746700-b4e3-11eb-8572-5e73db2dba3d.png)

**Comment by yuanyan** [comment]
昨天 tsc 会议上的一些结论，后续计划双端 JS 引擎都会切换到 quickjs 或者其他更好的选择

**Comment by JuneScut** [comment]
好的，感谢，请问下有时间安排吗

**Comment by andycall** [comment]
这个事情很重要，这周或者下周就启动

**Comment by andycall** [comment]
@JuneScut 请问测试的 case 代码有吗？

**Comment by JuneScut** [comment]
https://github.com/JuneScut/kraken-performance_test
here, 本地跑的时候用的是 Main 分支 Kraken 代码

**Comment by chenyulun** [comment]
@JuneScut 你拿了hummer的案例吗？

**Comment by JuneScut** [comment]
对的 @chenyulun

**Comment by cnryb** [comment]
@JuneScut 我用你的代码，在安卓上使用 MI NOTE 3 ,  flutter run --release,  进行加载测试，数据比你的好的多。我是那页面上的数字和console中的相减，不知道对不对


|  case  | 时间 |
|  ----  | ----  |
| case1  | 903 |
| case2  | 678 |
| case3  | 787 |
| case4  | 153 |

**Comment by wssgcg1213** [comment]
Hi，quickjs 已经发布两个版本号了，可以使用新版本再测试一下你们的case，此issue暂先close了
