### ISSUE TITLE
input 输入区域支持滑动，支持单击切换光标位置，支持选中文本功能

### ISSUE THREAD

**Issue by ReverseScale** [openkraken/kraken#327]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.7.2+3

### 重现步骤 ｜ Steps To Reproduce

1.input 超出输入框范围，输入区域不能滑动；
2.在输入的文本，点击移动输入光标插入文字时，单击只是展示光标位置变化，需要双击才能在光标位置插入；
3.双击输入的文本没有选中状态，并提示复制粘贴等气泡。

**重现代码 | Code example:** 

```js
const input = document.createElement('input');
input.placeholder = 'Please input something.';
input.style.width = '300px';
input.style.height = '50px';
document.body.appendChild(input);
```

**预期结果 ｜ Expected results:** 
1.超出输入框范围可以滑动；
2.单次点击切换光标位置；
3.双击选中输入文本并弹出气泡工具条。

**实际结果 ｜ Actual results:** 
超出输入框范围不能滑动，单击不能切换光标位置，没有选中文本功能。

**Comment by andycall** [comment]
这些功能都还没有做

**Comment by ReverseScale** [comment]
修复：2.单次点击切换光标位置

**Comment by temper357** [comment]
#496 已实现这些功能
