### ISSUE TITLE
能和vite一起使用吗？

### ISSUE THREAD

**Issue by gcxfd** [openkraken/kraken#337]
https://github.com/vitejs/vite
我尝试用vite，但是发现总是报错

```

❯ kraken http://localhost:3000/src/main.coffee
Execute binary: /Users/z/git/mac/home/.config/yarn/global/node_modules/@openkraken/cli/build/darwin/debug/app.app/Contents/MacOS/app

flutter: Observatory listening on http://127.0.0.1:61225/lCqGNdN5e_E=/
Unexpected token '{'. import call expects exactly one argument.
undefined

flutter: Kraken DevTool listening at ws://192.168.123.86:9222
flutter: Open Chrome/Edge and paste following url to your navigator:
flutter:     devtools://devtools/bundled/inspector.html?ws=192.168.123.86:9222
```

**Comment by wssgcg1213** [comment]
我拿 Vite 的 hello world 试了下, 它的入口不满足 js bundle, 而是使用 innerHTML 直接赋值节点的, Kraken 暂时不支持 innerHTML  

另外你的 main.coffee 的脚手架是怎么样的, 需要提供更多信息.

**Comment by gcxfd** [comment]
> 我拿 Vite 的 hello world 试了下, 它的入口不满足 js bundle, 而是使用 innerHTML 直接赋值节点的, Kraken 暂时不支持 innerHTML

你别看入口那个index.html, 你直接访问/src/main.js
> 
> 另外你的 main.coffee 的脚手架是怎么样的, 需要提供更多信息.

这个coffee其实就是用的/src/main.js
