### ISSUE TITLE
hello-react demo项目热重载失败

### ISSUE THREAD

**Issue by JuneScut** [openkraken/kraken#345]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.7.3

### 重现步骤 ｜ Steps To Reproduce
1. 修改 hello-react 的构建配置config/webpackDevServer.config.js ，增加 writeToDisk: true，使得dev开发时的 js 文件输出到硬盘
2. 命令行执行 kraken http://localhost:3000/static/js/bundle.js
3. 修改文本保存，热重载
出现如下错误
![image](https://user-images.githubusercontent.com/29206208/118915717-21ccc900-b960-11eb-97cd-29b89387cd37.png)
请问是否能帮忙排查下是什么缘故？此为打包出来的文件列表：
![image](https://user-images.githubusercontent.com/29206208/118915783-46c13c00-b960-11eb-89db-9ec2686c667d.png)

**Comment by yuanyan** [comment]
@JuneScut 这个问题是否已经解决？

**Comment by andycall** [comment]
和这个重复了 https://github.com/openkraken/kraken/issues/184，先 close 掉
