### ISSUE TITLE
flutter run --profile  ios真机调试失败（虚拟机运行成功）

### ISSUE THREAD

**Issue by llggyy233** [openkraken/kraken#346]
### 重现步骤 ｜ Steps To Reproduce

flutter run -- profile

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 
真机安装成功

**实际结果 ｜ Actual results:** 
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Automatically signing iOS for device deployment using specified development team in Xcode project: U68F2T6B39
Running Xcode build...                                                  
Xcode build done.                                            8.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    ld: '/Users/llggyy233/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/kraken_websocket-0.1.1/ios/libkraken_websocket_jsc.dylib' does not
    contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or
    disable bitcode for this target. file
    '/Users/llggyy233/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/kraken_websocket-0.1.1/ios/libkraken_websocket_jsc.dylib' for
    architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Could not build the precompiled application for the device.

**Comment by andycall** [comment]
需要在 Xcode 中关闭 BitCode

https://developer.apple.com/forums/thread/3991

**Comment by xmsz** [comment]
已经在xcode中关闭了bitCode 但还是报错这么解决
![image](https://user-images.githubusercontent.com/5879146/125596180-2de90a0f-28c8-471d-a054-68becb294a3b.png)
![image](https://user-images.githubusercontent.com/5879146/125596200-c6f05475-86b9-4436-9d36-bf47e41d271d.png)
