### ISSUE TITLE
支持 HTML 文本格式

### ISSUE THREAD

**Issue by andycall** [openkraken/kraken#348]
现在 Kraken 只支持使用 DOM API 来创建页面，这对于支持使用 HTML 生成的前端框架来说，并不是特别高效。

**Comment by answershuto** [comment]
初步结论：通过实现 HTML 结构的解析来优化首屏。

**Comment by anjihang** [comment]
是否需要考虑处理<noscript>标签

**Comment by answershuto** [comment]
> 是否需要考虑处理noscript标签

目前 Kraken 只支持 JavaScript 并且没有禁用脚本单纯渲染的功能。

**Comment by anjihang** [comment]
> > 是否需要考虑处理noscript标签
> 
> 目前 Kraken 只支持 JavaScript 并且没有禁用脚本单纯渲染的功能。

我的意思是：是否应该过滤掉 noscript 标签，因为我现在测试加载html，noscript标签内的内容会被展示出来。
