### ISSUE TITLE
完善 input 功能

### ISSUE THREAD

**Issue by yuanyan** [openkraken/kraken#35]
当前只实现了最基本的输入能力，与 Web 还有不少差距需要补齐

**Comment by wangyunlong0418** [comment]
Input设置高度之后，没有起到作用
![image](https://user-images.githubusercontent.com/27914380/116061787-d8b58c00-a6b5-11eb-9f00-50066fbe969b.png)

**Comment by Ryan-Shz** [comment]
maxlength 和 type="password" 不生效，input事件e.target.value取不到值。
