### ISSUE TITLE
讨论下 Kraken 下的 xhr 是否还需要遵循跨域的安全策略？

### ISSUE THREAD

**Issue by airingursb** [openkraken/kraken#354]
https://github.com/openkraken/kraken/blob/286396a0f2f706a040926f55fc9dede428548181/bridge/polyfill/src/xhr.ts#L26-L47

bridge 中关于 xhr 的一个 polyfill 是 copy 自 web 浏览器的实现的，但是 Kraken 本质上是 Dart 发起的 native request，不再有跨域限制，个人以为这一段 polyfill 中的 forbiddenHeaders 是可以直接删掉的。

**Comment by andycall** [comment]
嗯，我个人觉得同源策略在 kraken 不需要
