### ISSUE TITLE
document 代理的事件无法被处理

### ISSUE THREAD

**Issue by airingursb** [openkraken/kraken#360]
### 重现步骤 ｜ Steps To Reproduce

document 无法代理事件，kraken 的事件貌似只能代理到 body 上，无法继续向上了。
因此，在 React 16 及其之前的版本上，所有的 element 绑定的事件都无法被 kraken 处理，因为它们都被绑定到 document 上了。

**重现代码 | Code example:** 

```
document.addEventListener('click', function(e) {
    console.log('document click');
});
```

或者 hello-react 项目，将 react 版本换成 16.8.6，在某个 dom 上绑定 onClick。

**预期结果 ｜ Expected results:** 
有日志输出

**实际结果 ｜ Actual results:** 
无日志输出

**Comment by answershuto** [comment]
我来看下

**Comment by jardenliu** [comment]
说实话这玩意应该还没有好的开发体验吧

**Comment by andycall** [comment]
现在 Kraken 还处于早期版本，开发体验肯定是无法和成熟的平台相比较的
