### ISSUE TITLE
[喜报] 🎉🎉🎉vite 成功编译并运行 

### ISSUE THREAD

**Issue by Hareis** [openkraken/kraken#376]
#上截图
![image](https://user-images.githubusercontent.com/11290701/120131261-a4744480-c1fa-11eb-80fc-09f5b21a3ccb.png)

``vite.config.js``配置如下

```
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";

// https://vitejs.dev/config/
export default defineConfig({
  mode:"ios13",
  build: {
    
    rollupOptions: {
      output: {
        entryFileNames: "dist/app.js",
        format: 'umd',
      },
    },
  },
  plugins: [vue()],
});

```

上面的配置我也是瞎折腾 并不太清楚具体的含义，
尝试在vue文件中使用import css 运行时失败 ``flutter: ERROR: unexpected element type "STYLE"``

具体应该还是flutter的问题 不能识别资源文件

继续进一步尝试中，后面会继续跟进

**Comment by andycall** [comment]
nice work

**Comment by q2578443177** [comment]
nice

**Comment by answershuto** [comment]
666
