### ISSUE TITLE
Kraken 0.7.3 WebView无法滚动问题

### ISSUE THREAD

**Issue by zjutwhw** [openkraken/kraken#379]
Kraken：0.7.3
测试：iOS14.0 模拟器

### 重现步骤 ｜ Steps To Reproduce
`const iframe = document.createElement('iframe');
iframe.setAttribute(
    'src',
    'https://dev.g.alicdn.com/kraken/kraken-demos/todomvc/build/web/index.html'
);
iframe.style.width = '360px';
iframe.style.height = '375px';
document.body.appendChild(iframe);`

问题：WebView正常加载，点击事件也正常，但是不法正常滚动WebView

**Comment by andycall** [comment]
优酷也反馈过此类问题，可以高优看一下

**Comment by yuanyan** [comment]
应该是事件被阻断了，没有传递下去
