### ISSUE TITLE
文本 automatic minimum size 计算与浏览器不一致

### ISSUE THREAD

**Issue by temper357** [openkraken/kraken#401]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

main

### 重现步骤 ｜ Steps To Reproduce

在 flex 布局中对于 flex-grow/flex-shrink 的计算[算法](https://www.w3.org/TR/css-flexbox-1/#resolve-flexible-lengths)中涉及到对计算出的 target main size 与 flex item 的  [Automatic Minimum Size](https://www.w3.org/TR/css-flexbox-1/#min-size-auto) 作比较，对于文本来说浏览器是根据换行符来拆分文本算出 automatic minimum size，因此对于不同的文本 minimum size 可能不一样，例如以下示例：

```js
var div = document.createElement('div');
div.style.display = 'flex';
div.style.width = '100px';
div.style.border = '1px solid #0F0';
var span = document.createElement('span');
span.style.flexGrow = 1;
span.style.flexShrink = 1;
span.style.flexBasis = 0;
var text = document.createTextNode('哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈');
span.appendChild(text);
div.appendChild(span);
var img = document.createElement('img');
img.style.height = '50px';
img.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkAQMAAABKLAcXAAAABlBMVEX1CAD////Q9ly2AAAAhUlEQVQ4y93TMQ6AIAwF0BIHRo/AUTyaHM2jeARGBoNSkvqNkBASh8YO/rzR9kOqZjllth8pmqc8OSgRWSgSGSjkEL3D53C3KM8sSiwrOlhTW5FlRIFFbe1Fa0v85RyWL3IqNPwPnb109onNd2+Ea+LSzRYg0J66WWhd1Ui0Vc/L+Vaa5gJ+8ifpfqdy4gAAAABJRU5ErkJggg==';
div.appendChild(img);

document.body.appendChild(div);
```
**浏览器效果**
![image](https://user-images.githubusercontent.com/5419233/121135673-51883600-c867-11eb-84d9-cf3efdbba39b.png)

将文本替换后效果为：
![image](https://user-images.githubusercontent.com/5419233/121136076-cf4c4180-c867-11eb-877a-dc7ba21a81e7.png)
![image](https://user-images.githubusercontent.com/5419233/121136133-e12de480-c867-11eb-8739-95db6113df66.png)

**Kraken结果**

Kraken 缺少对于文本换行符的判断，对于文本的 automatic minimum size 统一是按不换行处理：
![image](https://user-images.githubusercontent.com/5419233/121135801-71b7f500-c867-11eb-856a-f7b8289b8a7d.png)
![image](https://user-images.githubusercontent.com/5419233/121136356-23efbc80-c868-11eb-8465-06e15045915e.png)
![image](https://user-images.githubusercontent.com/5419233/121136297-10dcec80-c868-11eb-854e-0e1371964955.png)

**Comment by cnryb** [comment]
fixed in #980
