### ISSUE TITLE
start example fail

### ISSUE THREAD

**Issue by chenzefeng09** [openkraken/kraken#42]
按照readme启动example时，执行flutter run 失败。报错如下 ：

../lib/src/gesture/scroll_position_with_single_context.dart:37:7: Error: The non-abstract class 'ScrollPositionWithSingleContext' is missing implementations for these members:
 - ViewportOffset.hasPixels
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ScrollPositionWithSingleContext extends ScrollPosition implements ScrollActivityDelegate {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/rendering/viewport_offset.dart:96:12: Context: 'ViewportOffset.hasPixels' is defined here.
  bool get hasPixels;
           ^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/chenzefeng/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/chenzefeng/Development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

**Comment by andycall** [comment]
需要 flutter 1.22 以上版本

**Comment by yuanyan** [comment]
`Flutter version in the kraken/pubspec.yaml`

**Comment by chenzefeng09** [comment]
安装后报错：

E/DartVM  (29022): vm-service: Error: Unhandled exception:
E/DartVM  (29022): WebSocketException: Invalid WebSocket upgrade request
E/DartVM  (29022):
E/flutter (29022): [ERROR:flutter/runtime/dart_isolate.cc(882)] Unhandled exception:
E/flutter (29022): WebSocketException: Invalid WebSocket upgrade request
Error connecting to the service protocol: failed to connect to
http://127.0.0.1:55543/ufXtD_4_LD0=/

**Comment by yuanyan** [comment]
重新安装下指定版本的 Flutter

**Comment by chenzefeng09** [comment]
flutter 的版本已经切到1.22.0了
![image](https://user-images.githubusercontent.com/7556537/111113418-b3a10a00-859c-11eb-8bcd-877ea756e35f.png)

**Comment by xmsz** [comment]
```
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (4 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
```

同样的错误

**Comment by abdulhamidalokzai** [comment]
@chenzefeng09 have you solved the problem?

**Comment by andycall** [comment]
flutter 2.0 现在还不支持，请切换到 1.22.4 版本
