### ISSUE TITLE
 js层瞬间插入1000个不同的image，在ios场景一下回触发异常“Connection failed (OS Error: Too many open files, errno = 24),”

### ISSUE THREAD

**Issue by pba-cra** [openkraken/kraken#437]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

v0.7

### 重现步骤 ｜ Steps To Reproduce

构造1000 image资源使用不同的图片，添加到节点上，会出现这个异常。

**重现代码 | Code example:** 
   const icon = document.createElement('img');
    icon.style.width = '40px';
    icon.style.height = '14px';
    icon.style.position = 'relative';
    icon.caching = 'store';
    icon.src='图片链接';
    document.body.appendChild.appendChild(icon);

**问题应该是CachedNetworkImage的fetchFile，并发大量的_httpClient，导致句柄被吃完。
是否考虑图片加载应该有队列进行缓冲或者引入三方的图片加载库。**

**预期结果 ｜ Expected results:** 
 1000个图片能够被加载完成，不会出现异常

**实际结果 ｜ Actual results:** 

Connection failed (OS Error: Too many open files, errno = 24),
大量的这个异常被抛出。
堆栈是：
`
Image provider: CachedNetworkImage()

Image key: CachedNetworkImage()
`

**Comment by yuanyan** [comment]
应该是本地io导致的

**Comment by burtonsun** [comment]
恩，知道的。
不知道flutter好久能解决这些问题，如果flutter不解决，kraken也不解决。那就只有使用方来进行模改了，对接解决了。

**Comment by andycall** [comment]
![image](https://user-images.githubusercontent.com/4409743/125389506-e2f14780-e3d3-11eb-98f6-b357482ebd54.png)

浏览器也会控制最大图片并发数量，我们也应该处理这种情况

**Comment by yuanyan** [comment]
可以在 Kraken 里控制下并发
