### ISSUE TITLE
前端vue代码无法获取 kraken对象

### ISSUE THREAD

**Issue by sisychen** [openkraken/kraken#451]
### 使用的 Kraken 版本0.7.3+2
node版本 v12.16.2

前端Vue代码已执行 npm install -g @openkraken/cli 成功
@openkraken/cli@0.8.0
updated 1 package in 11.218s

但是在node_modules目录下没有找到kraken.js文件

官网里面有说明  Kraken 在 JS 环境中添加了 kraken 的全局对象，在这个全局对象上有 kraken.methodChannel 对象，用于实现和 Native 的消息通信。链接是：https://openkraken.com/guide/advanced/communicate-with-native

**Comment by wssgcg1213** [comment]
`kraken` 对象是全局对象, 直接访问即可, 不需要引入任何 npm 包

**Comment by sisychen** [comment]
这段代码放到vue项目中，
kraken.methodChannel.invokeMethod('somemethod', 'parameter 1', ['parameter 2'], {
                  value: 'parmeter3',
              }).then(result => {
                  console.log('data from native', result);
              }).catch(err => {
                  console.log('some error occured', err);
              });
编译后会报错如下：
ERROR  Failed to compile with 1 error                                                                                                                                                        3:12:48 PM

 error  in ./src/App.vue

Module Error (from ./node_modules/eslint-loader/index.js):

/Users/xxx/Desktop/study/kraken/samples-main/demos/hello-vue/src/App.vue
  64:11  error  'kraken' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)

**Comment by andycall** [comment]
这是 typescript 类型错误，添加 ```@ts-ignore``` 忽略一下

**Comment by sisychen** [comment]
绕过之后编译js文件成功，但是执行事件还是会报错 kraken is not defined
runtime-core.esm-bundler.js?5c40:217 Uncaught ReferenceError: kraken is not defined
    at Proxy.onClick (App.vue?3dfd:92)
    at Object.onClick._cache.<computed>._cache.<computed> (App.vue?3dfd:38)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:163)
    at HTMLDivElement.invoker (runtime-dom.esm-bundler.js?830f:367)


有什么方式可以查看kraken是否在vue项目中存在？
