### ISSUE TITLE
Android 平台第二次进入页面会引发 libkraken_jsc.so crash

### ISSUE THREAD

**Issue by MrLiBack** [openkraken/kraken#456]
使用首页集成的安卓客户端sdk 第二次打开测试页面会出现动态库so错误

**Comment by andycall** [comment]
请问是什么错误？

**Comment by MrLiBack** [comment]
首次加载测试页面正常 回退页面后，再加载测试页面会出现错误 下面是错误信息：
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/polaris/polaris:10/QKQ1.190828.002/20.6.10:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-06-30 11:11:52+0800
pid: 13676, tid: 13825, name: 2.ui  >>> com.android.hanweb.flutterdemo <<<
uid: 10858
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x16
Cause: null pointer dereference
    x0  000000723afca100  x1  0000000000000000  x2  00000072b1404b68  x3  0000000000000002
    x4  0000000000000002  x5  0000000000000000  x6  0000000000800000  x7  0000000000000010
    x8  000000000000000e  x9  e55fa49bd2d0dbb2  x10 00000000ffffffff  x11 0000000000000000
    x12 000000723afca000  x13 fffffffffc000000  x14 0000000000000020  x15 0000000000010000
    x16 00000073347a5890  x17 0000007334797e68  x18 000000723e030000  x19 000000723afc46e0
    x20 0000007240ea5b60  x21 00000072a03771b0  x22 0005c5f31585fb03  x23 00000072a037a020
    x24 0000007213a48c90  x25 00000072a0377400  x26 00000072a037a020  x27 ffff000000000000
    x28 ffff000000000002  x29 00000072a03771a0
    sp  00000072a0377150  lr  000000721dc59814  pc  000000721dc59820

backtrace:
      #00 pc 0000000000053820  /data/app/com.android.hanweb.flutterdemo-FYEh8GXBsEqFYkXvmYeL9g==/lib/arm64/libkraken_jsc.so (BuildId: 62c524b86eb8ae981e81d9f9a0d463d9206fc210)
      #01 pc 000000000001b0c0  /data/app/com.android.hanweb.flutterdemo-FYEh8GXBsEqFYkXvmYeL9g==/lib/arm64/libkraken_jsc.so (BuildId: 62c524b86eb8ae981e81d9f9a0d463d9206fc210)
      #02 pc 0000000000143790  /data/app/com.android.hanweb.flutterdemo-FYEh8GXBsEqFYkXvmYeL9g==/lib/arm64/libjsc.so (BuildId: 5144ead17a8b84eafc4d3b53516b954156d85440)
      #03 pc 000000000040c018  /data/app/com.android.hanweb.flutterdemo-FYEh8GXBsEqFYkXvmYeL9g==/lib/arm64/libjsc.so (BuildId: 5144ead17a8b84eafc4d3b53516b954156d85440)
      #04 pc 00000000003f6158  /data/app/com.android.hanweb.flutterdemo-FYEh8GXBsEqFYkXvmYeL9g==/lib/arm64/libjsc.so (BuildId: 5144ead17a8b84eafc4d3b53516b954156d85440)

**Comment by andycall** [comment]
```
backtrace:
#0 pc 0000000000053820 /data/app/com.android.hanweb.flutterdemo-FYEh8GXBsEqFYkXvmYeL9g==/lib/arm64/libkraken_jsc.so (BuildId: 62c524b86eb8ae981e81d9f9a0d463d9206fc210)
```

通过以下命令进行处理之后：

```
➜  bin ./aarch64-linux-android-addr2line -f -C -e ~/Desktop/libkraken_jsc.so 0000000000053820
kraken::binding::jsc::JSPerformanceEntry::getPerformanceEntryPropertyNames()
/Users/kraken/workspace/kraken/bridge/bindings/jsc/KOM/performance.h:153
```

确认为 PerformanceTrack 引发的 crash。这个功能是不应该出现在发布在 pub.dev 的包里面的，不过曾经有个版本混进了这个代码，请问你是用了那个版本？

**Comment by MrLiBack** [comment]
使用的发布最新的  com.openkraken.kraken.sdk.0.8.0+1.zip

**Comment by andycall** [comment]
> 使用的发布最新的 com.openkraken.kraken.sdk.0.8.0+1.zip

这个版本的确有问题，试下刚更新上去的 0.8.0+2

**Comment by MrLiBack** [comment]
好的 谢谢
