### ISSUE TITLE
高刷新率120hz的手机屏幕，跑高性能长列表锁60帧

### ISSUE THREAD

**Issue by Tibbersss** [openkraken/kraken#457]
机型：小米11
功能：[实现一个高性能长列表](https://openkraken.com/guide/advanced/high-performance-list)
描述：手机日常跑120帧，Play Kraken跑高性能长列表滚动时锁定60帧，并且退出Play Kraken回到桌面后，大概率导致桌面和其他应用也锁60帧，约10秒后恢复正常。
![WechatIMG539](https://user-images.githubusercontent.com/10751521/123912365-893e5580-d9af-11eb-9277-2462287991c5.jpeg)

**Comment by wssgcg1213** [comment]
MIUI 有系统自己锁帧的现象, 可以研究一下

**Comment by wssgcg1213** [comment]
好像跟 Flutter 版本有关, 我更新一下版本试试

**Comment by Tibbersss** [comment]
> 好像跟 Flutter 版本有关, 我更新一下版本试试

是的，miui锁帧是锁游戏以及高温状态，我是关闭了所有应用测试并且机温不高Play Kraken就锁帧。更新完踹我，我测一下

**Comment by wssgcg1213** [comment]
还不是, 我实验了一下, 小米机型下面对摄像头开启状态是锁帧的, 包括它自己的拍照 App; 现在的 PlayKraken 第一个页面会用到摄像头, 所以导致系统锁帧, 进入后续页面后, 摄像头的采样貌似并没有结束, 所以继续维持 60fps. 我做一下 play kraken 的修改吧, 让退出扫码页面之后摄像头的 controller 销毁掉。

**Comment by wssgcg1213** [comment]
@Tibbersss https://kraken.oss-cn-hangzhou.aliyuncs.com/play-kraken/PlayKraken.v1.1.0.apk  试试这个版本是否解决了

**Comment by Tibbersss** [comment]
ok ，目测已经到120帧了，只是左下角还是60f/s，
![WechatIMG541](https://user-images.githubusercontent.com/10751521/124111478-e9122a80-da9b-11eb-92c9-4e54500d49b4.jpeg)
