### ISSUE TITLE
对Flutter Widget的注册支持

### ISSUE THREAD

**Issue by xuzhongpeng** [openkraken/kraken#462]
## 使用场景 ｜ Use case

如果只是使用Flutter的渲染能力，使用c++对接skia也是可行的，如果要发挥它在Flutter中更大价值，应该需要支持自定义Flutter组件的注册提供给h5使用

**Comment by yuanyan** [comment]
目标上是通过 Kraken 的插件机制（脚手架与 Flutter 插件一致）注册自定义标签

**Comment by ReverseScale** [comment]
如果支持使用 Flutter Widget （非 Render）实现自定义标签，可以发挥 Flutter 丰富的 UI 生态那就 nice 了

**Comment by xuzhongpeng** [comment]
> 目标上是通过 Kraken 的插件机制（脚手架与 Flutter 插件一致）注册自定义标签

我目前已经实现业务方自行在Flutter侧的方式注册 h5标签的方式 嵌入Flutter的Widget，伪代码：
```dart
void main() {
  KrakenWebsocket.initialize();
  KrakenPlugin.register('switch',MySwitch);
  runApp(MyApp());
}
```
MySwitch是一个需要用于自行实现的Element抽象类，定义抽象类的目的是1. 自行处理属性参数 2. 加入现有的Widget

h5端即可通过标签的方式引入
```JSX
<div>
    <switch data='xxx'></switch>
</div>
```

实现原理是通过RenderObjectToWidgetElement来注册多个顶层Widget树，然后通过Kraken的Element和Widget来进行桥接（为什么使用RenderObjectToWidgetElement是因为只有它可以对BuildOwner进行赋值），桥接是把树的构建、布局、渲染、事件等打通

目前已经基本实现，不知道跟主项目是否有冲突，如果有任何问题，我们可以继续沟通，后面我可以整理代码提个pr
