### ISSUE TITLE
同标签内动态值不会在同一行而是会掉下来

### ISSUE THREAD

**Issue by xmsz** [openkraken/kraken#484]
### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 

```
 <View style={{ flexDirection: 'row' }}>￥{balance}</View>
```

**预期结果 ｜ Expected results:** 
![image](https://user-images.githubusercontent.com/5879146/124908287-c04de000-e01b-11eb-86ae-fd6753051b04.png)

**实际结果 ｜ Actual results:** 
![image](https://user-images.githubusercontent.com/5879146/124908387-d8256400-e01b-11eb-9ba3-8cd2402a7498.png)

**Comment by temper357** [comment]
我测试了下，使用最新 main 上的代码运行你上面给的代码并不会换行，你本地测试下，只保留上面一个 View 看会不会换行？如果不会换行说明是其他代码影响，可以把完整代码发我

**Comment by xmsz** [comment]
> 我测试了下，使用最新 main 上的代码运行你上面给的代码并不会换行，你本地测试下，只保留上面一个 View 看会不会换行？如果不会换行说明是其他代码影响，可以把完整代码发我

那我有时间上传一下

**Comment by xmsz** [comment]
![image](https://user-images.githubusercontent.com/5879146/125432659-3467c242-3ca7-4e60-81a6-5894f6c3c278.png)

- Rax Kraken项目
```
import { createElement } from 'rax';
import View from 'rax-view';

export default function Home() {
  const test = 'test';
  return <View>文字：{test}</View>;
}

```

**Comment by temper357** [comment]
Duplicate of https://github.com/openkraken/kraken/issues/117

换行的原因是 Kraken 目前不会像浏览器一样合并相邻的文本，上面示例中 `文字:` 和 `test` 在 Kraken 中会被视作两个元素，所以在上面第一个例子中 direction 为 row 的 flex 布局中两个文本会水平排版，而在 direction 为 column 的 flex 布局中会竖直排版。
