### ISSUE TITLE
真机ipad mini5 运行master代码失败

### ISSUE THREAD

**Issue by chaim007** [openkraken/kraken#489]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

---- master
---
chaimdeiMac:ios chaim$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G5052c darwin-x64, locale zh-Hans-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

--- ipad mini5 真机 ios 14.6

### 重现步骤 ｜ Steps To Reproduce

--- 按照使用说明运行到flutter run 

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:** 

'/Users/chaim/.pub-cache/hosted/pub.flutter-io.cn/kraken_websocket-0.2.0+1/i
               os/libkraken_websocket_jsc.dylib' does not contain bitcode. You
must rebuild
               it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an
updated
               library from the vendor, or disable bitcode for this target. file

'/Users/chaim/.pub-cache/hosted/pub.flutter-io.cn/kraken_websocket-0.2.0+1/i
               os/libkraken_websocket_jsc.dylib' for architecture arm64
               clang: error: linker command failed with exit code 1 (use -v to
see
               invocation)
[ipad mini 5 真机报错.txt](https://github.com/openkraken/kraken/files/6795008/ipad.mini.5.txt)

**Comment by andycall** [comment]
Xcode 里面的ENABLE_BITCODE 关掉就可以了

**Comment by chaim007** [comment]
> Xcode 里面的ENABLE_BITCODE 关掉就可以了

![image](https://user-images.githubusercontent.com/25498851/125231737-e4f0d300-e30d-11eb-95b4-aa1c1c4f8bdd.png)

已经在xcode关掉了还是装不上,哪个gallery的可以装上上下拖动可以,但是点击没用反应,

**Comment by chaim007** [comment]
ld: '/Users/chaim/.pub-cache/hosted/pub.flutter-io.cn/kraken_websocket-0.2.0+1/ios/libkraken_websocket_jsc.dylib' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/chaim/.pub-cache/hosted/pub.flutter-io.cn/kraken_websocket-0.2.0+1/ios/libkraken_websocket_jsc.dylib' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chaim007** [comment]
kraken_websocket-0.2.0+1/ios/libkraken_websocket_jsc.dylib.  

---这个包有点问题,从代码中去掉 暂时运行ok

**Comment by andycall** [comment]
选中 kraken_websocket，然后关闭 ENABLE_BITCODE，你肯定是选错了

**Comment by xmsz** [comment]
> 选中 kraken_websocket，然后关闭 ENABLE_BITCODE，你肯定是选错了

在哪选中kraken_websocket关闭ENABLE_BITCODE
![image](https://user-images.githubusercontent.com/5879146/125584743-e76f5505-74b2-4c50-84ec-2f8a8450738c.png)

**Comment by andycall** [comment]
![image](https://user-images.githubusercontent.com/4409743/125597524-329b6be0-cd38-46f7-a148-739aa7926a04.png)

**Comment by xmsz** [comment]
@andycall 原来我打开的是`Runner.xcodeproj`，怪不得没看到这些配置
