### ISSUE TITLE
支持 HotReload 热更新

### ISSUE THREAD

**Issue by xmsz** [openkraken/kraken#492]
## 使用场景 ｜ Use case
- 使用Rax项目
- 保存代码触发刷新/热更新
- 目前Kraken预览界面会直接闪退
- 这样调试和预览太麻烦了

## 提案 ｜ Proposal
- 支持刷新/热更新时预览界面不闪退

**Comment by answershuto** [comment]
![image](https://user-images.githubusercontent.com/17812136/125445188-c39e42d2-ba18-41e7-b2ee-b82a3a6f40c5.png)
看起来 hot reload 的时候会导致 bridge 的 crash。

**Comment by answershuto** [comment]
全局 hot reload 已支持，还需研究下 HMR 看看需要对其哪些能力。

**Comment by answershuto** [comment]
#184
