### ISSUE TITLE
flutter: Warning: kraken_devtools is not supported on your platform

### ISSUE THREAD

**Issue by jeromehan** [openkraken/kraken#495]
### 重现步骤 ｜ Steps To Reproduce

最新库 npm run start

**预期结果 ｜ Expected results:** 
kraken_devtools run

**实际结果 ｜ Actual results:** 
An Observatory debugger and profiler on iPhone 11 Pro Max is available at:
http://127.0.0.1:56925/S10QAp4Rdhk=/
flutter: Warning: kraken_devtools is not supported on your platform.
The Flutter DevTools debugger and profiler on iPhone 11 Pro Max is available
at:
http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A56925%2FS10QAp4Rdhk%3D%2F
Application finished.

**Comment by andycall** [comment]
受苹果限制，iOS 平台下不支持 kraken_devtools。
