### ISSUE TITLE
软键盘收起UI渲染异常

### ISSUE THREAD

**Issue by tylorvan** [openkraken/kraken#499]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

master

### 重现步骤 ｜ Steps To Reproduce

页面打开后软键盘收起UI渲染异常

**重现代码 | Code example:** 

feature/resize_err

**预期结果 ｜ Expected results:** 

展示正常

**实际结果 ｜ Actual results:** 

https://user-images.githubusercontent.com/5905365/125739104-1971aa8a-ea13-4000-89b3-4ecd273962d0.mp4

**Comment by temper357** [comment]
已验证 feature/resize_err 分支合并最新的 main 问题消失。
