### ISSUE TITLE
tag 0.8 依赖的 kraken_devtools 版本存在问题

### ISSUE THREAD

**Issue by airingursb** [openkraken/kraken#505]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

kraken: 0.8.0 （commit：17788766）
kraken_devtools: ^0.2.0-dev.1

### 重现步骤 ｜ Steps To Reproduce

执行 `flutter build macos --build`

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

编译通过。

**实际结果 ｜ Actual results:** 

编译不通过，kraken_devtools 存在问题：

```
../../../../../env/flutter_macos_2.2.2-stable/.pub-cache/hosted/pub.dartlang.org/kraken_devtools-0.2.2/lib/inspector/modules/dom.dart:47:44: Error: The getter 'elementDelegate' isn't defined for the class 'RenderBoxModel'.
 - 'RenderBoxModel' is from 'package:kraken/src/rendering/box_model.dart' ('../lib/src/rendering/box_model.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'elementDelegate'.
      int targetId = lastHitRenderBoxModel.elementDelegate.getTargetId();
                                           ^^^^^^^^^^^^^^^              
```

kraken_devtools 的版本改成 0.2.1 可以编译通过。

**Comment by andycall** [comment]
使用 0.8.1 版本就可以了

**Comment by airingursb** [comment]
@andycall 麻烦 0.8.1 触发下 cli 的更新吧，现在 cli 还是 0.8.0

https://www.npmjs.com/package/@openkraken/cli
