### ISSUE TITLE
Macos启动调试过程报错 DartWorker (25): EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by xuzhongpeng** [openkraken/kraken#521]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.8.0

### 重现步骤 ｜ Steps To Reproduce

使用`npm run build:bridge:macos`生成产物，在macos中软链接到产物，启动正常✅

使用[开发与调试文档](https://openkraken.com/guide/contribute/development)中的『调试 Bridge 代码』，第二步生成的产物，在macos中软链接到产物，跑起来报错（表现为闪退）❌

目前Clion Cmake的配置如下
![WX20210722-142255](https://user-images.githubusercontent.com/24218764/126597576-5b390548-5dba-4ba6-810f-acd1f652cc26.png)

报错如下
![image](https://user-images.githubusercontent.com/24218764/126597554-c0275b2e-3149-4b62-b989-1268f365a965.png)

**Comment by andycall** [comment]
看上去和 kraken_devtools 有关

**Comment by andycall** [comment]
我想起来了，文档的方式存在问题，因为使用

```
npm run build:bridge:macos
```
回修改动态链接库里面 jsc 的依赖。

**Comment by andycall** [comment]
最新文档已经更新

**Comment by xuzhongpeng** [comment]
如果不修改`kraken/kraken/macos/libkraken_jsc.dylib`软链接到`kraken/bridge/cmake-build-debug/libkraken_jsc.dylib`那么文档第二步的作用是啥

**Comment by andycall** [comment]
自动生成 cmake Applications

**Comment by xuzhongpeng** [comment]
感谢 已经成功跑起来了
