### ISSUE TITLE
Example failed to run with ENOENT - No such file or directory @ rb_check_realpath_internal - .kraken_bridge.framework

### ISSUE THREAD

**Issue by MIFind** [openkraken/kraken#53]
Report
What did you do?
ℹ example : `flutter run` **or** `pod install`

What did you expect to happen?
ℹ with no error

What happened instead?
Errno:: ENOENT - No such file or directory @ rb_check_realpath_internal - ../kraken/kraken/example/ios/.symlinks/plugins/kraken/ios/kraken_bridge.framework

> CocoaPods Environment
```
CocoaPods : 1.10.1
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
    RubyGems : 3.2.5
        Host : macOS 11.2.1 (20D74)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : ~/.rvm/rubies/ruby-2.7.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

> Flutter Environment
```
    • Flutter version 1.22.6 at ~/flutter
    • Framework revision 9b2d32b605 (7 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
```

**Comment by wssgcg1213** [comment]
Waiting for #44 to be merged.

**Comment by andycall** [comment]
缺少了 kraken 的bridge

README 上的文档有问题，需要等这个 #44 合入了再看下 README。

**Comment by MIFind** [comment]
> 缺少了 kraken 的bridge
> 
> README 上的文档有问题，需要等这个 #44 合入了再看下 README。

1
