### ISSUE TITLE
支持 CSS 伪类选择器

### ISSUE THREAD

**Issue by xmsz** [openkraken/kraken#533]
## 使用场景 ｜ Use case
- web有很多&:active的触发效果
- 我在iOS模拟器和Kraken命令中没看到效果，不确定真机是否可行
- 感觉如果&:active不支持的话，是不是这类的都不支持，例如hover active link ...

## 提案 ｜ Proposal

- 支持此类选择器

**Comment by andycall** [comment]
伪类选择器还没有支持

**Comment by xmsz** [comment]
> 伪类选择器还没有支持

ok

**Comment by yuanyan** [comment]
很长一段事情，css选择器可能只会支持 `.class {}`，这主要还是从渲染性能、可读性与易用性上权衡考量，所以暂时close这个issue
