### ISSUE TITLE
invokeMethod如何可以支持同步返回

### ISSUE THREAD

**Issue by xmsz** [openkraken/kraken#535]
## 使用场景 ｜ Use case

- 需求实现 https://developers.weixin.qq.com/miniprogram/dev/api/base/system/wx.getSystemInfoSync.html 
- 我用invokeMethod可以实现Async异步版本，但是不知道这么实现同步版本
- 实现同步版本是有些场景需要
- 例如我有个函数没办法变成promise或者使用异步调用，所以想通过同步的接口是实现（阻塞也没事）

## 提案 ｜ Proposal

- 如何实现同步返回

**Comment by andycall** [comment]
https://github.com/openkraken/kraken/issues/132

**Comment by xmsz** [comment]
> #132
> 
> 还没有支持，我们最近实现一下

ok 期待
