### ISSUE TITLE
使用vue开发热加载功能

### ISSUE THREAD

**Issue by GetemJay** [openkraken/kraken#539]
## 使用场景 ｜ Use case
使用vue开发

## 提案 ｜ Proposal
每次修改都需要npm run build好麻烦啊 有没有方便点的开发方式呢？可以热加载的那种
还有我发现 Kraken(bundleURL: 'XXXXX')这个地址只能是80端口的 其他端口加载不出来 这是为啥呢。。

**Comment by answershuto** [comment]
HMR 功能已经在看了

**Comment by GetemJay** [comment]
> HMR 功能已经在看了

大佬 Kraken(bundleURL: 'XXXXX')这个地址只能是80端口的是吧，还有有没有提供相对路径的方法呢

**Comment by andycall** [comment]
其他的端口也是可以的，这块没有限制

**Comment by answershuto** [comment]
端口没有限制，看一下你的 bundle 地址在浏览器里面是否可以正常访问。

**Comment by GetemJay** [comment]
> 端口没有限制，看一下你的 bundle 地址在浏览器里面是否可以正常访问。

vue的dev server起的服务 浏览器地址栏可以访问 但是放进Kraken就不可以，但是直接用http-server启动的服务就是正常的

**Comment by answershuto** [comment]
应该是能正常拉取文件然后报错了吧？如果默认带上 HMR 的话，会找不到 window.self 而白屏的，这个我在 HMR 的分支中已经在改了。

**Comment by yuanyan** [comment]
其他端口的文件应该不是相同文件吧，大概率是报错所以没有显示内容

**Comment by GetemJay** [comment]
> 应该是能正常拉取文件然后报错了吧？如果默认带上 HMR 的话，会找不到 window.self 而白屏的，这个我在 HMR 的分支中已经在改了。

用最新的sample vue代码，bundleURL设置成dev server起来的js，依旧黑屏
Kraken kraken = Kraken(bundleURL: 'http://localhost:1024/js/app.js')
@answershuto
