### ISSUE TITLE
启动页面时的参数传递

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#553]
## 使用场景 ｜ Use case
目前北海的加载方式有三种

```
kraken.loadPath(xxx)
kraken.loadURL(xxx)
kraken.loadContent(xxx)
```
很多场景都需要根据参数去请求数据，以便动态化的渲染。但三种方式都没有找到对参数传递的描述。

## 提案 ｜ Proposal
请求支持。
例如

```
kraken.loadPath(xxx, param)
kraken.loadURL('xxx?q=123&k=v')
kraken.loadContent(xxx, param)
```

**Comment by andycall** [comment]
请求需要带有 querystring 的话，可以提前处理好然后拼接到 URL 上面

**Comment by cnryb** [comment]
如果使用的是 `kraken.loadURL(xxx)` ，拼接到URL上面querystring，在北海的js 中是可以拿到的吗？
那如果使用的是 `kraken.loadContent(xxx)` 或 `kraken.loadPath(xxx)` 应该怎么解决？

**Comment by xmsz** [comment]
> 如果使用的是 `kraken.loadURL(xxx)` ，拼接到URL上面querystring，在北海的js 中是可以拿到的吗？

我现在就是用这样的方式 因为xxx本身就是个url

**Comment by JuneScut** [comment]
请问北海的 js 中是怎么拿到的呢？
window 上的属性只有 ["eventTargetId","addEventListener","removeEventListener","dispatchEvent","__kraken_clear_event_listeners__","devicePixelRatio","colorScheme","__location__","window","history","parent","scrollX","scrollY","_unRejectEvt","HTMLIFrameElement"]

__location__ 上只有 reload

**Comment by andycall** [comment]
location.href

**Comment by JuneScut** [comment]
但是北海里边似乎没这个属性？

**Comment by answershuto** [comment]
![image](https://user-images.githubusercontent.com/17812136/128299943-d3acd3d6-f83f-498e-a15f-dabfb09b222b.png)

**Comment by cnryb** [comment]
@answershuto 使用 kraken.loadContent(xxx) 和 kraken.loadPath(xxx) 方式加载的，不考虑解决一下传参问题吗？

**Comment by answershuto** [comment]
可以通过 querystring 的方式拿到的，content 如果是需要传递给前端，可以通过将字符串拼接到全局变量或者通过 channel 传递参数等方式来实现，我理解这是一个业务上的选择，kraken 本事不应该直接提供独立的 api 来传递参数。

**Comment by cnryb** [comment]
1、从js 字符串中渲染的方式，倒是可以通过拼接全局变量的方式来解决。只是感觉不够优雅，有没有更好的方式呢？
2、从 app 本地文件加载渲染的方式，目前还没有解决方案。
App中自己开发JS bundle缓存的时候，都可能会用的到。
@answershuto
