### ISSUE TITLE
Kraken Playground App扫码之后背景色是黑色 看不到内容

### ISSUE THREAD

**Issue by LittleMoonkk** [openkraken/kraken#554]
Kraken Playground App扫码之后背景色是黑色 看不到内容

**Comment by cnryb** [comment]
1、可能码地址中的js bundle有问题，导致无法解析

**Comment by LittleMoonkk** [comment]
> 1、可能码地址中的js bundle有问题，导致无法解析
> 2、可能码地址不可达，被防火墙拦了

用的官网给的码：https://openkraken.com/guide/basic/style

**Comment by cnryb** [comment]
我看 playground 的源代码中已经解决了这个问题。
你拿源码重新编译一下能解决了。

**Comment by answershuto** [comment]
@andycall  这个修复的版本发布 APP 了吗？
