### ISSUE TITLE
关于CI的问题

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#558]
## 使用场景 ｜ Use case
从源码中可以看到目前北海的CI跑在你们自己的机器上的。这样会有两个问题。
- CI机器中的环境对于其它开发者来说不透明
- 对于fork的代码无法启用CI，因为无法模拟出相同的CI环境

## 提案 ｜ Proposal
建议使用 GitHub action 提供的虚拟机来执行CI。  
虽然配置没自己的机器好，但对于开源项目来说是完全免费的。  
也能让其它开发者，根据CI配置设定自己的开发环境。

**Comment by andycall** [comment]
执行 CI 需要的条件还比较苛刻：

1. macOS 系统，还需要有个显示器，因为 flutter 在 macOS 上还没有 headless 模式。
2. Intel 系的 GPU 显卡。

目前最好的方式就是你们提交一个 WIP 的 PR，然后我们为你们执行 CI。

或许我们应该研究一下如何在集成测试上开启软件渲染(--skia-deterministic-rendering)，这样就可以直接在任何一个 macOS 机器上测试了
