### ISSUE TITLE
example run 失败

### ISSUE THREAD

**Issue by devjiangzhou** [openkraken/kraken#574]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.8.1

### 重现步骤 ｜ Steps To Reproduce

➜  example git:(main) ✗ flutter run
Launching lib/main.dart on iPhoneX in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Automatically signing iOS for device deployment using specified development team in Xcode project: 4KSMJ2MECG
Running Xcode build...
 └─Compiling, linking and signing...                         3.1s
Xcode build done.                                           19.5s
(lldb) dyld: dependent dylib '@rpath/libgumbo_parse.dylib' not found for '/private/var/containers/Bundle/Application/E2AAB970-C5D3-4FF8-8432-EEB94A764F9F/Runner.app/Frameworks/kraken_bridge.framework/kraken_bridge', tried but didn't find: '/xxxxxx/Documents/tools/kraken/bridge/build/ios/lib/arm64/libgumbo_parse.dylib' '/private/var/containers/Bundle/Application/E2AAB970-C5D3-4FF8-8432-EEB94A764F9F/Runner.app/Frameworks/libgumbo_parse.dylib' '/private/var/containers/Bundle/Application/E2AAB970-C5D3-4FF8-8432-EEB94A764F9F/Runner.app/Frameworks/Frameworks/libgumbo_parse.dylib' '/Users/kraken/workspace/plugins/packages/kraken_websocket/bridge/kraken/lib/ios/libgumbo_parse.dylib' '/usr/lib/swift/libgumbo_parse.dylib' '@rpath/libgumbo_parse.dylib' '/usr/local/lib/libgumbo_parse.dylib' '/usr/lib/libgumbo_parse.dylib'
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x0000000100fa53e8 dyld`__abort_with_payload + 8
dyld`__abort_with_payload:
->  0x100fa53e8 <+8>:  b.lo   0x100fa5404               ; <+36>
    0x100fa53ec <+12>: stp    x29, x30, [sp, #-0x10]!
    0x100fa53f0 <+16>: mov    x29, sp
    0x100fa53f4 <+20>: bl     0x100fa39e8               ; cerror_nocancel
Target 0: (Runner) stopped.
Installing and launching...                                        21.4s

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

run success

**实际结果 ｜ Actual results:** 
failed

**Comment by andycall** [comment]
@answershuto 得把 gumbo_parse 编译成静态库文件

**Comment by devjiangzhou** [comment]
@andycall @answershuto 两位大佬，iOS run 起来，但是使用 CLion 调试 bridge 时发生的错误如下
/Users/xxxx/Documents/tools/kraken/kraken/example/build/macos/Build/Products/Debug/kraken_example.app
dyld: Library not loaded: @rpath/libkraken_jsc.dylib
  Referenced from: /Users/xxxx/Documents/tools/kraken/kraken/example/build/macos/Build/Products/Debug/kraken_example.app/Contents/Frameworks/libkraken_devtools_jsc.dylib
  Reason: no suitable image found.  Did find:
	/Users/xxxx/Documents/tools/kraken/kraken/example/build/macos/Build/Products/Debug/kraken_example.app/Contents/MacOS/../Frameworks/libkraken_jsc.dylib: mach-o, but wrong architecture
	/Users/xxxx/Documents/tools/kraken/kraken/example/build/macos/Build/Products/Debug/kraken_example.app/Contents/MacOS/../Frameworks/libkraken_jsc.dylib: mach-o, but wrong architecture
Signal: SIGABRT (signal SIGABRT)

![image](https://user-images.githubusercontent.com/1578465/128832663-00ffc223-37fb-446a-9569-629e1b71b69d.png)
![image](https://user-images.githubusercontent.com/1578465/128832714-9f8776e0-7ac6-4a3a-9295-45f2cd130d3e.png)
![image](https://user-images.githubusercontent.com/1578465/128832793-a0e52eda-7de7-4534-a83a-d37c99902c3d.png)
