### ISSUE TITLE
网络拦截器默认返回会导致 xhr 的用例跑不过

### ISSUE THREAD

**Issue by answershuto** [openkraken/kraken#581]
默认返回后用例的 status 看起来与预期不符了。
http://openkraken.com/guide/advanced/network-intercept

**Comment by wssgcg1213** [comment]
哪个用例可以提供一下

**Comment by answershuto** [comment]
xhr.ts

**Comment by wssgcg1213** [comment]
为什么加入拦截器之后会触发这个问题: 因为 contextID remove Header 的操作触发了 async error, 进而在 FetchModule 中进入了 catchError 的 cause, PR 里 @yuanyan 的 #543 和 HttpCache Feature 的 #580 都已经修复这个问题, 等合入即可
