### ISSUE TITLE
READM.md 中加上官网链接？

### ISSUE THREAD

**Issue by hydra1983** [openkraken/kraken#582]
## 使用场景 ｜ Use case

需要通过 github repository 直接链接到官网。

## 提案 ｜ Proposal

在 README.md 或项目描述中加入官网链接。

**Comment by answershuto** [comment]
![image](https://user-images.githubusercontent.com/17812136/128966295-1c1b146d-a525-46ce-be03-1ee150be6215.png)

右边有的

**Comment by wssgcg1213** [comment]
@hydra1983 可以直接提个 PR 上来哈

**Comment by hydra1983** [comment]
@wssgcg1213 已提

**Comment by answershuto** [comment]
https://github.com/openkraken/kraken/pull/586
