### ISSUE TITLE
实现 template 标签功能

### ISSUE THREAD

**Issue by OrangeXC** [openkraken/kraken#589]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
Version: v0.8.2

### 重现步骤 ｜ Steps To Reproduce
1.使用https://github.com/openkraken/samples.git 中的 /demos/hello-vue 进行测试；
2.使用 npm run build 构建；
3.使用 @openkraken/cli@0.8.2运行命令 kraken dist/js/app.js。

**重现代码 | Code example:** 
```
<template>
  <header>
    <h1>Kraken 入门教程</h1>
    <h2>2021-1-1</h2>
  </header>
  <main>
    <article>
      <p>
        <b>Kraken</b>是一款基于<i>W3C</i>标准的高性能渲染引擎。
      </p>
      <p>
        Kraken 底层基于 Flutter进行渲染，通过其自绘渲染的特性，保证多端一致性。
      </p>
    </article>
    <section>
      <h3>上层基于 W3C标准实现，拥有非常庞大的前端开发者生态。</h3>
    </section>
  </main>
  <footer>© 2021 Kraken</footer>
</template>
```

**预期结果 ｜ Expected results:**
正确渲染

**实际结果 ｜ Actual results:** 
![image](https://user-images.githubusercontent.com/16081320/129292338-e211fc05-b958-44aa-adf0-950382cd4703.png)

注：删除header标签或删除footer标签或删除section标签均可正确渲染，只有此代码结构会复现问题。还尝试了将标签全部换成div，一样会复现，初步认定与特殊的标签嵌套相关。

**Comment by answershuto** [comment]
看起来是 template 标签有问题，按理说 template 不应该出现在 bundle 中的，可能是 Vue 会判断有 header 之类的逻辑把 template 打进去了，我查一下。

**Comment by OrangeXC** [comment]
> 看起来是 template 标签有问题，按理说 template 不应该出现在 bundle 中的，可能是 Vue 会判断有 header 之类的逻辑把 template 打进去了，我查一下。

**Comment by OrangeXC** [comment]
@answershuto 

又有个代码片段复现了

```
<template>
  <div style="width: 200px; height: 100px; border: solid">
    边框(border: solid)
  </div>
  <div style="width: 200px; height: 100px; border: solid red">
    边框(border: dashed red)
  </div>
  <div style="width: 300px; height: 100px; border: 1vw solid">
    边框(border: border: 1vw solid)
  </div>
  <div style="width: 200px; height: 100px; backgroundColor: lightblue">
    背景色
  </div>
  <div style="
      width: 150px;
      height: 150px;
      backgroundImage: url(https://kraken.oss-cn-hangzhou.aliyuncs.com/images/60x60-green.png)">
    背景图片
  </div>
</template>
```

此例子也会渲染失败，删除任意一个 div 均可渲染成功。初步判断与标签无关，单个根元素也是渲染失败。

**Comment by OrangeXC** [comment]
Vue3对静态的 `template` 会使用 `template` 标签进行缓存，源码见：
![image](https://user-images.githubusercontent.com/16081320/129498566-b68c65d6-66e3-44db-97a9-26452de2a0a0.png)
北海只需要对 `template` 标签进行实现即可。

**Comment by wssgcg1213** [comment]
@OrangeXC 我们会纳入实现计划~

**Comment by answershuto** [comment]
依赖 #641 合入

**Comment by answershuto** [comment]
示例已经可以跑起来了。

https://github.com/openkraken/kraken/pull/713

![image](https://user-images.githubusercontent.com/17812136/135378589-e79e0ebf-76b3-4cce-b4b4-9c44254128c8.png)
