### ISSUE TITLE
performance tests 中使用 JS bundle 的源码是否可以开放出来？

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#591]
想按照源码中性能测试的方法，测一下更其它的内容，比如 JS bundle 大小对加载速度的影响有多大。但看不到源码

https://github.com/openkraken/kraken/blob/de04c4f60fd988cad343249a5e5a9fe0059f7336/performance_tests/lib/main.dart#L93

**Comment by wssgcg1213** [comment]
这个是业务的代码, 我也这边也没有源码，后面应该会用一个自己的前端测试仓库来替代这个   

如果你只是想测试 JS Bundle 大小对启动性能的影响, 不妨构造一个 bundle, 并通过填充无效代码的方法增加它的的体积

**Comment by cnryb** [comment]
之所以想看源码，最主要的就是想看看这个东西是咋写的
https://github.com/openkraken/kraken/blob/de04c4f60fd988cad343249a5e5a9fe0059f7336/performance_tests/lib/main.dart#L99

**Comment by andycall** [comment]
https://github.com/openkraken/kraken/blob/de04c4f60f/bridge/bindings/jsc/KOM/performance.cc#L414

**Comment by cnryb** [comment]
@andycall 

https://github.com/openkraken/kraken/blob/de04c4f60fd988cad343249a5e5a9fe0059f7336/performance_tests/lib/main.dart#L99

https://github.com/openkraken/kraken/blob/de04c4f60fd988cad343249a5e5a9fe0059f7336/bridge/bindings/jsc/KOM/performance.cc#L414

这两个是个是 JavaScript 的，一个是 C++ 的，如何在 JavaScript 使用你所述 C++ 的函数呀？

**Comment by cnryb** [comment]
找到文档了 https://github.com/openkraken/website/blob/ef0302137945a17da4de16c1e20279a23d4b0c9e/docs/guide/advanced/measure-performance.md#%E8%8E%B7%E5%8F%96%E6%80%A7%E8%83%BD%E6%8A%A5%E5%91%8A
