### ISSUE TITLE
Vue3双向数据绑定导致cli崩溃

### ISSUE THREAD

**Issue by OrangeXC** [openkraken/kraken#593]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
Version: v0.8.2

### 重现步骤 ｜ Steps To Reproduce
1.使用https://github.com/openkraken/samples.git 中的 /demos/hello-vue 进行测试；
2.使用 npm run build 构建；
3.使用 @openkraken/cli@0.8.2运行命令 kraken dist/js/app.js。

**重现代码 | Code example:** 
```html
<template>
  <input v-model="message"
         placeholder="edit me">
  <p>Message is: {{ message }}</p>
</template>

<script setup>
import { ref } from 'vue'

const message = ref('')
</script>
```

**预期结果 ｜ Expected results:**
正确执行

**实际结果 ｜ Actual results:**
命令行不停输出错误：
![image](https://user-images.githubusercontent.com/16081320/129530950-8fc4b6a8-2367-4379-b5e5-7f12b3709b02.png)
![image](https://user-images.githubusercontent.com/16081320/129530993-dfb13777-a31d-4f65-b56a-8b6fa30bc240.png)
![image](https://user-images.githubusercontent.com/16081320/129531076-fb115d9d-0f91-480f-b64c-5bc2ee29be67.png)

**Comment by OrangeXC** [comment]
涉及到事件与绑定联动的场景必现次问题，又一个 case

```
<template>
  <button @click="handleClick">点击事件</button>
  <p>点击 {{ count }} 次</p>
</template>

<script setup>
import { ref } from 'vue'

const count = ref(0)

function handleClick () {
  count.value += 1
}
</script>
```

**Comment by OrangeXC** [comment]
初步判断跟mac上北海模拟器的鼠标事件有关，真机上无法复现此错误

**Comment by answershuto** [comment]
#651
