### ISSUE TITLE
0.8.2上传到App Store提示 ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#597]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
使用版本 0.8.2

邮件详情：

ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _IOIteratorNext, _IOObjectRelease, _IORegistryEntryCreateCFProperties, _IORegistryEntryGetChildIterator, _IOServiceGetMatchingServices, _IOServiceNameMatching, _kIOMasterPortDefault. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by andycall** [comment]
https://github.com/flutter/flutter/issues/37850

应该和这个有关，需要 flutter clean 一下

**Comment by cnryb** [comment]
是把 Archive 的 Build Configuration 设置为 Profile 导致的
