### ISSUE TITLE
Kraken Binary NOT exists, try reinstall.

### ISSUE THREAD

**Issue by Chengshijian** [openkraken/kraken#602]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.8.2

### 重现步骤 ｜ Steps To Reproduce
kraken https://raw.githubusercontent.com/openkraken/kraken/master/kraken/example/assets/bundle.js

Kraken Binary NOT exists, try reinstall.

**预期结果 ｜ Expected results
启动一个调试应用

**实际结果 ｜ Actual results
报错：Kraken Binary NOT exists, try reinstall.

**Comment by cnryb** [comment]
感觉  cli 没装好，卸载了重装试试

**Comment by andycall** [comment]
检查一下 npm scripts 是不是被禁用了
