### ISSUE TITLE
React Demo hot reload 不生效，命令行报错

### ISSUE THREAD

**Issue by ni742015** [openkraken/kraken#642]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

Version: v0.8.3

### 重现步骤 ｜ Steps To Reproduce

1. 运行react demo
2. 命令行中执行 kraken http://localhost:3000/static/js/bundle.js
3. 修改部分代码
4. 命令行中出现如下报错，页面未变化
![image](https://user-images.githubusercontent.com/14267380/131308887-edd1852a-3847-447f-a85c-a264d440c823.png)

**重现代码 | Code example:** 
https://github.com/openkraken/gallery/tree/main/demos/hello-react

**预期结果 ｜ Expected results:** 
代码修改后，页面自动刷新

**实际结果 ｜ Actual results:** 
代码修改后，页面未刷新、命令行中有报错

**Comment by answershuto** [comment]
我看下
