### ISSUE TITLE
http cache  未处理 32 位系统导致报错

### ISSUE THREAD

**Issue by temper357** [openkraken/kraken#643]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

main

### 重现步骤 ｜ Steps To Reproduce

在 Samsung note4 测试机上运行任意 Rax 工程代码报以下错误。

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:** 
![image](https://user-images.githubusercontent.com/5419233/131310331-2fc686f4-8b9e-4364-8b1d-36c73952e32f.png)

**Comment by wssgcg1213** [comment]
1. 这个异常跟 32 位无关
2. 提示错误是因为索引文件不完整, 接下来会走到 invalid 逻辑, 继续走网络, 理论上不会影响
3. 我会提交一个 PR 在 invalid 状态下删除索引和缓存, 以避免重复进入此逻辑
