### ISSUE TITLE
kraken 真机 input点击空白无法失去焦点，隐藏键盘

### ISSUE THREAD

**Issue by todaymumu** [openkraken/kraken#654]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

^0.8.3+3

### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 
<input  type="tel"/>

**预期结果 ｜ Expected results:** 
点击空白隐藏键盘，失去焦点

**实际结果 ｜ Actual results:** 
未隐藏键盘，未失去焦点

**Comment by temper357** [comment]
Kraken 没有做这个交互有两个原因：
1. 点击空白处 input 失焦只是 web 的默认行为，但是并不是 native 默认的行为，可以参考手淘搜索框，input 聚焦后点击其他空白处，并不会使 input 失焦。
2. 即使 Kraken 做了这个交互，在 Kraken 内嵌在 Flutter 应用的 case 中 ，如果在 Kraken widget 之外点击，由于 Flutter 默认未做这个交互，会出现在 Kraken 内部点击会失焦，而在 Kraken 外部点击不失焦的不统一交互。

因此如果要实现这个交互，建议业务上自己处理，在 根节点绑 tap 事件，通过 focusNode.requestFocus() 来使 input 失去焦点，由于现版本 input 焦点处理上存在 bug，需要等 https://github.com/openkraken/kraken/pull/496 合并后再处理。

**Comment by cnryb** [comment]
@temper357 #496 合并了
