### ISSUE TITLE
flutter 自定义widget不支持手势

### ISSUE THREAD

**Issue by todaymumu** [openkraken/kraken#660]
### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 
Kraken.defineCustomElement('flutter-input', (
    Map<String, dynamic> attributes,
  ) {
    return Container(
      height: 200,
      width: Get.width,
      child: MaterialApp(
        home: Scaffold(
          body: TextField(),
        ),
      ),
    );
  });

**预期结果 ｜ Expected results:** 

**实际结果 ｜ Actual results:**

**Comment by answershuto** [comment]
意思是不触发 Flutter Widget 的手势回调还是在 Web 中该节点无法监听？

**Comment by todaymumu** [comment]
输入框不能获取焦点 ，flutter的 点击事件不触发
也测试过PageView 也滑动翻页也不支持 
应该是所有的事件都不支持

**Comment by answershuto** [comment]
看了一下问题在于动态加载渲染的 flutter widget 与 widget 生命周期没对接上，没有调用 mount 导致 widget 没有注册到全局，访问的时候就会访问不到而导致逻辑错误。

**Comment by answershuto** [comment]
以及 widget onTap 与 JS onClick 会有竞争关系导致无法一起监听。

**Comment by answershuto** [comment]
测试了一下，最新的自定义 widget 已可以正常 work ，先 close 了
