### ISSUE TITLE
[0.8.3/+3] Flutter Intergration Example Not Working

### ISSUE THREAD

**Issue by zimmed** [openkraken/kraken#663]
Perhaps I have misunderstood the documentation, but here were my steps:

(Kraken CLI and Flutter+deps already installed)
```
MacOS 10.15.7
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (10 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

- Created a new flutter app (`flutter create kraken_test`)
- Ran the app to ensure everything is configured correctly (`flutter run`)
- Stopped app, added kraken to dependencies:
    ```
    dependencies:
        kraken: '>= 0.8.3'
  ```
- Ran `flutter pub get`
- Replaced `main.dart` with following:
 ```dart
 import 'package:flutter/material.dart';
import 'package:kraken/kraken.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    Kraken kraken = Kraken(
        bundleURL:
            'https://raw.githubusercontent.com/openkraken/kraken/master/kraken/example/assets/bundle.js');

    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home: kraken);
  }
}
```
- Re-ran app with `flutter run`

However, the app was unable to build and spat errors to the console for about 20 straight seconds.

Tried again with 0.8.3+3, but same result.

The file attached shows the run output. Here are the first couple of errors:
```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...          
../../.pub-cache/hosted/pub.dartlang.org/kraken-0.8.3+3/lib/widget.dart:7:8: Error: Not found: 'dart:ffi'

import 'dart:ffi';

       ^

../../.pub-cache/hosted/pub.dartlang.org/kraken-0.8.3+3/lib/src/dom/element_registry.dart:6:8: Error: Not found: 'dart:ffi'

import 'dart:ffi';

       ^
```

What am I doing wrong? Thanks.

[output.log](https://github.com/openkraken/kraken/files/7122344/output.log)

**Comment by zimmed** [comment]
Nevermind. I believe the errors are due to kraken not supported wasm, which was not clear from the documentation. I was hoping this library would be my solution to write UI that compiles to native gl / opengl from the same codebase, but apparently that is outside of its capabilities.

**Comment by wssgcg1213** [comment]
yes，kraken is not designed for web

**Comment by Zireael07** [comment]
The docs should be clearer on the fact that Kraken doesn't support WASM...
