### ISSUE TITLE
Webp 动画问题

### ISSUE THREAD

**Issue by suanmei** [openkraken/kraken#664]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.8.x

### 重现步骤 ｜ Steps To Reproduce
rax-image 加载 webp 动画

**预期结果 ｜ Expected results:** 
每次打开新的kraken容器，重新播放

**实际结果 ｜ Actual results:** 
每次打开新的容器，webp动画还会接着上次的进行播放，除非杀进程。遇到单次播放的动画，如果不杀app进程，表现是动画只有第一次进入的时候会播放。

**Comment by wssgcg1213** [comment]
原因可能跟 Flutter 的 ImageCache 机制有关, 还在进一步修复

**Comment by wssgcg1213** [comment]
related to https://github.com/flutter/flutter/issues/51775
