### ISSUE TITLE
QuickJS

### ISSUE THREAD

**Issue by suyulin** [openkraken/kraken#668]
## 使用场景 ｜ Use case

在 linux arm64 平台使用 北海框架，quickjs 分支对应的依赖库已经编译成功，由于quickjs 还在开发阶段，example 报错无法运行。
所以想问一下 预计什么时候可以合并到main 分支，或者有什么办法可以运行 example 。

**Comment by andycall** [comment]
Linux 平台暂时还没有在支持的范围内

**Comment by suyulin** [comment]
> Linux 平台暂时还没有在支持的范围内

linux 平台我可以支持，现在的问题是 quickjs 分支的 example 怎么样运行起来，目前是有报错的。

**Comment by neeboo** [comment]
我们也可以一起帮忙，如果需要的话

**Comment by suyulin** [comment]
> quickjs 已经支持了 @suyulin

linux arm64平台 我已经编译成功，可以正常使用，就等0.9 版本投入开发。

**Comment by suyulin** [comment]
https://github.com/suyulin/kraken/tree/linux_support linux-arm64 可以正常运行,不支持交叉编译。
`npm run build:bridge:linux:release`
