### ISSUE TITLE
【疑问】集成北海SDK后，安卓和iOS包体会分别增量多少？

### ISSUE THREAD

**Issue by lolimay** [openkraken/kraken#688]
正在调研这个框架集成进APP的可能性，但客户端团队对包体增量非常敏感。看到 Release 页发布的 SDK 有 70~80MB，有点被吓到了。隔壁 [Hippy](https://hippyjs.org/#/) 框架标称 `iOS 增量 1MB，Android 增量最小 2.5MB`。北海是不是也可以在官网明确标注集成 Kraken 会导致多大的包体增量？

**Comment by lolimay** [comment]
看到之前的[会议纪要](https://github.com/openkraken/TSC/blob/master/meetings/2021-03-10.md)目标是：

> 包体积
Dart+Bridge app 增量 iOS 1.5M Android 1M

现在的情况大概是怎样呢？

**Comment by andycall** [comment]
SDK 里面包含多个架构，不同 target 的产物，肯定会很大的。

实际集成包大小增量还是要看个人情况，因为有的团队可以复用 flutter engine，有的团队可以复用 jsc，所以具体增量表现还是要按照个人情况来判断。

**Comment by answershuto** [comment]
@lolimay 如果 APP 已经集成 JSC 与 Flutter Engine 的情况下，增量大概在 2.5M 的样子。

**Comment by wssgcg1213** [comment]
`增量` 这个指标其实是比较模糊的, 特别是在不同 SDK 对比的时候, 因为需要有一个 `基础` 体积；这个 `基础` 内置的东西可就广了, 把 Flutter Engine/ JSC or V8/ App 原先在用的 Flutter 插件等等都算在基础里面，这样增量就会比较小。但是如果对于新的 App, 所有内容都是 `增量`, 所以希望可以理性看待这个数字。

我先给几个大概的数据吧: 

Android 为例: 

- 依赖项
  - libflutter.so 单架构约 3m+
  - JavaScriptCore 14M
- 核心
  - kraken bridge 约 600K
  - app.so (只能计算增量, 因为 flutter 很多东西都是公用的) +约1-1.5M

其它信息: 
- iOS/macOS 无需计算 JSCore, 因为系统内置了
- kraken 0.9 版本会支持 quickjs 作为默认 JSEngine, 此项估计可以减小到 1M 以内


> 至于 70-80 M 的数据,  Flutter 在打包 Debug 包时会打入调试信息和符号表，在 release 打包时才会去除 (更彻底需要定制构建参数, 这些社区有不少瘦身的教程可以参考), 所以无需多虑

**Comment by lolimay** [comment]
了解，感谢详细的解答。

https://github.com/openkraken/kraken/issues/283#issuecomment-840971509

这样看 QuickJS 确实有很大吸引力

**Comment by answershuto** [comment]
@wssgcg1213  补充到官网常见问题 https://github.com/openkraken/website/pull/161

**Comment by answershuto** [comment]
补充最新数据：
package:kraken  1 MB
libquickjs.dylib     902K 
libkraken.dylib     748K
