### ISSUE TITLE
iOS-本地局域网访问缓存崩溃。之前还是OK的

### ISSUE THREAD

**Issue by showtestlog** [openkraken/kraken#691]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.8.3

### 重现步骤 ｜ Steps To Reproduce
电脑打包,python服务部署，iOS本地访问，出现缓存问题，必崩。

**重现代码 | Code example:** 

打开桌面服务的bundle.js。
**实际结果 ｜ Actual results:** 

![image](https://user-images.githubusercontent.com/12830799/133583563-4e4fbfc9-d7ea-426c-bf07-1780e56ac496.png)

**Comment by wssgcg1213** [comment]
应该是缓存在写入的过程中失败, 导致读入的 buffer 为空  
猜测跟权限有关系, 我拿一台 iOS 试一下

**Comment by wssgcg1213** [comment]
可以升级到最新版本, 已经解决掉这个问题了
