### ISSUE TITLE
flex 叠加 absolute 样式错位

### ISSUE THREAD

**Issue by suanmei** [openkraken/kraken#692]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
最新版

### 重现步骤 ｜ Steps To Reproduce

外层元素设置 display: flex; align-items: center; 子元素设置 position: absolute;不指定left: 0; 子元素会跑偏父元素宽度的 50%

**预期结果 ｜ Expected results:** 
子元素实际 left应该为 0

**实际结果 ｜ Actual results:** 
子元素展示出了 left: 50% 的效果

**Comment by temper357** [comment]
经测试最新的 main 上 Kraken 与浏览器显示效果一致。

**Comment by temper357** [comment]
image 设置 loading=lazy 能复现此问题。
