### ISSUE TITLE
0.8.3 text-align:center 无效

### ISSUE THREAD

**Issue by gcxfd** [openkraken/kraken#701]
代码
https://github.com/gcxfd/rmw-dart/tree/454079e0b8108e992246051458c6a0c6d7fb1489

chrome debug截图如下
![image](https://user-images.githubusercontent.com/69608605/134493119-a861062f-f531-4478-9107-be809773d45a.png)

**Comment by temper357** [comment]
在浏览器中运行上面的 demo，text-align: center 同样是不生效的

![image](https://user-images.githubusercontent.com/5419233/134613898-d1ed1352-6743-41e3-94b0-fc45a90665a0.png)

**Comment by gcxfd** [comment]
我的错
