### ISSUE TITLE
vue 中不在其它容器中的文本前面会被添加空格

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#740]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.8.4

**重现代码 | Code example:** 

样例工程在这里 https://github.com/cnryb/kraken-demo/blob/master/test-case/test-case3/src/App.vue

```HTML
<template>
  <div>Hello</div>
  Hello
</template>
```

**实际结果 ｜ Actual results:** 
![image](https://user-images.githubusercontent.com/3817284/138066474-a5e134de-c7f8-45f6-898b-50f4681aab5b.png)

**Comment by wssgcg1213** [comment]
这个貌似是符合预期的? Hello 与 div 结束之间有 `\n` 和2个空格, 理论上会被合并成一个空格
`[<div>, ' ', 'Hello']`

**Comment by wssgcg1213** [comment]
@temper357 确认下呢
