### ISSUE TITLE
有计划什么时候DevTool支持JS和网络的调试吗？

### ISSUE THREAD

**Issue by QFangMobile** [openkraken/kraken#741]
## 使用场景 ｜ Use case

目前的调试只支持Element不支持js等，开发调试还是非常不方便

## 提案 ｜ Proposal

有计划什么时候DevTool支持JS和网络的调试吗？

**Comment by cnryb** [comment]
现在已经支持 JS 的调试了 https://openkraken.com/guide/native/embedded-devtools

展示网络请求也计划支持 #30 ，最快也要等到处理完 quick js 相关的问题了。

**Comment by wssgcg1213** [comment]
网络这块最近已经在开始投入了, 最快月底之前可以完成, 可以关注 #30 这个 issue, 我会同步在那边
