### ISSUE TITLE
vue 中动态生成的元素 space-between 展示异常

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#743]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.8.4

**重现代码 | Code example:** 
样例工程在这里  https://github.com/cnryb/kraken-demo/blob/master/test-case/test-case5/src/App.vue
``` html
<template>
<!-- 这段展示异常正常 -->

<div style="display: flex; justify-content: space-between; align-items: center;">
  <div
    v-for="color in 3"
    :key="color"
    style="border: 1px solid red;"
  >{{ color }}</div>
</div>

<!-- 这段正常 -->
<div style="display: flex; justify-content: space-between; align-items: center;">
    <div style="border: 1px solid red;">1</div>
    <div style="border: 1px solid red;">2</div>
    <div style="border: 1px solid red;">3</div>
</div>
</template>
```

**实际结果 ｜ Actual results:** 

![image](https://user-images.githubusercontent.com/3817284/138077234-392b9d35-755d-46f7-b6c7-195e1759550e.png)

**Comment by temper357** [comment]
第一段 vue 模板转换出来的 js 指令有错乱导致渲染不对

**Comment by cnryb** [comment]
> 第一段 vue 模板转换出来的 js 指令有错乱导致渲染不对

所以呢，应该怎么处理呀，要把问题提交给 vue 社区吗？

**Comment by temper357** [comment]
@answershuto 会负责看一下这个问题

**Comment by cnryb** [comment]
👍
