### ISSUE TITLE
npm run build:bridge:android failed

### ISSUE THREAD

**Issue by whatleo** [openkraken/kraken#751]
Cmake Comand:cmake -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_TOOLCHAIN_FILE=SDK/ndk-bundle-21/build/cmake/android.toolchain.cmake     -DANDROID_NDK=SDK/ndk-bundle-21     -DIS_ANDROID=TRUE     -DANDROID_ABI="arm64-v8a"          -DANDROID_PLATFORM="android-16"     -DANDROID_STL=c++_shared     -G "Unix Makefiles"     -B Flutter/Ali_Kraken/kraken/bridge/cmake-build-android-arm64-v8a -S Flutter/Ali_Kraken/kraken/bridge, at path:Flutter/Ali_Kraken/kraken/bridge
-- Check for working C compiler: SDK/ndk-bundle-21/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: SDK/ndk-bundle-21/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: SDK/ndk-bundle-21/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Check for working CXX compiler: SDK/ndk-bundle-21/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DART_SDK include:flutter/bin/cache/dart-sdk/include
-- env.KRAKEN_JS_ENGINE:jsc
-- Configuring done
-- Generating done
-- Build files have been written to: kraken/bridge
cmake build kraken/bridge/cmake-build-android-arm64-v8a
Error: kraken/bridge/cmake-build-android-arm64-v8a is not a directory
kraken/node_modules/async-done/index.js:18
    throw err;

kraken版本0.8.4，android NDK 21.4.7075529，flutter版本2.2.0

**Comment by andycall** [comment]
光从日志看不出问题，有更详细的日志吗？
