### ISSUE TITLE
子元素不会继承父元素的fontWeight

### ISSUE THREAD

**Issue by gcxfd** [openkraken/kraken#764]
```
main(:style="{ display: 'flex' }")
  article(:style="{ fontWidth: 300, padding: '16px' }")
    p(:style="{ fontWeight: 300 }") 房产税如果普遍征收而没有任何豁免，由于二线以下城市房租无法拟补持有成本，那么房产投资客应该会抛掉二线以下的城市房产，集中购买一线城市的房产，那么
二线以下城市的房地产市场估计会崩盘。
    a 月光博客
```

效果如下，`月光博客`fontWidth不是300
![image](https://user-images.githubusercontent.com/69608605/138578235-c3fd2cc6-aad1-46e5-a27e-05f063fdb15d.png)

**Comment by temper357** [comment]
article 标签上指定的样式写错了，应该是 fontWeight，不是 fontWidth

![image](https://user-images.githubusercontent.com/5419233/140268613-883e6539-d90e-41b8-8fb5-c9f688ef6e55.png)
