### ISSUE TITLE
部分元素加上style属性后 kraken会崩溃Failed to execute 'insertBefore' on 'Node': the node element is not object.

### ISSUE THREAD

**Issue by gcxfd** [openkraken/kraken#768]
kraken 0.8.4 
代码 https://github.com/rmw-dart/ui/tree/bd111d2ea4f9a310ea8132c114a3f4b3932ca291

header这一行加上style标签后 kraken会崩溃
删除style就可以运行

如下图 
![image](https://user-images.githubusercontent.com/69608605/138588444-c79ba773-385b-498a-be4b-3a2a9f174358.png)

**Comment by gcxfd** [comment]
@wssgcg1213 这个问题修复了吗？不修复没法尝试开发东西

**Comment by andycall** [comment]
可以试下0.9还有这个问题吗

**Comment by gcxfd** [comment]
@andycall 0.9.0一样的报错
![image](https://user-images.githubusercontent.com/69608605/140451444-e30c5aad-6151-40d0-95bc-817c9567c647.png)

**Comment by andycall** [comment]
![image](https://user-images.githubusercontent.com/4409743/140457365-1d248fe3-11c3-4944-a56c-8f81faec0857.png)

直接给 style 赋值字符串的用法还在开发中，之前的版本只支持给 style 传递一个对象

https://github.com/openkraken/kraken/pull/815

**Comment by andycall** [comment]
@gcxfd https://github.com/openkraken/kraken/pull/851

**Comment by gcxfd** [comment]
多谢
