### ISSUE TITLE
0.8.4 中 max-width 布局异常

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#783]
### 重现步骤 ｜ Steps To Reproduce

样例工程在这里 https://github.com/cnryb/kraken-demo/blob/master/test-case/test-case11/src/App.vue

**重现代码 | Code example:** 
``` html

<template>
  <div style="max-width: 100%;
      margin: 40px;
      border: 1px solid red;">
    Kraken is a high-performance rendering engine based on W3C standards. Kraken's bottom layer is rendered based on Flutter, and its self-drawn rendering feature ensures multi-end consistency. The upper layer is implemented based on W3C standards and has a very large front-end developer ecosystem.
  </div>
</template>
```

**实际结果 ｜ Actual results:** 
下图是浏览器和 kraken cli 的对比
![image](https://user-images.githubusercontent.com/3817284/138706631-f52e1964-b9c4-449f-b2f0-e4edc7bf04b9.png)

**Comment by temper357** [comment]
https://github.com/openkraken/kraken/pull/838 分支已修复该问题

**Comment by cnryb** [comment]
fixed in #656
