### ISSUE TITLE
优化 Widget 扩展的能力

### ISSUE THREAD

**Issue by andycall** [openkraken/kraken#788]
## 使用场景 ｜ Use case

现在使用 Flutter Widget 扩展渲染，只能使用例如 Text 这样不依赖 MediaQuery 等上下文环境等 Widget。像 MaterialDesign 内部的一些组件例如 Scaffold 都无法正常使用。

需要找到一些解决办法，扩展可用 Widget 的范围

**Comment by answershuto** [comment]
https://github.com/openkraken/kraken/pull/904
