### ISSUE TITLE
build apk 控制台报错

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#801]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
main 分支

### 重现步骤 ｜ Steps To Reproduce
安装依赖，执行 `npm run build:bridge:all:release` 之后。
在 `.kraken/kraken/example` 目录中，执行 `flutter run apk ` 。 控制台报输出如下 

```
💪 Building with sound null safety 💪

Error: unable to find directory entry in pubspec.yaml: /Users/renyuebing/.pub-cache/hosted/pub.flutter-io.cn/kraken_websocket-1.0.0-dev.1/assets/
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      14.6s
✓  Built build/app/outputs/flutter-apk/app-release.apk (21.0MB).
```

**Comment by wssgcg1213** [comment]
不影响, 可忽略, 插件的配置项可以更新一下   
迁移到 plugins 仓库 https://github.com/openkraken/plugins/pull/22
