### ISSUE TITLE
在使用canvas中经常崩溃

### ISSUE THREAD

**Issue by fly512** [openkraken/kraken#821]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.8.4

F/libc    (22448): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 22484 (1.ui), pid 22448 (m.example.webgl)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/SEA-AL10/HWSEA-A:10/HUAWEISEA-AL10/102.0.0.165C00:user/release-keys'
Revision: '0'
ABI: 'arm64'
SYSVMTYPE: Maple
APPVMTYPE: Art
Timestamp: 2021-11-02 12:44:52+0800
pid: 22448, tid: 22484, name: 1.ui  >>> com.example.webgl <<<
uid: 10220
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    x0  000000782f4f7940  x1  0000000000000000  x2  000000784dc0b078  x3  000000784d1f1ee0
    x4  0000000000000002  x5  0000000000000000  x6  000000783113fc01  x7  0000000000000000
    x8  0000000000000000  x9  0000000000000001  x10 0000000000000000  x11 0000000000000000
    x12 00000078305fbf20  x13 0000000000000001  x14 0000000000000000  x15 000000784d1f1540
    x16 0000000000000000  x17 000000782f414600  x18 000000784c860000  x19 00000078275d4900
    x20 00000078b52b59c0  x21 000000784d4a2c10  x22 000000784d1f1640  x23 000000784d1f3020
    x24 000000784d1f1640  x25 000000784dc2ae50  x26 0000000000000005  x27 ffff000000000000
    x28 ffff000000000002  x29 000000784d1f1600
    sp  000000784d1f1550  lr  000000784dc2af58  pc  0000000000000000
backtrace:
      #00 pc 0000000000000000  <unknown>
      #01 pc 000000000004ef54  /data/app/com.example.webgl-gqf2ywzeXOIB6ZlFgkyxuw==/lib/arm64/libkraken_jsc.so (kraken::binding::jsc::CanvasRenderingContext2D::clearRect(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**)+260) (BuildId: 2c18f633464c8ad2e3579e4f1b6d610717af2b0d)
      #02 pc 0000000000143790  /data/app/com.example.webgl-gqf2ywzeXOIB6ZlFgkyxuw==/lib/arm64/libjsc.so (BuildId: 5144ead17a8b84eafc4d3b53516b954156d85440)
      #03 pc 000000000040c018  /data/app/com.example.webgl-gqf2ywzeXOIB6ZlFgkyxuw==/lib/arm64/libjsc.so (BuildId: 5144ead17a8b84eafc4d3b53516b954156d85440)
      #04 pc 00000000003f6158  /data/app/com.example.webgl-gqf2ywzeXOIB6ZlFgkyxuw==/lib/arm64/libjsc.so (BuildId: 5144ead17a8b84eafc4d3b53516b954156d85440)

**Comment by wssgcg1213** [comment]
升级到 0.9.0 新版本试一下还有没有这个问题?
