### ISSUE TITLE
window.addEventListener not working

### ISSUE THREAD

**Issue by andycall** [openkraken/kraken#837]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.9.0-rc.5

### 重现步骤 ｜ Steps To Reproduce

```javascript
window.onclick = () => console.log(1234);
```

Click screen and not print 1234 on terminal.

**Comment by wssgcg1213** [comment]
冒泡的问题?

**Comment by answershuto** [comment]
原因是 window 不是继承 Node 而是 EventTarget，现在的冒泡是根据 Node tree 来实现的，需要对 window 进行特殊处理。
