### ISSUE TITLE
E/KRAKEN_NATIVE_LOG: document.querySelector is not a function. (In 'document.querySelector('base')', 'document.querySelector' is undefined)

### ISSUE THREAD

**Issue by colorfulldays** [openkraken/kraken#849]
kraken 版本  kraken: ^0.7.2

显示 js页面 有如下报错 
```
E/KRAKEN_NATIVE_LOG: document.querySelector is not a function. (In 'document.querySelector('base')', 'document.querySelector' is undefined)
```

**Comment by wssgcg1213** [comment]
document.querySelector 需要升级到 0.9.0 后支持

**Comment by colorfulldays** [comment]
> document.querySelector 需要升级到 0.9.0 后支持

因为我们flutter 用的还是2.0以下的版本 ，支持不了这么高的版本，目前用的 0.7.3， 感觉好多web特性都没有支持。。。

**Comment by colorfulldays** [comment]
> document.querySelector 需要升级到 0.9.0 后支持
升级了 0.9 又出了这样的错误
 TypeError: cannot read property 'charAt' of undefined
