### ISSUE TITLE
linux 环境下安装出错，kraken-linux-0.9.0.tar.gz 未上传

### ISSUE THREAD

**Issue by yunfengsay** [openkraken/kraken#853]
~~### 使用的 Kraken 版本 ｜ What version of kraken are you using~~

~~### 重现步骤 ｜ Steps To Reproduce~~

~~ubuntu 20.04版本~~
```
npm i @openkraken/cli -g
```

~~**重现代码 | Code example:~~** 

~~**预期结果 ｜ Expected results:~~** 

~~**实际结果 ｜ Actual results:~~** 
![image](https://user-images.githubusercontent.com/15527378/140605207-13d47a9e-a78c-4b2e-8b1d-36b0d8ce8ccb.png)

~~定位是 https://kraken.oss-cn-hangzhou.aliyuncs.com/kraken-cli-vendors/kraken-linux-0.9.0.tar.gz oss文件未上传~~

**Comment by yunfengsay** [comment]
看到了npm install方式只支持macos

**Comment by arasrezaei** [comment]
please add windows and linux

**Comment by wssgcg1213** [comment]
cli 暂未支持 linux & windows, 可以 follow 这个文档 https://flutter.dev/desktop#build-a-release-app 构建一个 app 产物, anyone can submit PR to help us?

**Comment by suyulin** [comment]
#668

**Comment by andycall** [comment]
Linux now supported
