### ISSUE TITLE
safe-area-inset-* 不正确

### ISSUE THREAD

**Issue by cnryb** [openkraken/kraken#859]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
使用 kraken 版本 0.9.0  
在手机中 safe-area-inset-right、safe-area-inset-left，明显的和浏览器中不同。

### 重现步骤 ｜ Steps To Reproduce
使用 flutter create 创建一个新的空白工程。把 `lib/main.dart` 中的代码修改成下面的样子。

**重现代码 | Code example:**
``` dart
import 'package:flutter/material.dart';
import 'package:kraken/kraken.dart';

void main() {
  runApp(Kraken(
          bundleContent:'''
const container = document.createElement('div');
const paddings = [
  'env(safe-area-inset-top)',
  'env(safe-area-inset-right)',
  'env(safe-area-inset-bottom)',
  'env(safe-area-inset-left)',
];
container.style.padding = paddings.join(' ');
container.style.backgroundColor = '#666';
container.style.height = '100vh'

const contentEle = document.createElement('div')
contentEle.style.width = '100%'
contentEle.style.height = '100%'
contentEle.style.backgroundColor = '#fff'

container.appendChild(contentEle)
document.body.appendChild(container);
          '''
        ));
}
```

**预期结果 ｜ Expected results:** 
![image](https://user-images.githubusercontent.com/3817284/140881154-b3a41684-acf8-4a03-a6cb-93e02de1bf1e.png)
图片来自 https://developer.apple.com/documentation/uikit/uiview/positioning_content_relative_to_the_safe_area#2936293

**实际结果 ｜ Actual results:** 
在 macOS 的 kraken 中 和 浏览器 （包括手机中的浏览器）中，展示的都是一块白屏。

在 iPhone 11 中展示如下图
![image](https://user-images.githubusercontent.com/3817284/140891957-6a042a02-cec7-4e1e-a43f-63ecc697d51c.png)

在 Mi Note 3 中展示如下图

![image](https://user-images.githubusercontent.com/3817284/140892087-de96760c-e1e5-48d1-a096-78a60fa16369.png)

**Comment by temper357** [comment]
目前还未支持 env()

**Comment by cnryb** [comment]
我看测试代码里有这么写的了，才开始做这个测试的……
https://github.com/openkraken/kraken/blob/67850fa9082fef6de026276b0f10b71536e45530/integration_tests/specs/css/css-variables/environment.ts#L4-L14

gallery 里也有这么写的
https://github.com/openkraken/gallery/blob/179169e8c08e71287ee9e9beb3860449c0d5c25b/demos/data-grid/src/App.vue#L17-L23

**Comment by temper357** [comment]
看了下代码对 env(safe-area-inset-*)的确有支持， safe-area-inset-* 解析逻辑如下，使用的是 Flutter window上的 viewPadding 变量

https://github.com/openkraken/kraken/blob/67850fa9082fef6de026276b0f10b71536e45530/kraken/lib/src/css/style_declaration.dart#L424-L438

macOS 和手机上显示不一致我理解是正常的，源自 Flutter engine 对 viewPadding 的解析不同导致，在 macOS 上 window 内无其他 UI viewPadding 被解析成 0 导致 kraken 全屏显示，而手机上则会解析成系统 UI 遮挡部分的尺寸导致 kraken 外有 padding。

https://github.com/flutter/engine/blob/df686d2638b35ce6ea771586b374fae800d0624c/lib/ui/platform_dispatcher.dart#L1094-L1106

**Comment by cnryb** [comment]
可是在手机中，  safe-area-inset-right、safe-area-inset-left 返回那么大的不安全区域，看起来也不太对呀

**Comment by temper357** [comment]
safe area padding 的处理逻辑与 flutter 是一致的，可以写一个 Flutter 原生的 SafeArea Widget 对比一下效果？如果效果一致的话，有可能与右上角的 debug banner 有关，把 debug banner 去除再看看

**Comment by cnryb** [comment]
使用flutter写的安全区截图如下，红色是非安全区

在 iPhone 11 中展示如下图
![image](https://user-images.githubusercontent.com/3817284/141097451-5c006d42-25ad-494f-91c2-65b1b1425e37.png)

在 Mi Note 3 中展示如下图
![image](https://user-images.githubusercontent.com/3817284/141097811-5e937894-192f-4214-80bc-6350a2d5c57f.png)

以下是测试代码
``` dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
      // debugShowCheckedModeBanner: false,
      home: Scaffold(
          backgroundColor: Colors.red,
          body: SafeArea(
            child: Container(
              color: Colors.grey,
            ),
          ))));
}
```

**Comment by cnryb** [comment]
对比看来，似乎只有 `safe-area-inset-top` 是正确的

**Comment by temper357** [comment]
我测试了下 main 上的确有问题，但是切到 https://github.com/openkraken/kraken/pull/656 这个 PR 对应的分支问题消失，看起来是以前的实现上有 bug，renderStyle 重构正好解了这个问题，你可以切到 feat-css-style-sheet 分支试下

**Comment by cnryb** [comment]
fixed in #656
