### ISSUE TITLE
kraken_webview 1.1.0 编译错误

### ISSUE THREAD

**Issue by meyhuan** [openkraken/kraken#875]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

  kraken: ^0.9.0
  kraken_webview: ^1.1.0
  kraken_devtools: 0.4.0-dev.0

### 重现步骤 ｜ Steps To Reproduce

android 编译 arr 报错：

 - 'WebViewElement' is from 'package:kraken_webview/iframe_element.dart' ('../../.pub-cache/hosted/pub.dartlang.org/kraken_webview-1.1.0/lib/iframe_element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'renderStyle'.
  double? get width => renderStyle.width.isAuto

**重现代码 | Code example:** 
KrakenWebView.initialize();

**预期结果 ｜ Expected results:** 
编译成功

**实际结果 ｜ Actual results:** 
编译错误

**Comment by andycall** [comment]
可以用一下 1.0.0 版本
