### ISSUE TITLE
调用 Viewport Resize 展示不符合预期

### ISSUE THREAD

**Issue by tylorvan** [openkraken/kraken#89]
Viewport Resize 后展示不符合预期：
预期效果:
![image](https://user-images.githubusercontent.com/5905365/111965028-3c392080-8b30-11eb-85b6-157bf7b0e05e.png)

展示效果：
![image](https://user-images.githubusercontent.com/5905365/111956679-01ca8600-8b26-11eb-93b2-af000dc39d71.png)

不符合预期点：
1. 位置错误
2. 高度未全填充

![image](https://user-images.githubusercontent.com/5905365/111957094-8a492680-8b26-11eb-803b-acffff3911f7.png)

测试地址：
https://t.youku.com/yep/page/kraken/m/cvd3r6f068

**Comment by wssgcg1213** [comment]
1. 布局的问题需要确认下 @temper357 
2. 高度的问题, 需要再提供一下传入的 viewportHeight 以及设备的宽高 @tylorvan

**Comment by tylorvan** [comment]
高度是动态计算的，为屏幕高度- 状态栏高度- 44
可以按照以下过滤条件进行过滤
tylorvan

![image](https://user-images.githubusercontent.com/5905365/111961014-7227d600-8b2b-11eb-9a15-96b599f358ce.png)

**Comment by temper357** [comment]
第二个高度问题是前端代码的原因，容器的高度用 vw 写死了，这样 web 上 resize 容器变高时同样会有问题。

看下面调试器截图，外面两层都设置死了 vw 高度，正确做法是改成 100vh。
![image](https://user-images.githubusercontent.com/5419233/112088732-4eb46800-8bcb-11eb-9cda-4ee09f08428c.png)

![image](https://user-images.githubusercontent.com/5419233/112088881-8de2b900-8bcb-11eb-8461-2df0c64e54e1.png)

**Comment by tylorvan** [comment]
确认 resize 之后，没有重新计算高度，按照之前的高度进行了进行转换的值进行了布局

麻烦再确认下第一个位置不对的问题

**Comment by temper357** [comment]
第一个问题 https://github.com/openkraken/kraken/pull/116 已解决。
