### ISSUE TITLE
CommentNode support

### ISSUE THREAD

**Issue by lifeart** [openkraken/kraken#894]
## 使用场景 ｜ Use case

I would like to play with kraken support for glimmer-vm ([GlimmerX](https://github.com/glimmerjs/glimmer-experimental), [Ember](http://emberjs.com/))

As I see, right now DOM CommentNode is not supported, but it's used in Glimmer:

https://github.com/glimmerjs/glimmer-vm/blob/4f1bef0d9a8a3c3ebd934c5b6e09de4c5f6e4468/packages/%40glimmer/runtime/lib/dom/operations.ts#L107
https://github.com/glimmerjs/glimmer-vm/blob/4f1bef0d9a8a3c3ebd934c5b6e09de4c5f6e4468/packages/%40glimmer/runtime/lib/compat/text-node-merging-fix.ts#L38
https://github.com/glimmerjs/glimmer-vm/blob/5c0dd7b4514b7f5211f61be4eba2c5c0c237274d/packages/%40glimmer/runtime/lib/vm/update.ts#L247
https://github.com/glimmerjs/glimmer-vm/blob/4f1bef0d9a8a3c3ebd934c5b6e09de4c5f6e4468/packages/%40glimmer/runtime/lib/vm/element-builder.ts#L342

Comment node used as "cursor" for DOM manipulations

## 提案 ｜ Proposal

It will be great to have DOM Comment API support

**Comment by andycall** [comment]
CommentNode is already supported in kraken in v0.9.0. May be you should give us more info about why comment node are not working well on   (GlimmerX, Ember)

https://github.com/openkraken/kraken/blob/fae0c432759b258b87b7a10a9493275a89f5d478/bridge/bindings/qjs/dom/document.h#L37

**Comment by lifeart** [comment]
@andycall thank you for reference! Will double check logic
