### ISSUE TITLE
zsh: command not found: kraken

### ISSUE THREAD

**Issue by yahooyee** [openkraken/kraken#921]
### 使用的 Kraken 版本 0.9
使用npm install -g @openkraken/cli命令行安装成功后
/usr/local/Cellar/node/17.0.1/bin/kraken -> /usr/local/Cellar/node/17.0.1/lib/node_modules/@openkraken/cli/bin/kraken.js

> @openkraken/cli@0.9.0 postinstall /usr/local/Cellar/node/17.0.1/lib/node_modules/@openkraken/cli
> node install.js

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 46.3M  100 46.3M    0     0  2294k      0  0:00:20  0:00:20 --:--:-- 2309k
+ @openkraken/cli@0.9.0
updated 1 package in 25.699s
user ~ % kraken
zsh: command not found: kraken

提示没有发现kraken

**Comment by wssgcg1213** [comment]
```bash
echo $PATH
````

检查一下 /usr/local/Cellar/node/17.0.1/bin 这个路径是否在 PATH 里面

**Comment by yahooyee** [comment]
已解决
