### ISSUE TITLE
Flutter Widget 自定义元素，Scrollable无法滚动

### ISSUE THREAD

**Issue by jnxey** [openkraken/kraken#943]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
Version:  0.9.0

### 重现步骤 ｜ Steps To Reproduce
定义一个自定义flutter元素，包含一个滚动器，类似于SingleChildScrollView，
在kraken中调用这个元素，无法滚动。

若是间隔500ms自动build一次滚动器，则可以滚动。

猜测原因：Scrollable的滚动事件监听绑定是异步的，绑定后重build一遍滚动器，但在自定义元素方法内无法重新build。

**重现代码 | Code example:
## main.dart 自定义元素 ##
void defineKrakenCustomElements() {
  Kraken.defineCustomElement('scroll-flutter',
      (targetId, nativeEventTarget, elementManager) {
    return ListViewTest(targetId, nativeEventTarget, elementManager);
  });
}

class ListViewTest extends WidgetElement {
  ListViewTest(int targetId, Pointer<NativeEventTarget> nativeEventTarget,
      ElementManager elementManager)
      : super(targetId, nativeEventTarget, elementManager);

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties) {
    String str = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    Widget Scroll(int change) {
      return SingleChildScrollView(
        physics: BouncingScrollPhysics(),
        padding: EdgeInsets.all(16.0),
        scrollDirection: Axis.vertical,
        child: Center(
          child: Column(
            //动态创建一个List<Widget>
            children: str
                .split("")
                //每一个字母都用一个Text显示,字体为原来的两倍
                .map(
                  (c) => Text(
                    c,
                    textDirection: TextDirection.ltr,
                    textScaleFactor: 2.0,
                  ),
                )
                .toList(),
          ),
        ),
      );
    }
    return Center(
      child: Container(
        width: 300,
        height: 300,
        color: Colors.blue,
        child: KrakenScroll(
          builder: Scroll,
        ),
      ),
    );
  }
}

## kraken_scroll.dart ##
import 'package:flutter/material.dart';
import 'dart:async';
class KrakenScroll extends StatefulWidget {
  const KrakenScroll({Key? key, required this.builder});
  final Function builder;
  @override
  _KrakenScrollState createState() => _KrakenScrollState();
}
class _KrakenScrollState extends State<KrakenScroll> {
  int change = 0;
  Timer? timer;
  @override
  void initState() {
    // 注释后无法滚动
    // const timeout = const Duration(microseconds: 500);
    // timer = Timer(timeout, () {
    //   setState(() {
    //     change = 1;
    //   });
    // });
    super.initState();
  }
  @override
  void dispose() {
    super.dispose();
    timer?.cancel();
  }
  @override
  Widget build(BuildContext context) {
    print(change);
    return widget.builder(change);
  }
}

**预期结果 ｜ Expected results:
可以正常滚动

**实际结果 ｜ Actual results:
无法滚动

**Comment by answershuto** [comment]
https://user-images.githubusercontent.com/17812136/147179946-d8eaf68e-bf94-41ea-ba1c-748cc0286b73.mov

**Comment by answershuto** [comment]
在最新 main 上测试，该问题已经修复。
