### ISSUE TITLE
image 在已有width property 的情况下改变 width property 不生效

### ISSUE THREAD

**Issue by temper357** [openkraken/kraken#945]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

main

### 重现步骤 ｜ Steps To Reproduce

**重现代码 | Code example:** 

```js
   it('image width property change bug', async () => {
    let img = createElement('img', {
          src: 'assets/300x150-green.png',
          width: 100,
          height: 100
        });
    BODY.appendChild(img);
 
    setTimeout(() => {
       img.setAttribute('width', 200);
    }, 1000);

    await snapshot(0.1);
  });

```

**预期结果 ｜ Expected results:** 
![image](https://user-images.githubusercontent.com/5419233/144800810-ffc6f2c4-448a-4696-a4af-eaca17e25998.png)

**实际结果 ｜ Actual results:** 
![image](https://user-images.githubusercontent.com/5419233/144800835-55171d4f-a615-4d2f-8af2-07a670f3cc82.png)

**Comment by andycall** [comment]
有试过这个分支吗？

**Comment by andycall** [comment]
https://github.com/openkraken/kraken/pull/879

**Comment by temper357** [comment]
刚刚切过去测试了，一样有问题。
