### ISSUE TITLE
react demo 页面样式不一致

### ISSUE THREAD

**Issue by Alvabill** [openkraken/kraken#949]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.9.0

### 重现步骤 ｜ Steps To Reproduce

git clone https://github.com/openkraken/samples.git
cd ./demos/hello-react

**重现代码 | Code example:** 
git clone https://github.com/openkraken/samples.git
cd ./demos/hello-react

**预期结果 ｜ Expected results:** 
h5 版本和 flutter app 版本样式一致

**实际结果 ｜ Actual results:** 
样式不一致
![image](https://user-images.githubusercontent.com/19250684/144995357-c3476d1a-8742-438d-851e-a41134aa266f.png)
![image](https://user-images.githubusercontent.com/19250684/144995383-95050613-032b-4284-93e3-7ea5a7e675e8.png)

**Comment by niluanxy** [comment]
这是一个纯 KPI 的项目，我非常怀疑他们自己是不是写个 Hello World 页面就算测试通过了，官方的教程跑不通不说，单单同样的代码，Mac 下的 CLI 模拟是一个样子，安卓真机安装又是一个样子，每个平台都有BUG，且每个BUG还都不一样，奉劝要不直接用 Flutter 来开发，要不用原生，或者H5套壳也好，比现在这种 KPI 项目好得多，又一个 Weex 的。

**Comment by wssgcg1213** [comment]
@niluanxy What's your problem?

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/145349119-ba6f6979-f4ae-419c-b566-b4615057b027.png)
可以升级到 0.9.1-rc.1 版本试一下, 这个版本解决了一些样式设置顺序导致的问题, 我这边本地试了下是正常
