### ISSUE TITLE
支持样式继承，支持样式表

### ISSUE THREAD

**Issue by Alvabill** [openkraken/kraken#956]

**Comment by wssgcg1213** [comment]
样式表: 在 0.9.1 上已经实现  
样式继承：目前支持有限的样式继承, 你可以描述一下何属性未按预期工作

**Comment by hkc452** [comment]
有发版计划吗
> 样式表: 在 0.9.1 上已经实现 样式继承：目前支持有限的样式继承, 你可以描述一下何属性未按预期工作
