### ISSUE TITLE
ReferenceError: 'WebSocket' is not defined

### ISSUE THREAD

**Issue by jnxey** [openkraken/kraken#962]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
Version: master/v0.9.0

### 重现步骤 ｜ Steps To Reproduce
使用npm init rax kraken-rax创建一个项目
运行npm install
运行npm start
用app打开
[Kraken] Run Kraken Playground App: 
http://[IP]:3333/kraken/home.js

**重现代码 | Code example:** 
没有修改模板的任何代码

**预期结果 ｜ Expected results:** 
正常显示

**实际结果 ｜ Actual results:** 
报错ReferenceError: 'WebSocket' is not defined

**Comment by answershuto** [comment]
websocket 是一个插件，可以根据业务需要按需使用，要用的话需接入插件。
http://openkraken.com/plugins/official/kraken_websocket

**Comment by jnxey** [comment]
> 

ok
