### ISSUE TITLE
滚动事件触发有问题

### ISSUE THREAD

**Issue by zelllez** [openkraken/kraken#963]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

kraken: '0.9.1-rc'
kraken_devtools: '0.4.0-dev.1'
lutter 2.2.3 • channel stable •
Dart 2.13.4

### 重现步骤 ｜ Steps To Reproduce

安卓真机，macos上 
![image](https://user-images.githubusercontent.com/36196697/145535482-ba19d24b-dd4a-4969-85c1-0907e80a0e84.png)

**重现代码 | Code example:** 
略

**预期结果 ｜ Expected results:** 
期望只需要绑定window滚动事件就可以抛出滚动事件

**实际结果 ｜ Actual results:** 

上述截图代码唯有在同时加上window的listener才会抛出documentElement的滚动事件
而同样的代码web端只会抛出window的滚动事件
而web端的document.documentElement单独绑定不会有事件抛出，单独绑定window的滚动事件可以抛出滚动事件

-----------------------

#925  这个bug提出的例子好像在我的环境下也是不能打印的
只有同时绑定documentElement才可以
```javascript
const container = document.createElement('div');
Object.assign(container.style, {
  height: '100px',
});

for (var i = 0; i < 9; i ++) {
  const item = document.createElement('div');
  Object.assign(item.style, {
    height: '145px',
    background: 'red',
    marginBottom: '10px',
  });
  container.appendChild(item);
}
document.body.appendChild(container);

function scrollListener() {
    console.log(11122)
}

document.documentElement.addEventListener('scroll', scrollListener);
window.addEventListener('scroll',()=>{});
```

**Comment by wssgcg1213** [comment]
收到你的问题, 我们会进行排查   

cc @temper357

**Comment by zelllez** [comment]
@temper357   any idea?
