### ISSUE TITLE
js devtool 调试 没有断点，没有console输出，没有文件选择，仅有element且经常自己刷新丢失上下文

### ISSUE THREAD

**Issue by zelllez** [openkraken/kraken#964]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

kraken: '0.9.1-rc'
kraken_devtools: '0.4.0-dev.1'
lutter 2.2.3 • channel stable •
Dart 2.13.4

### 重现步骤 ｜ Steps To Reproduce

```dart
Widget build(BuildContext context) {
    Kraken kraken = Kraken(
      bundleURL: 'http://10.80.42.107:8080/',
      devToolsService: ChromeDevToolsService(),
    );
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home: kraken);
  }
}
```

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 
应该可以在js端用`debugger`，console.log,在devtool中可以打印日志也可以在启动后的情形进入js断点调试

**实际结果 ｜ Actual results:** 
用`devtools://devtools/bundled/inspector.html?ws=10.80.42.107:9222` 可以打开看到用element面板看dom和css，但是source没有可选，console面板没有日志打出，仅有在启动的terminal有js日志输出，且与console.log同个上下文的debugger在devtool的source没有断点进入（断点时机是滚动事件，所以不存在启动devtool的先后问题）。

**Comment by wssgcg1213** [comment]
抱歉, 新版本 0.9.x 使用的 QuickJS 还没有对 JS Engine 的断点调试功能实现, 我们已经在做这一块了, 但是还需要一些时间

**Comment by wssgcg1213** [comment]
console 会在 stdout 输出, 对应 macos 是命令行或者控制台输出, 对应 android 可以查看 adb logcat

**Comment by zelllez** [comment]
好的，谢谢，期待 ❤️

**Comment by zelllez** [comment]
close时只有0.8可以调试js

**Comment by wssgcg1213** [comment]
是的, quickjs 调试 JS 断点能力目前仍未实现
