### ISSUE TITLE
无法使用APP本地图片

### ISSUE THREAD

**Issue by jnxey** [openkraken/kraken#974]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
v0.9.0

### 重现步骤 ｜ Steps To Reproduce
使用npm init rax <YourProjectName>初始化一个项目
在Home添加本地图片，
包括两种方式：1-img，2-background-image
使用在APP内定义了的images图片
均无法正常显示图片(在APP内可以正常显示图片)

**重现代码 | Code example:** 
## index.jsx
```
<img src="images/Home/top-bg.png" style={{ width: '750rpx', height: '308rpx' }} />
<View className={styles.homeTopBg} />
```

## index.module.css
```
.homeTopBg {
  width: 750rpx;
  height: 308rpx;
  background-image: url('images/Home/top-bg.png');
  background-size: cover;
}
```

## pubspec.yaml
```
flutter:
  uses-material-design: true
  assets:
    - images/Home/top-bg.png
```

**预期结果 ｜ Expected results:**
显示本地图片

**实际结果 ｜ Actual results:**
img-无法显示图片，也不报错
background-image-报错如下
error：
HTTP request failed, statusCode: 404, http://[ip]:3333/kraken/images/Home/top-bg.png

**Comment by answershuto** [comment]
本地使用 assets 协议。
assets://xxx/xxx.png

**Comment by jnxey** [comment]
改成也没有显示图片呀。
```
<img src="assets://images/Home/top-bg.png" style={{ width: '750rpx', height: '308rpx' }} />
```

**Comment by jnxey** [comment]
不是特别明白【本地使用 assets 协议。】
我已经在本地pubspec.yaml引入了图片。
在rax中使用assets开头也不行
```
<img src="assets://images/Home/top-bg.png" style={{ width: '750rpx', height: '308rpx' }} />
```
我的用法应该和
https://github.com/openkraken/gallery/blob/da5a89c2a12d7c5c1c889d7b57cc8f36481836ab/demos/gallery/src/pages/Home/index.jsx
https://github.com/openkraken/gallery/blob/main/pubspec.yaml#L71
是一样的

**Comment by andycall** [comment]
需要使用 main 分支，这个功能还没发版

**Comment by jnxey** [comment]
assets://功能没有发版的话，按理说，直接如下引入，应该是可以访问到图片的才对
```
<img src="images/Home/top-bg.png" style={{ width: '750rpx', height: '308rpx' }} />
```
我看匹配到的应该是ImageType.asset类型

**Comment by andycall** [comment]
Web 标准里面，`images/Home/top-bg.png` 默认会拼接上 location.href 地址。所以就访问不到 assets 了

**Comment by jnxey** [comment]
好的
