### ISSUE TITLE
码源不全啊 ,.gen目录怎么没有呢

### ISSUE THREAD

**Issue by dkbyjh** [openkraken/kraken#976]
## .gen目录没有啊,相关码源找不到啊
![image](https://user-images.githubusercontent.com/5645078/145914720-32e092df-feb5-4bc0-a3ee-fdd24d61f3b6.png)

**Comment by cnryb** [comment]
.gen 目录中的代码是自动生成的。
build 一下 bridge 就会生成，比如在项目根目录执行一下 `npm run build:bridge:macos:release`

**Comment by dkbyjh** [comment]
ok,感谢
