### ISSUE TITLE
Kraken导致dio的options.followRedirects: false失效

### ISSUE THREAD

**Issue by donfo** [openkraken/kraken#978]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

Version: v0.9.0

### 重现步骤 ｜ Steps To Reproduce

一但在项目里使用了Kraken()，就会导致dio设置的followRedirects: false失效。注释掉Kraken()就不会。

**预期结果 ｜ Expected results:** 
dio设置followRedirects: false生效

**实际结果 ｜ Actual results:** 
dio设置followRedirects: false失效

**Comment by wssgcg1213** [comment]
我来看下

**Comment by donfo** [comment]
@wssgcg1213 大佬，空了记得帮忙看下哇
