### ISSUE TITLE
Failed to execute 'setTimeout': dart method (setTimeout) is not registered.

### ISSUE THREAD

**Issue by pba-cra** [openkraken/kraken#981]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

0.8.0和0.8.4版本，ios环境下，android正常

### 重现步骤 ｜ Steps To Reproduce

setTimeout(()=>{},10)

**重现代码 | Code example:** 
setTimeout(()=>{},10)

**预期结果 ｜ Expected results:** 
执行正常

**实际结果 ｜ Actual results:** 

执行失败

**Comment by andycall** [comment]
我在 ios 上没有遇到这种情况，你确认没有改动什么代码吗？

https://github.com/andycall/kraken-example

**Comment by pba-cra** [comment]
> 我在 ios 上没有遇到这种情况，你确认没有改动什么代码吗？
> 
> https://github.com/andycall/kraken-example

不知道是否是跟使用safari调试有关 控制台输入setTimeout就会触发
