### ISSUE TITLE
vue基本响应式的问题

### ISSUE THREAD

**Issue by zelllez** [openkraken/kraken#989]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (6 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

kraken: 👉  '0.9.1-rc' /  0.8.4 👈 
kraken_devtools: '0.4.0-dev.1'  /  0.3.1
kraken_websocket: '1.0.6' / 0.2.0+1
vue 3.2.24

### 重现步骤 ｜ Steps To Reproduce

https://codesandbox.io/embed/wonderful-bash-w3d0k?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark

![image](https://user-images.githubusercontent.com/36196697/146352586-36a31ebe-903c-4ad3-8c49-bd39ce089ed4.png)

**重现代码 | Code example:** 
https://codesandbox.io/embed/wonderful-bash-w3d0k?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark

**预期结果 ｜ Expected results:** 
123

**实际结果 ｜ Actual results:** 
213

**Comment by answershuto** [comment]
试了一下最新的 kraken 已经修复这个问题了，我先关了。
![image](https://user-images.githubusercontent.com/17812136/149284965-4f9b1cf1-01b8-4d8b-9bfd-dc189b8f3e86.png)
