### ISSUE TITLE
Rax报错getComponentByLazy 

### ISSUE THREAD

**Issue by jnxey** [openkraken/kraken#995]
### 使用的 Kraken 版本 ｜ What version of kraken are you using
0.9.0

### 重现步骤 ｜ Steps To Reproduce
根据 https://rax.js.org/docs/guide/mpa-page-entry 文档里的runApp部分编写代码，
添加app.js和app.json到Home目录下，代码于示例一致
北海加载home.js后，报:
E/KRAKEN_NATIVE_LOG(29075): TypeError: not a function
E/KRAKEN_NATIVE_LOG(29075):     at getComponentByLazy (http://[ip]:3333/kraken/home.js:3084)
错误

将home.js中的var isWeb = true;改为false之后可以正常显示

**重现代码 | Code example:** 
  ├── src/                   
  │   └── pages/            
  │       ├── Home/     		
+ │       │   ├── app.js     # 自定义页面配置入口
+ │       │   ├── app.json   # 页面级别的 app.json 配置
- │       │   └── index.jsx

**预期结果 ｜ Expected results:**
正常显示

**实际结果 ｜ Actual results:**
报错

**Comment by yuanyan** [comment]
当前 Kraken 没有支持 MPA 模式，需要后续等多页面跳转完善

**Comment by wssgcg1213** [comment]
https://github.com/raxjs/rax-app/blob/master/packages/plugin-rax-router/src/runtime.tsx#L104

**Comment by wssgcg1213** [comment]
@jnxey 参考这篇文档: https://rax.js.org/docs/guide/mpa-page-entry#runApp

目前不建议在 Rax 的 MPA 下启用 SPA 的 router 功能，你可以删除页面路径下的 app.json 文件, 这样就不会启用路由功能了   

---
@yuanyan 这个 getComponentByLazy 底下会通过 dynamic import 异步加载一个页面的 bundle, 构建后实际是通过动态创建 script 标签方式引入和执行 js bundle 的, 估计是这里的时序有问题, 可以单独写个测试验证一下

**Comment by jnxey** [comment]
> @jnxey 参考这篇文档: https://rax.js.org/docs/guide/mpa-page-entry#runApp
> 
> 目前不建议在 Rax 的 MPA 下启用 SPA 的 router 功能，你可以删除页面路径下的 app.json 文件, 这样就不会启用路由功能了
> 
> @yuanyan 这个 getComponentByLazy 底下会通过 dynamic import 异步加载一个页面的 bundle, 构建后实际是通过动态创建 script 标签方式引入和执行 js bundle 的, 估计是这里的时序有问题, 可以单独写个测试验证一下

好的
