### ISSUE TITLE
Error: A value of type 'Future<bool> Function(Uri, String, String)?' can't be assigned to a variable of type 'Future<bool> Function(Uri, String, String?)?' because 'String?' is nullable and 'String' isn't.

### ISSUE THREAD

**Issue by qinuoyun** [openkraken/kraken#996]
官方demo
运行后
![image](https://user-images.githubusercontent.com/30451572/146677547-bc330b7e-21ff-41f7-bd5b-aee28253718c.png)

**Comment by andycall** [comment]
<h2 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.5em; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Flutter version scope</h2><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Only flutter stable released version are fully tested.</p>

Krake n | Flutter |
-- | --
|>= 0.7.0 < 0.8.0 | 1.22.0 ~ 1.22.6
|>= 0.8.0 < 0.10.0 | 2.2.0 ~ 2.2.3
