### ISSUE TITLE
几个响应式和布局问题

### ISSUE THREAD

**Issue by zelllez** [openkraken/kraken#997]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

Flutter 2.2.3 • channel stable • flutter/flutter.git
Framework • revision f4abaa0735 (6 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

kraken: 0.8.4
kraken_devtools: 0.3.1
kraken_websocket: 0.2.0+1
rax 1.2.2

### 重现步骤 ｜ Steps To Reproduce

https://codesandbox.io/embed/rax-quick-start-forked-u6ssh?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fpages%2FHome%2Findex.tsx&theme=dark

**重现代码 | Code example:** 
https://codesandbox.io/embed/rax-quick-start-forked-u6ssh?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fpages%2FHome%2Findex.tsx&theme=dark

**预期结果 ｜ Expected results:** 
有三个问题
上面实例内部有3个位置  搜索 bug NO.X 定位到

<table>
  <tr>
    <td>no</td>
    <td>描述</td>
    <td>截图</td>
  </tr>

  <tr>
    <td>1</td>
    <td>
      外部div有relative后会导致内部的ref的getBoundingClientRect不变化，接触relative注释后可以看第二点
    </td>
    <td>
	<img src="https://user-images.githubusercontent.com/36196697/146747214-4de6fec7-c3d9-4fcd-9ecc-29768363d171.png"/>
    </td>
  </tr>

  <tr>
    <td>2</td>
    <td>
      数据响应变化，但是显示内容没有变化
    </td>
    <td>
	<img src="https://user-images.githubusercontent.com/36196697/146748125-cfef8661-2f18-4c7b-b139-5d3ecca26e59.png" />
    </td>
  </tr>

  <tr>
    <td>3</td>
    <td>兄弟节点互斥情况布局不同导致显示被遮盖问题</td>
    <td>
	<img src="https://user-images.githubusercontent.com/36196697/146746827-f1154b88-cdf9-4a7b-978d-3d5e571129d0.png" />
    </td>
  </tr>
</table>

**实际结果 ｜ Actual results:** 

上面已说明

**Comment by temper357** [comment]
关联 PR 可解决上面问题
https://github.com/openkraken/kraken/pull/1214
https://github.com/openkraken/kraken/pull/1229
