### ISSUE TITLE
使用rax-app 创建和普通web创建，跑起npm run start 时功能子集不一致？

### ISSUE THREAD

**Issue by zelllez** [openkraken/kraken#999]
### 使用的 Kraken 版本 ｜ What version of kraken are you using

Flutter 2.2.3 • channel stable • flutter/flutter.git
Framework • revision f4abaa0735 (6 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

kraken: 0.8.4
kraken_devtools: 0.3.1
kraken_websocket: 0.2.0+1
rax 1.2.2

### 重现步骤 ｜ Steps To Reproduce

用 rax-app kraken模板创建时候 跑起来会报错

`[DriverKraken]: dangerouslySetInnerHTML is not supported.`

**重现代码 | Code example:** 

**预期结果 ｜ Expected results:** 

功能集应该一致

**实际结果 ｜ Actual results:** 

当前看到dangerouslySetInnerHTML 这个api不能用

期望有rax+kraken的搭配使用的最佳实践文档

**Comment by yuanyan** [comment]
kraken 最新版本已经支持 innerHTML，重新创建不会有这个问题
